build =
{
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car0_rch0_res0_hyp0", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car0_rch0_res0_hyp0", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car0_rch0_res0_hyp1", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car0_rch0_res0_hyp1", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car0_rch0_res1_hyp0", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car0_rch0_res1_hyp0", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car0_rch0_res1_hyp1", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car0_rch0_res1_hyp1", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car0_rch1_res0_hyp0", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car0_rch1_res0_hyp0", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car0_rch1_res0_hyp1", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car0_rch1_res0_hyp1", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car0_rch1_res1_hyp0", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car0_rch1_res1_hyp0", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car0_rch1_res1_hyp1", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car0_rch1_res1_hyp1", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car1_rch0_res0_hyp0", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car1_rch0_res0_hyp0", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car1_rch0_res0_hyp1", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car1_rch0_res0_hyp1", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car1_rch0_res1_hyp0", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car1_rch0_res1_hyp0", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car1_rch0_res1_hyp1", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car1_rch0_res1_hyp1", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car1_rch1_res0_hyp0", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car1_rch1_res0_hyp0", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car1_rch1_res0_hyp1", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car1_rch1_res0_hyp1", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car1_rch1_res1_hyp1", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car1_rch1_res1_hyp1", Type = Ship,},
	{Description = "MS", DisplayPriority = 13, DisplayedName = "MS_car1_rch1_res1_hyp0", RequiredFleetSubSystems = "", RequiredResearch = "", RequiredShipSubSystems = "", ThingToBuild = "Hgn_Mothership_car1_rch1_res1_hyp0", Type = Ship,},
	-- #1.0, capital_builds.lua
	{
		Description = "$7061",
		DisplayPriority = 118,
		DisplayedName = "$7060",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_BattlecruiserIonWeapons_hyp0",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Battlecruiser_hyp0",
		Type = Ship,
	},
	-- #2.0, capital_builds.lua
	{
		Description = "$7061",
		DisplayPriority = 118,
		DisplayedName = "$7060",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_BattlecruiserIonWeapons_hyp1",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Battlecruiser_hyp1",
		Type = Ship,
	},
	-- #3.0, capital_builds.lua
	{
		Description = "$7057",
		DisplayPriority = 116,
		DisplayedName = "$7056",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_DestroyerTech_hyp0",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Destroyer_hyp0",
		Type = Ship,
	},
	-- #4.0, capital_builds.lua
	{
		Description = "$7057",
		DisplayPriority = 116,
		DisplayedName = "$7056",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_DestroyerTech_hyp1",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Destroyer_hyp1",
		Type = Ship,
	},
	-- #5.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #6.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #7.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #8.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #9.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #10.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #11.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #12.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #13.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #14.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #15.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #16.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #17.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #18.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #19.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #20.0, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #21.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car0_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #22.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car1_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #23.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car0_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #24.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car1_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #25.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car0_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #26.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car1_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #27.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car0_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #28.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car1_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #29.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car0_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #30.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car1_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #31.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car0_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #32.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car1_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #33.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car0_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #34.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car1_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #35.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car0_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #36.0, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car1_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #37.0, carrier_builds.lua
	{
		Description = "$7019",
		DisplayPriority = 50,
		DisplayedName = "$7018",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_CloakGenerator_rch0",
		Type = SubSystem,
	},
	-- #38.0, carrier_builds.lua
	{
		Description = "$7019",
		DisplayPriority = 50,
		DisplayedName = "$7018",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_CloakGenerator_rch1",
		Type = SubSystem,
	},
	-- #39.0, carrier_builds.lua
	{
		Description = "$7021",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_FireControl_rch0",
		Type = SubSystem,
	},
	-- #40.0, carrier_builds.lua
	{
		Description = "$7021",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		RequiredFleetSubSystems = "AdvancedResearch",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_FireControl_rch1",
		Type = SubSystem,
	},
	-- #41.0, carrier_builds.lua
	{
		Description = "$7015",
		DisplayPriority = 30,
		DisplayedName = "$7014",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_Hyperspace_rch0",
		Type = SubSystem,
	},
	-- #42.0, carrier_builds.lua
	{
		Description = "$7015",
		DisplayPriority = 30,
		DisplayedName = "$7014",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_Hyperspace_rch1",
		Type = SubSystem,
	},
	-- #43.0, carrier_builds.lua
	{
		Description = "$7017",
		DisplayPriority = 40,
		DisplayedName = "$1826",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_HyperspaceInhibitor_rch0",
		Type = SubSystem,
	},
	-- #44.0, carrier_builds.lua
	{
		Description = "$7017",
		DisplayPriority = 40,
		DisplayedName = "$1826",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_HyperspaceInhibitor_rch1",
		Type = SubSystem,
	},
	-- #45.0, carrier_builds.lua
	{
		Description = "$7011",
		DisplayPriority = 0,
		DisplayedName = "$7010",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_Research",
		Type = SubSystem,
	},
	-- #46.0, carrier_builds.lua
	{
		Description = "$7013",
		DisplayPriority = 10,
		DisplayedName = "$7012",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_ResearchAdvanced",
		Type = SubSystem,
	},
	-- #47.0, carrier_builds.lua
	{
		Description = "$7023",
		DisplayPriority = 151,
		DisplayedName = "$7022",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Sensors_AdvancedArray",
		Type = SubSystem,
	},
	-- #48.0, carrier_builds.lua
	{
		Description = "$7025",
		DisplayPriority = 152,
		DisplayedName = "$7024",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Sensors_DetectCloaked",
		Type = SubSystem,
	},
	-- #49.0, carrier_builds.lua
	{
		Description = "$7037",
		DisplayPriority = 150,
		DisplayedName = "$7036",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Sensors_DetectHyperspace",
		Type = SubSystem,
	},
	-- #50.0, corvette_builds.lua
	{
		Description = "$7039",
		DisplayPriority = 50,
		DisplayedName = "$7038",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_AssaultCorvette_hyp0",
		Type = Ship,
	},
	-- #51.0, corvette_builds.lua
	{
		Description = "$7039",
		DisplayPriority = 50,
		DisplayedName = "$7038",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_AssaultCorvette_hyp1",
		Type = Ship,
	},
	-- #52.0, corvette_builds.lua
	{
		Description = "$7043",
		DisplayPriority = 52,
		DisplayedName = "$7042",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_GraviticAttractionMines_hyp0",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_MinelayerCorvette_hyp0",
		Type = Ship,
	},
	-- #53.0, corvette_builds.lua
	{
		Description = "$7043",
		DisplayPriority = 52,
		DisplayedName = "$7042",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_GraviticAttractionMines_hyp1",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_MinelayerCorvette_hyp1",
		Type = Ship,
	},
	-- #54.0, corvette_builds.lua
	{
		Description = "$7041",
		DisplayPriority = 51,
		DisplayedName = "$7040",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_PulsarCorvette_hyp0",
		Type = Ship,
	},
	-- #55.0, corvette_builds.lua
	{
		Description = "$7041",
		DisplayPriority = 51,
		DisplayedName = "$7040",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_PulsarCorvette_hyp1",
		Type = Ship,
	},
	-- #56.0, fighter_builds.lua
	{
		Description = "$7035",
		DisplayPriority = 30,
		DisplayedName = "$7034",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		ThingToBuild = "Hgn_AttackBomber_hyp0",
		Type = Ship,
	},
	-- #57.0, fighter_builds.lua
	{
		Description = "$7035",
		DisplayPriority = 30,
		DisplayedName = "$7034",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		ThingToBuild = "Hgn_AttackBomber_hyp1",
		Type = Ship,
	},
	-- #58.0, fighter_builds.lua
	{
		Description = "$7033",
		DisplayPriority = 20,
		DisplayedName = "$7032",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		ThingToBuild = "Hgn_Interceptor_hyp0",
		Type = Ship,
	},
	-- #59.0, fighter_builds.lua
	{
		Description = "$7033",
		DisplayPriority = 20,
		DisplayedName = "$7032",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		ThingToBuild = "Hgn_Interceptor_hyp1",
		Type = Ship,
	},
	-- #60.0, fighter_builds.lua
	{
--		Description = "$7031",
--		DisplayPriority = 10,
--		DisplayedName = "$7030",
		Description = "$7031",
		DisplayPriority = 11,
		DisplayedName = "Hgn_Scout_hyp0",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Scout_hyp0",
		Type = Ship,
	},
	-- #61.0, fighter_builds.lua
	{
--		Description = "$7031",
--		DisplayPriority = 10,
--		DisplayedName = "$7030",
		Description = "$7031",
		DisplayPriority = 12,
		DisplayedName = "Hgn_Scout_hyp1",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Scout_hyp1",
		Type = Ship,
	},
	-- test
	{ 
		Type =					Ship, 
		ThingToBuild =			"Hgn_Scout",
		RequiredResearch =		"",
		RequiredShipSubSystems =	"",
		DisplayPriority =		10,
		DisplayedName =			"Hgn_Scout",
		Description =			"$7031"
	},
	-- #62.0, frigate_builds.lua
	{
		Description = "$7049",
		DisplayPriority = 60,
		DisplayedName = "$7048",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_AssaultFrigate_hyp0",
		Type = Ship,
	},
	-- #63.0, frigate_builds.lua
	{
		Description = "$7049",
		DisplayPriority = 60,
		DisplayedName = "$7048",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_AssaultFrigate_hyp1",
		Type = Ship,
	},
	-- #64.0, frigate_builds.lua
	{
		Description = "$7045",
		DisplayPriority = 80,
		DisplayedName = "$7044",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_DefenseFieldFrigateShield_hyp0",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_DefenseFieldFrigate_hyp0",
		Type = Ship,
	},
	-- #65.0, frigate_builds.lua
	{
		Description = "$7045",
		DisplayPriority = 80,
		DisplayedName = "$7044",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_DefenseFieldFrigateShield_hyp1",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_DefenseFieldFrigate_hyp1",
		Type = Ship,
	},
	-- #66.0, frigate_builds.lua
	{
		Description = "$7051",
		DisplayPriority = 70,
		DisplayedName = "$1520",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_IonCannonFrigate_hyp0",
		Type = Ship,
	},
	-- #67.0, frigate_builds.lua
	{
		Description = "$7051",
		DisplayPriority = 70,
		DisplayedName = "$1520",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_IonCannonFrigate_hyp1",
		Type = Ship,
	},
	-- #68.0, frigate_builds.lua
	{
		Description = "$7053",
		DisplayPriority = 75,
		DisplayedName = "$7052",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_MarineFrigate_hyp0",
		Type = Ship,
	},
	-- #69.0, frigate_builds.lua
	{
		Description = "$7053",
		DisplayPriority = 75,
		DisplayedName = "$7052",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_MarineFrigate_hyp1",
		Type = Ship,
	},
	-- #70.0, frigate_builds.lua
	{
		Description = "$7047",
		DisplayPriority = 65,
		DisplayedName = "$7046",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_TorpedoFrigate_hyp0",
		Type = Ship,
	},
	-- #71.0, frigate_builds.lua
	{
		Description = "$7047",
		DisplayPriority = 65,
		DisplayedName = "$7046",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_TorpedoFrigate_hyp1",
		Type = Ship,
	},
	-- #72.0, mothership_builds.lua
	{
		Description = "$7019",
		DisplayPriority = 50,
		DisplayedName = "$7018",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_CloakGenerator_rch0",
		Type = SubSystem,
	},
	-- #73.0, mothership_builds.lua
	{
		Description = "$7019",
		DisplayPriority = 50,
		DisplayedName = "$7018",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_CloakGenerator_rch1",
		Type = SubSystem,
	},
	-- #74.0, mothership_builds.lua
	{
		Description = "$7021",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_FireControl_rch0",
		Type = SubSystem,
	},
	-- #75.0, mothership_builds.lua
	{
		Description = "$7021",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		RequiredFleetSubSystems = "AdvancedResearch",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_FireControl_rch1",
		Type = SubSystem,
	},
	-- #76.0, mothership_builds.lua
	{
		Description = "$7015",
		DisplayPriority = 30,
		DisplayedName = "$7014",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_Hyperspace_rch0",
		Type = SubSystem,
	},
	-- #77.0, mothership_builds.lua
	{
		Description = "$7015",
		DisplayPriority = 30,
		DisplayedName = "$7014",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_Hyperspace_rch1",
		Type = SubSystem,
	},
	-- #78.0, mothership_builds.lua
	{
		Description = "$7017",
		DisplayPriority = 40,
		DisplayedName = "$1826",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_HyperspaceInhibitor_rch0",
		Type = SubSystem,
	},
	-- #79.0, mothership_builds.lua
	{
		Description = "$7017",
		DisplayPriority = 40,
		DisplayedName = "$1826",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_HyperspaceInhibitor_rch1",
		Type = SubSystem,
	},
	-- #80.0, mothership_builds.lua
	{
		Description = "$7011",
		DisplayPriority = 0,
		DisplayedName = "$7010",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_Research",
		Type = SubSystem,
	},
	-- #81.0, mothership_builds.lua
	{
		Description = "$7013",
		DisplayPriority = 10,
		DisplayedName = "$7012",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_ResearchAdvanced",
		Type = SubSystem,
	},
	-- #82.0, mothership_builds.lua
	{
		Description = "$7023",
		DisplayPriority = 151,
		DisplayedName = "$7022",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Sensors_AdvancedArray",
		Type = SubSystem,
	},
	-- #83.0, mothership_builds.lua
	{
		Description = "$7025",
		DisplayPriority = 152,
		DisplayedName = "$7024",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Sensors_DetectCloaked",
		Type = SubSystem,
	},
	-- #84.0, mothership_builds.lua
	{
		Description = "$7037",
		DisplayPriority = 150,
		DisplayedName = "$7036",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Sensors_DetectHyperspace",
		Type = SubSystem,
	},
	-- #85.0, platform_builds.lua
	{
		Description = "$7063",
		DisplayPriority = 141,
		DisplayedName = "$7062",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "PlatformProduction",
		ThingToBuild = "Hgn_GunTurret_hyp0",
		Type = Ship,
	},
	-- #86.0, platform_builds.lua
	{
		Description = "$7063",
		DisplayPriority = 141,
		DisplayedName = "$7062",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "PlatformProduction",
		ThingToBuild = "Hgn_GunTurret_hyp1",
		Type = Ship,
	},
	-- #87.0, platform_builds.lua
	{
		Description = "$7065",
		DisplayPriority = 142,
		DisplayedName = "$1514",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_PlatformIonWeapons_hyp0",
		RequiredShipSubSystems = "PlatformProduction",
		ThingToBuild = "Hgn_IonTurret_hyp0",
		Type = Ship,
	},
	-- #88.0, platform_builds.lua
	{
		Description = "$7065",
		DisplayPriority = 142,
		DisplayedName = "$1514",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_PlatformIonWeapons_hyp1",
		RequiredShipSubSystems = "PlatformProduction",
		ThingToBuild = "Hgn_IonTurret_hyp1",
		Type = Ship,
	},
	-- #89.0, production_builds.lua
	{
		Description = "$7009",
		DisplayPriority = 10,
		DisplayedName = "$7008",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_PlatformControl",
		Type = SubSystem,
	},
	-- #90.0, production_builds.lua
	{
		Description = "$7003",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Production_Corvette_rch0",
		Type = SubSystem,
	},
	-- #91.0, production_builds.lua
	{
		Description = "$7003",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Production_Corvette_rch1",
		Type = SubSystem,
	},
	-- #92.0, production_builds.lua
	{
		Description = "$7001",
		DisplayPriority = 0,
		DisplayedName = "$7000",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Production_Fighter",
		Type = SubSystem,
	},
	-- #93.0, production_builds.lua
	{
		Description = "$7005",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Production_Frigate_rch0",
		Type = SubSystem,
	},
	-- #94.0, production_builds.lua
	{
		Description = "$7005",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Production_Frigate_rch1",
		Type = SubSystem,
	},
	-- #95.0, production_builds.lua
	{
		Description = "$7009",
		DisplayPriority = 20,
		DisplayedName = "$7008",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_PlatformControl",
		Type = SubSystem,
	},
	-- #96.0, production_builds.lua
	{
		Description = "$7007",
		DisplayPriority = 0,
		DisplayedName = "$7006",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_CapShip",
		Type = SubSystem,
	},
	-- #97.0, production_builds.lua
	{
		Description = "$7003",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_Corvette_rch0",
		Type = SubSystem,
	},
	-- #98.0, production_builds.lua
	{
		Description = "$7003",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_Corvette_rch1",
		Type = SubSystem,
	},
	-- #99.0, production_builds.lua
	{
		Description = "$7001",
		DisplayPriority = 0,
		DisplayedName = "$7000",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_Fighter",
		Type = SubSystem,
	},
	-- #100.0, production_builds.lua
	{
		Description = "$7005",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_Frigate_rch0",
		Type = SubSystem,
	},
	-- #101.0, production_builds.lua
	{
		Description = "$7005",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_Frigate_rch1",
		Type = SubSystem,
	},
	-- #102.0, production_builds.lua
	{
		Description = "$7007",
		DisplayPriority = 0,
		DisplayedName = "$7006",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_SY_Production_CapShip",
		Type = SubSystem,
	},
	-- #103.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #104.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #105.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #106.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #107.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #108.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #109.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #110.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #111.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #112.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #113.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #114.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #115.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #116.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #117.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #118.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #119.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #120.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #121.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #122.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #123.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #124.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #125.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #126.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #127.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #128.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #129.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #130.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #131.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #132.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #133.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #134.0, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #135.0, singleplayer_builds.lua
	{
		Description = "$7914",
		DisplayPriority = 53,
		DisplayedName = "$7913",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Kpr_Mover_hyp0",
		Type = Ship,
	},
	-- #136.0, singleplayer_builds.lua
	{
		Description = "$7914",
		DisplayPriority = 53,
		DisplayedName = "$7913",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Kpr_Mover_hyp1",
		Type = Ship,
	},
	-- #137.0, singleplayer_builds.lua
	{
		Description = "$7911",
		DisplayPriority = 10,
		DisplayedName = "$7910",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_MS_Production_CorvetteMover",
		Type = SubSystem,
	},
	-- #138.0, utility_builds.lua
	{
		Description = "$7075",
		DisplayPriority = 160,
		DisplayedName = "$7074",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_ECMProbe_hyp0",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ECMProbe_hyp0",
		Type = Ship,
	},
	-- #139.0, utility_builds.lua
	{
		Description = "$7075",
		DisplayPriority = 160,
		DisplayedName = "$7074",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_ECMProbe_hyp1",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ECMProbe_hyp1",
		Type = Ship,
	},
	-- #140.0, utility_builds.lua
	{
		Description = "$7071",
		DisplayPriority = 140,
		DisplayedName = "$7070",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Probe_hyp0",
		Type = Ship,
	},
	-- #141.0, utility_builds.lua
	{
		Description = "$7071",
		DisplayPriority = 140,
		DisplayedName = "$7070",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Probe_hyp1",
		Type = Ship,
	},
	-- #142.0, utility_builds.lua
	{
		Description = "$7073",
		DisplayPriority = 150,
		DisplayedName = "$7072",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_SensDisProbe_hyp0",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ProximitySensor_hyp0",
		Type = Ship,
	},
	-- #143.0, utility_builds.lua
	{
		Description = "$7073",
		DisplayPriority = 150,
		DisplayedName = "$7072",
		RequiredFleetSubSystems = "",
		RequiredResearch = "Hgn_SensDisProbe_hyp1",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ProximitySensor_hyp1",
		Type = Ship,
	},
	-- #144.0, utility_builds.lua
	{
		Description = "$7067",
		DisplayPriority = 120,
		DisplayedName = "$7066",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceCollector_res0_hyp0",
		Type = Ship,
	},
	-- #145.0, utility_builds.lua
	{
		Description = "$7067",
		DisplayPriority = 120,
		DisplayedName = "$7066",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceCollector_res1_hyp0",
		Type = Ship,
	},
	-- #146.0, utility_builds.lua
	{
		Description = "$7067",
		DisplayPriority = 120,
		DisplayedName = "$7066",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceCollector_res0_hyp1",
		Type = Ship,
	},
	-- #147.0, utility_builds.lua
	{
		Description = "$7067",
		DisplayPriority = 120,
		DisplayedName = "$7066",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceCollector_res1_hyp1",
		Type = Ship,
	},
	-- #148.0, utility_builds.lua
	{
		Description = "$7069",
		DisplayPriority = 130,
		DisplayedName = "$7068",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceController_res0_hyp0",
		Type = Ship,
	},
	-- #149.0, utility_builds.lua
	{
		Description = "$7069",
		DisplayPriority = 130,
		DisplayedName = "$7068",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceController_res1_hyp0",
		Type = Ship,
	},
	-- #150.0, utility_builds.lua
	{
		Description = "$7069",
		DisplayPriority = 130,
		DisplayedName = "$7068",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceController_res0_hyp1",
		Type = Ship,
	},
	-- #151.0, utility_builds.lua
	{
		Description = "$7069",
		DisplayPriority = 130,
		DisplayedName = "$7068",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceController_res1_hyp1",
		Type = Ship,
	},
}
