research =
{
	-- #1.0, ability_upgrades.lua
	{
		Cost = 1500,
		Description = "$7518",
		DisplayPriority = 30,
		DisplayedName = "$7517",
		Icon = Icon_Ability,
		Name = "Hgn_AttackBomberImprovedBombs",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		ShortDisplayedName = "$7208",
		TargetName = "Hgn_AttackBomber",
		TargetType = Ship,
		Time = 45,
		UpgradeName = "UseSpecialWeaponsInNormalAttack",
		UpgradeType = Ability,
	},
	-- #2.0, ability_upgrades.lua
	{
		Cost = 1500,
		Description = "$7522",
		DisplayPriority = 32,
		DisplayedName = "$7521",
		Icon = Icon_Ability,
		Name = "Hgn_DefenseFieldFrigateShield",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch & FrigateProduction",
		ShortDisplayedName = "$7210",
		TargetName = "Hgn_DefenseFieldFrigate",
		TargetType = Ship,
		Time = 60,
	},
	-- #3.0, ability_upgrades.lua
	{
		Cost = 1000,
		Description = "$7516",
		DisplayPriority = 29,
		DisplayedName = "$7515",
		Icon = Icon_Ability,
		Name = "Hgn_ImprovedTorpedo",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		ShortDisplayedName = "$7207",
		TargetName = "Hgn_TorpedoFrigate",
		TargetType = Ship,
		Time = 60,
		UpgradeName = "UseSpecialWeaponsInNormalAttack",
		UpgradeType = Ability,
	},
	-- #4.0, ability_upgrades.lua
	{
		Cost = 350,
		Description = "$7512",
		DisplayPriority = 26,
		DisplayedName = "$7511",
		Icon = Icon_Ability,
		Name = "Hgn_RepairAbility",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		ShortDisplayedName = "$7205",
		TargetName = "Hgn_ResourceCollector",
		TargetType = Ship,
		Time = 25,
		UpgradeName = "Repair",
		UpgradeType = Ability,
	},
	-- #5.0, ability_upgrades.lua
	{
		Cost = 1500,
		Description = "$7520",
		DisplayPriority = 31,
		DisplayedName = "$7519",
		Icon = Icon_Ability,
		Name = "Hgn_ScoutEMPAbility",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		ShortDisplayedName = "$7209",
		TargetName = "Hgn_Scout",
		TargetType = Ship,
		Time = 70,
		UpgradeName = "SpecialAttack",
		UpgradeType = Ability,
	},
	-- #6.0, ability_upgrades.lua
	{
		Cost = 500,
		Description = "$7514",
		DisplayPriority = 27,
		DisplayedName = "$7513",
		Icon = Icon_Ability,
		Name = "Hgn_ScoutPingAbility",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		ShortDisplayedName = "$7206",
		TargetName = "Hgn_Scout",
		TargetType = Ship,
		Time = 40,
		UpgradeName = "SensorPing",
		UpgradeType = Ability,
	},
	-- #7.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_AllShipBuildSpeed",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.025,
	},
	-- #8.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_AllShipBuildSpeedExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.075,
	},
	-- #9.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_AllShipBuildSpeedHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.05,
	},
	-- #10.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_cpuplayers_aggressive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #11.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_cpuplayers_defensive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #12.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_cpuplayers_dynamic",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #13.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_cpuplayers_norushtime10",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #14.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_cpuplayers_norushtime15",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #15.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_cpuplayers_norushtime5",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #16.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_ResourceCollectionRateExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "hgn_resourcecollector",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.08,
	},
	-- #17.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_ResourceCollectionRateHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "hgn_resourcecollector",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.04,
	},
	-- #18.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_WeaponDamageUpgrade125",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Hgn_fleet",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #19.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_WeaponDamageUpgrade150",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Hgn_fleet",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.5,
	},
	-- #20.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_WeaponDamageUpgrade175",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Hgn_fleet",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.75,
	},
	-- #21.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_WeaponDamageUpgrade200",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Hgn_fleet",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 2,
	},
	-- #22.0, battlecruiser_upgrades.lua
	{
		Cost = 1500,
		Description = "$7596",
		DisplayPriority = 401,
		DisplayedName = "$7595",
		Icon = Icon_Health,
		Name = "Hgn_BattlecruiserHealthUpgrade1",
		RequiredResearch = "Hgn_BattlecruiserIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		ShortDisplayedName = "$7254",
		TargetName = "Hgn_BattleCruiser",
		TargetType = Ship,
		Time = 90,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.4,
	},
	-- #23.0, battlecruiser_upgrades.lua
	{
		Cost = 600,
		Description = "$7600",
		DisplayPriority = 404,
		DisplayedName = "$7599",
		Icon = Icon_Speed,
		Name = "Hgn_BattlecruiserMAXSPEEDUpgrade1",
		RequiredResearch = "Hgn_BattlecruiserIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		ShortDisplayedName = "$7254",
		TargetName = "Hgn_BattleCruiser",
		TargetType = Ship,
		Time = 30,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #24.0, carrier_upgrades.lua
	{
		Cost = 2250,
		Description = "$7806",
		DisplayPriority = 65,
		DisplayedName = "$7805",
		Icon = Icon_Build,
		Name = "Hgn_CarrierBUILDSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch & CapShipProduction",
		ShortDisplayedName = "$7240",
		TargetName = "Hgn_Carrier",
		TargetType = Ship,
		Time = 60,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.3,
	},
	-- #25.0, carrier_upgrades.lua
	{
		Cost = 800,
		Description = "$7532",
		DisplayPriority = 61,
		DisplayedName = "$7531",
		Icon = Icon_Health,
		Name = "Hgn_CarrierHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		ShortDisplayedName = "$7221",
		TargetName = "Hgn_Carrier",
		TargetType = Ship,
		Time = 40,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.4,
	},
	-- #26.0, carrier_upgrades.lua
	{
		Cost = 400,
		Description = "$7536",
		DisplayPriority = 64,
		DisplayedName = "$7535",
		Icon = Icon_Speed,
		Name = "Hgn_CarrierMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		ShortDisplayedName = "$7221",
		TargetName = "Hgn_Carrier",
		TargetType = Ship,
		Time = 30,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #27.0, corvette_upgrade_health.lua
	{
		Cost = 800,
		Description = "$7556",
		DisplayPriority = 200,
		DisplayedName = "$7555",
		Icon = Icon_Health,
		Name = "Hgn_AssaultCorvetteHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		ShortDisplayedName = "$7237",
		TargetName = "Hgn_AssaultCorvette",
		TargetType = Ship,
		Time = 40,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.5,
	},
	-- #28.0, corvette_upgrade_health.lua
	{
		Cost = 1000,
		Description = "$7564",
		DisplayPriority = 206,
		DisplayedName = "$7563",
		Icon = Icon_Health,
		Name = "Hgn_PulsarCorvetteHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		ShortDisplayedName = "$7241",
		TargetName = "Hgn_PulsarCorvette",
		TargetType = Ship,
		Time = 50,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.5,
	},
	-- #29.0, corvette_upgrade_speed.lua
	{
		Cost = 400,
		Description = "$7560",
		DisplayPriority = 203,
		DisplayedName = "$7559",
		Icon = Icon_Speed,
		Name = "Hgn_AssaultCorvetteMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		ShortDisplayedName = "$7237",
		TargetName = "Hgn_AssaultCorvette",
		TargetType = Ship,
		Time = 20,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #30.0, corvette_upgrade_speed.lua
	{
		Cost = 600,
		Description = "$7568",
		DisplayPriority = 209,
		DisplayedName = "$7567",
		Icon = Icon_Speed,
		Name = "Hgn_PulsarCorvetteMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CorvetteProduction",
		ShortDisplayedName = "$7241",
		TargetName = "Hgn_PulsarCorvette",
		TargetType = Ship,
		Time = 30,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #31.0, default.lua
	{
		Cost = 1800,
		Description = "$7505",
		DisplayPriority = 1,
		DisplayedName = "$7504",
		Icon = Icon_Tech,
		Name = "Hgn_BattlecruiserIonWeapons",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch & CapShipProduction",
		ShortDisplayedName = "$7202",
		TargetName = "Hgn_BattleCruiser",
		TargetType = Ship,
		Time = 140,
	},
	-- #32.0, default.lua
	{
		Cost = 1500,
		Description = "$7508",
		DisplayPriority = 3,
		DisplayedName = "$7507",
		Icon = Icon_Tech,
		Name = "Hgn_DestroyerTech",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		ShortDisplayedName = "$7203",
		TargetName = "Hgn_Destroyer",
		TargetType = Ship,
		Time = 90,
	},
	-- #33.0, default.lua
	{
		Cost = 500,
		Description = "$7510",
		DisplayPriority = 4,
		DisplayedName = "$7509",
		Icon = Icon_Tech,
		Name = "Hgn_ECMProbe",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch",
		ShortDisplayedName = "$7204",
		TargetName = "Hgn_ECMProbe",
		TargetType = Ship,
		Time = 45,
	},
	-- #34.0, default.lua
	{
		Cost = 750,
		Description = "$7501",
		DisplayPriority = 2,
		DisplayedName = "$7500",
		Icon = Icon_Tech,
		Name = "Hgn_GraviticAttractionMines",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch & CorvetteProduction",
		ShortDisplayedName = "$7200",
		TargetName = "Hgn_MinelayerCorvette",
		TargetType = Ship,
		Time = 40,
	},
	-- #35.0, default.lua
	{
		Cost = 0,
		Description = "Enhances the fleet's hyperspace drive systems, reducing the hyperspace damage caused by gravity wells. Ships Only Take 10 11384919amage when forced out of hyperspace.",
		DisplayPriority = 950,
		DisplayedName = "Hyperspace Damage Reduction",
		DoNotGrant = 1,
		Name = "Hgn_HyperspaceDamageReductionUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "10Hyperspace Exit Damage",
		TargetName = "Hgn_fleet",
		TargetType = AllShips,
		Time = 0,
		UpgradeName = "HyperSpaceAbortDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0.4,
	},
	-- #36.0, default.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 1,
		DisplayedName = "",
		Name = "Hgn_InstaAdvancedFrigateTech",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch",
		TargetName = "Hgn_Mothership",
		TargetType = Ship,
		Time = 0,
	},
	-- #37.0, default.lua
	{
		Cost = 600,
		Description = "$7503",
		DisplayPriority = 24,
		DisplayedName = "$7502",
		Icon = Icon_Tech,
		Name = "Hgn_PlatformIonWeapons",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
		ShortDisplayedName = "$7201",
		TargetName = "Hgn_IonTurret",
		TargetType = Ship,
		Time = 100,
	},
	-- #38.0, default.lua
	{
		Cost = 500,
		Description = "$7651",
		DisplayPriority = 5,
		DisplayedName = "7650",
		Icon = Icon_Tech,
		Name = "Hgn_SensDisProbe",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$7214",
		TargetName = "Hgn_ProximitySensor",
		TargetType = Ship,
		Time = 35,
	},
	-- #39.0, destroyer_upgrades.lua
	{
		Cost = 1500,
		Description = "$7640",
		DisplayPriority = 405,
		DisplayedName = "$7639",
		Icon = Icon_Health,
		Name = "Hgn_DestroyerHealthUpgrade1",
		RequiredResearch = "Hgn_DestroyerTech",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		ShortDisplayedName = "$7274",
		TargetName = "Hgn_Destroyer",
		TargetType = Ship,
		Time = 90,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.4,
	},
	-- #40.0, destroyer_upgrades.lua
	{
		Cost = 600,
		Description = "$7644",
		DisplayPriority = 406,
		DisplayedName = "$7643",
		Icon = Icon_Speed,
		Name = "Hgn_DestroyerMAXSPEEDUpgrade1",
		RequiredResearch = "Hgn_DestroyerTech",
		RequiredSubSystems = "Research | AdvancedResearch & CapShipProduction",
		ShortDisplayedName = "$7274",
		TargetName = "Hgn_Destroyer",
		TargetType = Ship,
		Time = 40,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #41.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_SGMCapitalHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Hgn_Mothership",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.5,
	},
	-- #42.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_SGMCarrierHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Hgn_Carrier",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.65,
	},
	-- #43.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_SGMFrigateHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Frigate",
		TargetType = Family,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.65,
	},
	-- #44.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Hgn_SGMShipyardHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Hgn_Shipyard",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.5,
	},
	-- #45.0, fighter_upgrade_speed.lua
	{
		Cost = 400,
		Description = "$7552",
		DisplayPriority = 87,
		DisplayedName = "$7551",
		Icon = Icon_Speed,
		Name = "Hgn_AttackBomberMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		ShortDisplayedName = "$7234",
		TargetName = "Hgn_AttackBomber",
		TargetType = Ship,
		Time = 30,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.4,
	},
	-- #46.0, fighter_upgrade_speed.lua
	{
		Cost = 800,
		Description = "$7544",
		DisplayPriority = 81,
		DisplayedName = "$7543",
		Icon = Icon_Speed,
		Name = "Hgn_InterceptorMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FighterProduction",
		ShortDisplayedName = "$7231",
		TargetName = "Hgn_Interceptor",
		TargetType = Ship,
		Time = 30,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.4,
	},
	-- #47.0, frigate_upgrade_health.lua
	{
		Cost = 1000,
		Description = "$7588",
		DisplayPriority = 312,
		DisplayedName = "$7587",
		Icon = Icon_Health,
		Name = "Hgn_AssaultFrigateHealthUpgrade1",
		RequiredResearch = "Hgn_InstaAdvancedFrigateTech",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		ShortDisplayedName = "$7251",
		TargetName = "Hgn_AssaultFrigate",
		TargetType = Ship,
		Time = 75,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.4,
	},
	-- #48.0, frigate_upgrade_health.lua
	{
		Cost = 1000,
		Description = "$7580",
		DisplayPriority = 306,
		DisplayedName = "$7579",
		Icon = Icon_Health,
		Name = "Hgn_IonCannonFrigateHealthUpgrade1",
		RequiredResearch = "Hgn_InstaAdvancedFrigateTech",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		ShortDisplayedName = "$7247",
		TargetName = "Hgn_IonCannonFrigate",
		TargetType = Ship,
		Time = 75,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.4,
	},
	-- #49.0, frigate_upgrade_health.lua
	{
		Cost = 1000,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Icon = Icon_Health,
		Name = "Hgn_TorpedoFrigateHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		ShortDisplayedName = "$7244",
		TargetName = "Hgn_TorpedoFrigate",
		TargetType = Ship,
		Time = 75,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.4,
	},
	-- #50.0, frigate_upgrade_speed.lua
	{
		Cost = 600,
		Description = "$7592",
		DisplayPriority = 315,
		DisplayedName = "$7591",
		Icon = Icon_Speed,
		Name = "Hgn_AssaultFrigateMAXSPEEDUpgrade1",
		RequiredResearch = "Hgn_InstaAdvancedFrigateTech",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		ShortDisplayedName = "$7251",
		TargetName = "Hgn_AssaultFrigate",
		TargetType = Ship,
		Time = 50,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #51.0, frigate_upgrade_speed.lua
	{
		Cost = 600,
		Description = "$7584",
		DisplayPriority = 309,
		DisplayedName = "$7583",
		Icon = Icon_Speed,
		Name = "Hgn_IonCannonFrigateMAXSPEEDUpgrade1",
		RequiredResearch = "Hgn_InstaAdvancedFrigateTech",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		ShortDisplayedName = "$7247",
		TargetName = "Hgn_IonCannonFrigate",
		TargetType = Ship,
		Time = 50,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #52.0, frigate_upgrade_speed.lua
	{
		Cost = 600,
		Description = "$7576",
		DisplayPriority = 303,
		DisplayedName = "$7575",
		Icon = Icon_Speed,
		Name = "Hgn_TorpedoFrigateMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & FrigateProduction",
		ShortDisplayedName = "$7244",
		TargetName = "Hgn_TorpedoFrigate",
		TargetType = Ship,
		Time = 50,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #53.0, hyperspace_upgrades.lua
	{
		Cost = 500,
		Description = "$7628",
		DisplayPriority = 1000,
		DisplayedName = "$7627",
		Icon = Icon_Tech,
		Name = "Hgn_HyperspaceCostUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & Hyperspace",
		ShortDisplayedName = "$7280",
		TargetName = "Hgn_Mothership",
		TargetType = AllShips,
		Time = 45,
		UpgradeName = "HyperspaceCost",
		UpgradeType = Modifier,
		UpgradeValue = 0.75,
	},
	-- #54.0, hyperspace_upgrades.lua
	{
		Cost = 1000,
		Description = "$7630",
		DisplayPriority = 1000,
		DisplayedName = "$7629",
		Icon = Icon_Tech,
		Name = "Hgn_HyperspaceCostUpgrade2",
		RequiredResearch = "Hgn_HyperspaceCostUpgrade1",
		RequiredSubSystems = "AdvancedResearch | AdvancedResearch & Hyperspace",
		ShortDisplayedName = "$7281",
		TargetName = "Hgn_Mothership",
		TargetType = AllShips,
		Time = 60,
		UpgradeName = "HyperspaceCost",
		UpgradeType = Modifier,
		UpgradeValue = 0.6,
	},
	-- #55.0, mothership_upgrades.lua
	{
		Cost = 1000,
		Description = "$7801",
		DisplayPriority = 45,
		DisplayedName = "$7800",
		Icon = Icon_Build,
		Name = "Hgn_MothershipBUILDSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch",
		ShortDisplayedName = "$7240",
		TargetName = "Hgn_MotherShip",
		TargetType = Ship,
		Time = 60,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.3,
	},
	-- #56.0, mothership_upgrades.lua
	{
		Cost = 800,
		Description = "$7524",
		DisplayPriority = 41,
		DisplayedName = "$7523",
		Icon = Icon_Health,
		Name = "Hgn_MothershipHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		ShortDisplayedName = "$7211",
		TargetName = "Hgn_MotherShip",
		TargetType = Ship,
		Time = 30,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.75,
	},
	-- #57.0, mothership_upgrades.lua
	{
		Cost = 400,
		Description = "$7528",
		DisplayPriority = 44,
		DisplayedName = "$7527",
		Icon = Icon_Speed,
		Name = "Hgn_MothershipMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		ShortDisplayedName = "$7211",
		TargetName = "Hgn_MotherShip",
		TargetType = Ship,
		Time = 30,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #58.0, platform_upgrades.lua
	{
		Cost = 800,
		Description = "$7604",
		DisplayPriority = 600,
		DisplayedName = "$7603",
		Icon = Icon_Health,
		Name = "Hgn_GunTurretHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
		ShortDisplayedName = "$7257",
		TargetName = "Hgn_GunTurret",
		TargetType = Ship,
		Time = 40,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.5,
	},
	-- #59.0, platform_upgrades.lua
	{
		Cost = 800,
		Description = "$7608",
		DisplayPriority = 603,
		DisplayedName = "$7607",
		Icon = Icon_Health,
		Name = "Hgn_IonTurretHealthUpgrade1",
		RequiredResearch = "Hgn_PlatformIonWeapons",
		RequiredSubSystems = "Research | AdvancedResearch & PlatformProduction",
		ShortDisplayedName = "$7261",
		TargetName = "Hgn_IonTurret",
		TargetType = Ship,
		Time = 100,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.5,
	},
	-- #60.0, shipyard_upgrades.lua
	{
		Cost = 1000,
		Description = "$7811",
		DisplayPriority = 1204,
		DisplayedName = "$7810",
		Icon = Icon_Build,
		Name = "Hgn_ShipyardBUILDSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "AdvancedResearch & Hyperspace",
		ShortDisplayedName = "$7240",
		TargetName = "Hgn_Shipyard",
		TargetType = Ship,
		Time = 40,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.3,
	},
	-- #61.0, shipyard_upgrades.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 1204,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "Hgn_ShipyardBUILDSPEEDUpgrade1_Elohim",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "$7240",
		TargetName = "Hgn_Shipyard_Elohim",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.3,
	},
	-- #62.0, shipyard_upgrades.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 1204,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "Hgn_ShipyardBUILDSPEEDUpgrade1_SPG",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "$7240",
		TargetName = "Hgn_Shipyard_SPG",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.3,
	},
	-- #63.0, shipyard_upgrades.lua
	{
		Cost = 800,
		Description = "$7620",
		DisplayPriority = 1200,
		DisplayedName = "$7619",
		Icon = Icon_Health,
		Name = "Hgn_ShipyardHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & Hyperspace",
		ShortDisplayedName = "$7271",
		TargetName = "Hgn_Shipyard",
		TargetType = Ship,
		Time = 30,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.4,
	},
	-- #64.0, shipyard_upgrades.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 1200,
		DisplayedName = "",
		Icon = Icon_Health,
		Name = "Hgn_ShipyardHealthUpgrade1_Elohim",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "$7271",
		TargetName = "Hgn_Shipyard_Elohim",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.4,
	},
	-- #65.0, shipyard_upgrades.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 1200,
		DisplayedName = "",
		Icon = Icon_Health,
		Name = "Hgn_ShipyardHealthUpgrade1_SPG",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "$7271",
		TargetName = "Hgn_Shipyard_SPG",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.4,
	},
	-- #66.0, shipyard_upgrades.lua
	{
		Cost = 400,
		Description = "$7624",
		DisplayPriority = 1203,
		DisplayedName = "$7623",
		Icon = Icon_Speed,
		Name = "Hgn_ShipyardMAXSPEEDUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch & Hyperspace",
		ShortDisplayedName = "$7271",
		TargetName = "Hgn_Shipyard",
		TargetType = Ship,
		Time = 30,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #67.0, shipyard_upgrades.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 1203,
		DisplayedName = "",
		Icon = Icon_Speed,
		Name = "Hgn_ShipyardMAXSPEEDUpgrade1_Elohim",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "$7271",
		TargetName = "Hgn_Shipyard_Elohim",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #68.0, shipyard_upgrades.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 1203,
		DisplayedName = "",
		Icon = Icon_Speed,
		Name = "Hgn_ShipyardMAXSPEEDUpgrade1_SPG",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "$7271",
		TargetName = "Hgn_Shipyard_SPG",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #69.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1204,
		DisplayedName = "Elite Assault Corvette Weapon Upgrade",
		Name = "Hgn_AssaultCorvetteEliteWeaponUpgrade",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Hgn_AssaultCorvetteElite",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 2,
	},
	-- #70.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1205,
		DisplayedName = "Elite Attack Bomber Weapon Upgrade",
		Name = "Hgn_AttackBomberEliteWeaponUpgrade",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Hgn_AttackBomberElite",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.8,
	},
	-- #71.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_AttackDroidHealthUpgradeSPGAME_HIGH",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_AttackDroid",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 4,
	},
	-- #72.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_AttackDroidHealthUpgradeSPGAME_LOW",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_AttackDroid",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 2,
	},
	-- #73.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_AttackDroidHealthUpgradeSPGAME_MED",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_AttackDroid",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 3,
	},
	-- #74.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_AttackDroidWeaponUpgradeSPGAME_HIGH",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_AttackDroid",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 2,
	},
	-- #75.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_AttackDroidWeaponUpgradeSPGAME_LOW",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_AttackDroid",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.3,
	},
	-- #76.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_AttackDroidWeaponUpgradeSPGAME_MED",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_AttackDroid",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.6,
	},
	-- #77.0, singleplayer_hacks.lua
	{
		Cost = 500,
		Description = "$7901",
		DisplayPriority = 29,
		DisplayedName = "$7900",
		Name = "Hgn_DamageMoverTech",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "Research | AdvancedResearch",
		ShortDisplayedName = "$7902",
		TargetName = "Hgn_Mothership",
		TargetType = Ship,
		Time = 60,
	},
	-- #78.0, singleplayer_hacks.lua
	{
		Cost = 800,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_FrigateHealthUpgradeSPGAME",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Frigate",
		TargetType = Family,
		Time = 60,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 2.5,
	},
	-- #79.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperHealthUpgradeSPGAME_HIGH",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_Destroyer",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 4.5,
	},
	-- #80.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperHealthUpgradeSPGAME_LOW",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_Destroyer",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 2.5,
	},
	-- #81.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperHealthUpgradeSPGAME_M10_LVL_1",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_DestroyerM10",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 2,
	},
	-- #82.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperHealthUpgradeSPGAME_M10_LVL_2",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_DestroyerM10",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 3,
	},
	-- #83.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperHealthUpgradeSPGAME_M10_LVL_3",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_DestroyerM10",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 4,
	},
	-- #84.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperHealthUpgradeSPGAME_MED",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_Destroyer",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 3.5,
	},
	-- #85.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperWeaponUpgradeSPGAME_M10_LVL_1",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_DestroyerM10",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0.1,
	},
	-- #86.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperWeaponUpgradeSPGAME_M10_LVL_2",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_DestroyerM10",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0.2,
	},
	-- #87.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperWeaponUpgradeSPGAME_M10_LVL_3",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_DestroyerM10",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0.3,
	},
	-- #88.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperWeaponUpgradeSPGAME_M10_LVL_4",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_DestroyerM10",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0.4,
	},
	-- #89.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperWeaponUpgradeSPGAME_M10_LVL_5",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_DestroyerM10",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0.5,
	},
	-- #90.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "$7572",
		DisplayPriority = 300,
		DisplayedName = "$7571",
		Name = "Hgn_KeeperWeaponUpgradeSPGAME_M10_LVL_6",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_DestroyerM10",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0.6,
	},
	-- #91.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "Downgrades Mover health",
		DisplayPriority = 41,
		DisplayedName = "Mover health downgrade",
		Name = "Hgn_MoverHealthDowngrade",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_Mover",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1,
	},
	-- #92.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "Upgrades Mover health",
		DisplayPriority = 41,
		DisplayedName = "Mover health upgrade",
		Name = "Hgn_MoverHealthUpgrade",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kpr_Mover",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 5,
	},
	-- #93.0, singleplayer_hacks.lua
	{
		Cost = 500,
		Description = "$7906",
		DisplayPriority = 30,
		DisplayedName = "$7905",
		Name = "Hgn_RadiationDefenseField",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "Research | AdvancedResearch",
		ShortDisplayedName = "$7907",
		TargetName = "Hgn_DefenseFieldFrigate",
		TargetType = Ship,
		Time = 60,
		UpgradeName = "DefenseFieldShield",
		UpgradeType = Ability,
	},
	-- #94.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1213,
		DisplayedName = "SensorsBackToNormal1",
		Name = "Hgn_SensorsBackToNormal1",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Hgn_MotherShip",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "PrimarySensorsRange",
		UpgradeType = Modifier,
		UpgradeValue = 1,
	},
	-- #95.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1214,
		DisplayedName = "SensorsBackToNormal2",
		Name = "Hgn_SensorsBackToNormal2",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Hgn_MotherShip",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "SecondarySensorsRange",
		UpgradeType = Modifier,
		UpgradeValue = 1,
	},
	-- #96.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1215,
		DisplayedName = "SensorsBackToNormal3",
		Name = "Hgn_SensorsBackToNormal3",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Hgn_MotherShip",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "VisualRange",
		UpgradeType = Modifier,
		UpgradeValue = 1,
	},
	-- #97.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1210,
		DisplayedName = "Sensors Downgrade1",
		Name = "Hgn_SensorsDowngrade1",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Hgn_MotherShip",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "PrimarySensorsRange",
		UpgradeType = Modifier,
		UpgradeValue = 0.3,
	},
	-- #98.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1211,
		DisplayedName = "Sensors Downgrade2",
		Name = "Hgn_SensorsDowngrade2",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Hgn_MotherShip",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "SecondarySensorsRange",
		UpgradeType = Modifier,
		UpgradeValue = 0.3,
	},
	-- #99.0, singleplayer_hacks.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1212,
		DisplayedName = "Sensors Downgrade3",
		Name = "Hgn_SensorsDowngrade3",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Hgn_MotherShip",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "VisualRange",
		UpgradeType = Modifier,
		UpgradeValue = 0.3,
	},
	-- #100.0, utility_upgrades.lua
	{
		Cost = 1000,
		Description = "$7612",
		DisplayPriority = 701,
		DisplayedName = "$7611",
		Icon = Icon_Health,
		Name = "Hgn_ResourceCollectorHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		ShortDisplayedName = "$7264",
		TargetName = "Hgn_ResourceCollector",
		TargetType = Ship,
		Time = 90,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.6,
	},
	-- #101.0, utility_upgrades.lua
	{
		Cost = 400,
		Description = "$7616",
		DisplayPriority = 704,
		DisplayedName = "$7615",
		Icon = Icon_Health,
		Name = "Hgn_ResourceControllerHealthUpgrade1",
		RequiredResearch = "",
		RequiredSubSystems = "Research | AdvancedResearch",
		ShortDisplayedName = "$7267",
		TargetName = "Hgn_ResourceController",
		TargetType = Ship,
		Time = 60,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 1.6,
	},
}
