research =
{
	-- #1.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_AllShipBuildSpeed",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.025,
	},
	-- #2.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_AllShipBuildSpeedExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.075,
	},
	-- #3.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_AllShipBuildSpeedHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.05,
	},
	-- #4.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_aggressive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #5.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_defensive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #6.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_dynamic",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #7.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_norushtime10",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #8.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_norushtime15",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #9.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_norushtime5",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #10.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateExpert_res0_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res0_hyp0",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.09,
	},
	-- #11.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateExpert_res1_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp0",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.09,
	},
	-- #12.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateExpert_res0_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res0_hyp1",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.09,
	},
	-- #13.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateExpert_res1_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp1",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.09,
	},
	-- #14.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateHard_res0_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res0_hyp0",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.04,
	},
	-- #15.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateHard_res1_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp0",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.04,
	},
	-- #16.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateHard_res0_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res0_hyp1",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.04,
	},
	-- #17.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateHard_res1_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp1",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.04,
	},
	-- #18.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_WeaponDamageUpgrade125",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #19.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_WeaponDamageUpgrade150",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.5,
	},
	-- #20.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_WeaponDamageUpgrade175",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.75,
	},
	-- #21.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_WeaponDamageUpgrade200",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 2,
	},
	-- #22.0, corvette_tech.lua
	{
		Cost = 700,
		Description = "$11523",
		DisplayPriority = 22,
		DisplayedName = "$11522",
		Icon = Icon_Build,
		Name = "Tai_CorvetteChassis_hyp0",
		RequiredResearch = "Tai_CorvetteDrive_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11522",
		TargetName = "Tai_SalvageCorvette_hyp0",
		TargetType = Ship,
		Time = 60,
	},
	-- #23.0, corvette_tech.lua
	{
		Cost = 700,
		Description = "$11523",
		DisplayPriority = 22,
		DisplayedName = "$11522",
		Icon = Icon_Build,
		Name = "Tai_CorvetteChassis_hyp1",
		RequiredResearch = "Tai_CorvetteDrive_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11522",
		TargetName = "Tai_SalvageCorvette_hyp1",
		TargetType = Ship,
		Time = 60,
	},
	-- #24.0, corvette_tech.lua
	{
		Cost = 1000,
		Description = "$11517",
		DisplayPriority = 21,
		DisplayedName = "$11516",
		Icon = Icon_Build,
		Name = "Tai_CorvetteDrive_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11516",
		TargetName = "Tai_LightCorvette_hyp0",
		TargetType = Ship,
		Time = 75,
	},
	-- #25.0, corvette_tech.lua
	{
		Cost = 1000,
		Description = "$11517",
		DisplayPriority = 21,
		DisplayedName = "$11516",
		Icon = Icon_Build,
		Name = "Tai_CorvetteDrive_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11516",
		TargetName = "Tai_LightCorvette_hyp1",
		TargetType = Ship,
		Time = 75,
	},
	-- #26.0, corvette_tech.lua
	{
		Cost = 500,
		Description = "$11511",
		DisplayPriority = 24,
		DisplayedName = "$11510",
		Icon = Icon_Build,
		Name = "Tai_FastTrackingTurrets_hyp0",
		RequiredResearch = "Tai_CorvetteChassis_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11510",
		TargetName = "Tai_MultiGunCorvette_hyp0",
		TargetType = Ship,
		Time = 40,
	},
	-- #27.0, corvette_tech.lua
	{
		Cost = 500,
		Description = "$11511",
		DisplayPriority = 24,
		DisplayedName = "$11510",
		Icon = Icon_Build,
		Name = "Tai_FastTrackingTurrets_hyp1",
		RequiredResearch = "Tai_CorvetteChassis_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11510",
		TargetName = "Tai_MultiGunCorvette_hyp1",
		TargetType = Ship,
		Time = 40,
	},
	-- #28.0, corvette_tech.lua
	{
		Cost = 400,
		Description = "$11519",
		DisplayPriority = 23,
		DisplayedName = "$11518",
		Icon = Icon_Build,
		Name = "Tai_HeavyCorvetteUpgrade_hyp0",
		RequiredResearch = "Tai_CorvetteChassis_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11518",
		TargetName = "Tai_HeavyCorvette_hyp0",
		TargetType = Ship,
		Time = 30,
	},
	-- #29.0, corvette_tech.lua
	{
		Cost = 400,
		Description = "$11519",
		DisplayPriority = 23,
		DisplayedName = "$11518",
		Icon = Icon_Build,
		Name = "Tai_HeavyCorvetteUpgrade_hyp1",
		RequiredResearch = "Tai_CorvetteChassis_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11518",
		TargetName = "Tai_HeavyCorvette_hyp1",
		TargetType = Ship,
		Time = 30,
	},
	-- #30.0, corvette_tech.lua
	{
		Cost = 1200,
		Description = "$11521",
		DisplayPriority = 25,
		DisplayedName = "$11520",
		Icon = Icon_Build,
		Name = "Tai_MinelayingTech_hyp0",
		RequiredResearch = "Tai_CorvetteChassis_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11520",
		TargetName = "Tai_MinelayerCorvette_hyp0",
		TargetType = Ship,
		Time = 100,
	},
	-- #31.0, corvette_tech.lua
	{
		Cost = 1200,
		Description = "$11521",
		DisplayPriority = 25,
		DisplayedName = "$11520",
		Icon = Icon_Build,
		Name = "Tai_MinelayingTech_hyp1",
		RequiredResearch = "Tai_CorvetteChassis_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11520",
		TargetName = "Tai_MinelayerCorvette_hyp1",
		TargetType = Ship,
		Time = 100,
	},
	-- #32.0, default.lua
	{
		Cost = 500,
		Description = "$11559",
		DisplayPriority = 54,
		DisplayedName = "$11558",
		Icon = Icon_Build,
		Name = "Tai_CloakGenerator_hyp0",
		RequiredResearch = "Tai_CapitalShipDrive_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11558",
		TargetName = "Tai_CloakGenerator_hyp0",
		TargetType = Ship,
		Time = 50,
	},
	-- #33.0, default.lua
	{
		Cost = 500,
		Description = "$11559",
		DisplayPriority = 54,
		DisplayedName = "$11558",
		Icon = Icon_Build,
		Name = "Tai_CloakGenerator_hyp1",
		RequiredResearch = "Tai_CapitalShipDrive_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11558",
		TargetName = "Tai_CloakGenerator_hyp1",
		TargetType = Ship,
		Time = 50,
	},
	-- #34.0, default.lua
	{
		Cost = 500,
		Description = "$11557",
		DisplayPriority = 53,
		DisplayedName = "$11556",
		Icon = Icon_Build,
		Name = "Tai_GravityGenerator_hyp0",
		RequiredResearch = "Tai_CapitalShipDrive_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11556",
		TargetName = "Tai_GravWellGenerator_hyp0",
		TargetType = Ship,
		Time = 100,
	},
	-- #35.0, default.lua
	{
		Cost = 500,
		Description = "$11557",
		DisplayPriority = 53,
		DisplayedName = "$11556",
		Icon = Icon_Build,
		Name = "Tai_GravityGenerator_hyp1",
		RequiredResearch = "Tai_CapitalShipDrive_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11556",
		TargetName = "Tai_GravWellGenerator_hyp1",
		TargetType = Ship,
		Time = 100,
	},
	-- #36.0, default.lua
	{
		Cost = 0,
		Description = "Enhances the fleet's hyperspace drive systems, reducing the hyperspace damage caused by gravity wells. Ships only take 10 11384919amage when forced out of hyperspace.",
		DisplayPriority = 950,
		DisplayedName = "Hyperspace Damage Reduction",
		DoNotGrant = 1,
		Name = "Tai_HyperspaceDamageReductionUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "10Hyperspace Exit Damage",
		TargetName = "Tai_fleet",
		TargetType = AllShips,
		Time = 0,
		UpgradeName = "HyperSpaceAbortDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0.4,
	},
	-- #37.0, default.lua
	{
		Cost = 0,
		Description = "Enhances the fleet's hyperspace drive systems, reducing the hyperspace damage caused by gravity wells. Heavy Cruisers only take 0 11384919amage when forced out of hyperspace.",
		DisplayPriority = 951,
		DisplayedName = "Hyperspace Damage Reduction",
		DoNotGrant = 1,
		Name = "Tai_HyperspaceDamageReductionUpgradeHC_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "0HC Hyperspace Exit Damage",
		TargetName = "Tai_HeavyCruiser_hyp0",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "HyperSpaceAbortDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0,
	},
	-- #38.0, default.lua
	{
		Cost = 0,
		Description = "Enhances the fleet's hyperspace drive systems, reducing the hyperspace damage caused by gravity wells. Heavy Cruisers only take 0 11384919amage when forced out of hyperspace.",
		DisplayPriority = 951,
		DisplayedName = "Hyperspace Damage Reduction",
		DoNotGrant = 1,
		Name = "Tai_HyperspaceDamageReductionUpgradeHC_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "0HC Hyperspace Exit Damage",
		TargetName = "Tai_HeavyCruiser_hyp1",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "HyperSpaceAbortDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0,
	},
	-- #39.0, default.lua
	{
		Cost = 500,
		Description = "$11553",
		DisplayPriority = 51,
		DisplayedName = "$11552",
		Icon = Icon_Build,
		Name = "Tai_ProximitySensor_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11552",
		TargetName = "Tai_ProximitySensor_hyp0",
		TargetType = Ship,
		Time = 40,
	},
	-- #40.0, default.lua
	{
		Cost = 500,
		Description = "$11553",
		DisplayPriority = 51,
		DisplayedName = "$11552",
		Icon = Icon_Build,
		Name = "Tai_ProximitySensor_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11552",
		TargetName = "Tai_ProximitySensor_hyp1",
		TargetType = Ship,
		Time = 40,
	},
	-- #41.0, default.lua
	{
		Cost = 500,
		Description = "$11555",
		DisplayPriority = 52,
		DisplayedName = "$11554",
		Icon = Icon_Build,
		Name = "Tai_SensorArray_hyp0",
		RequiredResearch = "Tai_ProximitySensor_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11554",
		TargetName = "Tai_SensorArray_hyp0",
		TargetType = Ship,
		Time = 50,
	},
	-- #42.0, default.lua
	{
		Cost = 500,
		Description = "$11555",
		DisplayPriority = 52,
		DisplayedName = "$11554",
		Icon = Icon_Build,
		Name = "Tai_SensorArray_hyp1",
		RequiredResearch = "Tai_ProximitySensor_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11554",
		TargetName = "Tai_SensorArray_hyp1",
		TargetType = Ship,
		Time = 50,
	},
	-- #43.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_SGMCapitalHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.5,
	},
	-- #44.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_SGMFrigateHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Frigate",
		TargetType = Family,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.45,
	},
	-- #45.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_SGMGravWellHealth_hyp0",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Tai_GravWellGenerator_hyp0",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.2,
	},
	-- #46.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_SGMGravWellHealth_hyp1",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Tai_GravWellGenerator_hyp1",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.2,
	},
	-- #47.0, fighter_tech.lua
	{
		Cost = 800,
		Description = "$11529",
		DisplayPriority = 13,
		DisplayedName = "$11528",
		Icon = Icon_Build,
		Name = "Tai_DefenderSubSystems_hyp0",
		RequiredResearch = "Tai_FighterDrive_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11528",
		TargetName = "Tai_Defender_hyp0",
		TargetType = Ship,
		Time = 75,
	},
	-- #48.0, fighter_tech.lua
	{
		Cost = 800,
		Description = "$11529",
		DisplayPriority = 13,
		DisplayedName = "$11528",
		Icon = Icon_Build,
		Name = "Tai_DefenderSubSystems_hyp1",
		RequiredResearch = "Tai_FighterDrive_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11528",
		TargetName = "Tai_Defender_hyp1",
		TargetType = Ship,
		Time = 75,
	},
	-- #49.0, fighter_tech.lua
	{
		Cost = 1000,
		Description = "$11509",
		DisplayPriority = 15,
		DisplayedName = "$11508",
		Icon = Icon_Build,
		Name = "Tai_DefenseFighter_hyp0",
		RequiredResearch = "Tai_FighterChassis_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11508",
		TargetName = "Tai_DefenseFighter_hyp0",
		TargetType = Ship,
		Time = 100,
	},
	-- #50.0, fighter_tech.lua
	{
		Cost = 1000,
		Description = "$11509",
		DisplayPriority = 15,
		DisplayedName = "$11508",
		Icon = Icon_Build,
		Name = "Tai_DefenseFighter_hyp1",
		RequiredResearch = "Tai_FighterChassis_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11508",
		TargetName = "Tai_DefenseFighter_hyp1",
		TargetType = Ship,
		Time = 100,
	},
	-- #51.0, fighter_tech.lua
	{
		Cost = 300,
		Description = "$11515",
		DisplayPriority = 12,
		DisplayedName = "$11514",
		Icon = Icon_Build,
		Name = "Tai_FighterChassis_hyp0",
		RequiredResearch = "Tai_FighterDrive_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11514",
		TargetName = "Tai_Interceptor_hyp0",
		TargetType = Ship,
		Time = 30,
	},
	-- #52.0, fighter_tech.lua
	{
		Cost = 300,
		Description = "$11515",
		DisplayPriority = 12,
		DisplayedName = "$11514",
		Icon = Icon_Build,
		Name = "Tai_FighterChassis_hyp1",
		RequiredResearch = "Tai_FighterDrive_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11514",
		TargetName = "Tai_Interceptor_hyp1",
		TargetType = Ship,
		Time = 30,
	},
	-- #53.0, fighter_tech.lua
	{
		Cost = 200,
		Description = "$11503",
		DisplayPriority = 11,
		DisplayedName = "$11502",
		Icon = Icon_Build,
		Name = "Tai_FighterDrive_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11502",
		TargetName = "Tai_Scout_hyp0",
		TargetType = Ship,
		Time = 20,
	},
	-- #54.0, fighter_tech.lua
	{
		Cost = 200,
		Description = "$11503",
		DisplayPriority = 11,
		DisplayedName = "$11502",
		Icon = Icon_Build,
		Name = "Tai_FighterDrive_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11502",
		TargetName = "Tai_Scout_hyp1",
		TargetType = Ship,
		Time = 20,
	},
	-- #55.0, fighter_tech.lua
	{
		Cost = 400,
		Description = "$11513",
		DisplayPriority = 14,
		DisplayedName = "$11512",
		Icon = Icon_Build,
		Name = "Tai_PlasmaBombLauncher_hyp0",
		RequiredResearch = "Tai_FighterChassis_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11512",
		TargetName = "Tai_AttackBomber_hyp0",
		TargetType = Ship,
		Time = 40,
	},
	-- #56.0, fighter_tech.lua
	{
		Cost = 400,
		Description = "$11513",
		DisplayPriority = 14,
		DisplayedName = "$11512",
		Icon = Icon_Build,
		Name = "Tai_PlasmaBombLauncher_hyp1",
		RequiredResearch = "Tai_FighterChassis_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11512",
		TargetName = "Tai_AttackBomber_hyp1",
		TargetType = Ship,
		Time = 40,
	},
	-- #57.0, frigate_tech.lua
	{
		Cost = 1200,
		Description = "$11541",
		DisplayPriority = 32,
		DisplayedName = "$11540",
		Icon = Icon_Build,
		Name = "Tai_CapitalShipChassis_hyp0",
		RequiredResearch = "Tai_CapitalShipDrive_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11540",
		TargetName = "Tai_AssaultFrigate_hyp0",
		TargetType = Ship,
		Time = 90,
	},
	-- #58.0, frigate_tech.lua
	{
		Cost = 1200,
		Description = "$11541",
		DisplayPriority = 32,
		DisplayedName = "$11540",
		Icon = Icon_Build,
		Name = "Tai_CapitalShipChassis_hyp1",
		RequiredResearch = "Tai_CapitalShipDrive_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11540",
		TargetName = "Tai_AssaultFrigate_hyp1",
		TargetType = Ship,
		Time = 90,
	},
	-- #59.0, frigate_tech.lua
	{
		Cost = 1000,
		Description = "$11527",
		DisplayPriority = 31,
		DisplayedName = "$11526",
		Icon = Icon_Build,
		Name = "Tai_CapitalShipDrive_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11526",
		TargetName = "Tai_SupportFrigate_hyp0",
		TargetType = Ship,
		Time = 75,
	},
	-- #60.0, frigate_tech.lua
	{
		Cost = 1000,
		Description = "$11527",
		DisplayPriority = 31,
		DisplayedName = "$11526",
		Icon = Icon_Build,
		Name = "Tai_CapitalShipDrive_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11526",
		TargetName = "Tai_SupportFrigate_hyp1",
		TargetType = Ship,
		Time = 75,
	},
	-- #61.0, frigate_tech.lua
	{
		Cost = 1100,
		Description = "$11539",
		DisplayPriority = 34,
		DisplayedName = "$11538",
		Icon = Icon_Build,
		Name = "Tai_DefenseField_hyp0",
		RequiredResearch = "Tai_CapitalShipChassis_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11538",
		TargetName = "Tai_FieldFrigate_hyp0",
		TargetType = Ship,
		Time = 80,
	},
	-- #62.0, frigate_tech.lua
	{
		Cost = 1100,
		Description = "$11539",
		DisplayPriority = 34,
		DisplayedName = "$11538",
		Icon = Icon_Build,
		Name = "Tai_DefenseField_hyp1",
		RequiredResearch = "Tai_CapitalShipChassis_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11538",
		TargetName = "Tai_FieldFrigate_hyp1",
		TargetType = Ship,
		Time = 80,
	},
	-- #63.0, frigate_tech.lua
	{
		Cost = 1700,
		Description = "$11535",
		DisplayPriority = 33,
		DisplayedName = "$11534",
		Icon = Icon_Build,
		Name = "Tai_IonCannons_hyp0",
		RequiredResearch = "Tai_CapitalShipChassis_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11534",
		TargetName = "Tai_IonCannonFrigate_hyp0",
		TargetType = Ship,
		Time = 120,
	},
	-- #64.0, frigate_tech.lua
	{
		Cost = 1700,
		Description = "$11535",
		DisplayPriority = 33,
		DisplayedName = "$11534",
		Icon = Icon_Build,
		Name = "Tai_IonCannons_hyp1",
		RequiredResearch = "Tai_CapitalShipChassis_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11534",
		TargetName = "Tai_IonCannonFrigate_hyp1",
		TargetType = Ship,
		Time = 120,
	},
	-- #65.0, supercapital_tech.lua
	{
		Cost = 3500,
		Description = "$11547",
		DisplayPriority = 44,
		DisplayedName = "$11546",
		Icon = Icon_Build,
		Name = "Tai_GuidedMissiles_hyp0",
		RequiredResearch = "Tai_SuperCapitalShipDrive_res0_hyp0 | Tai_SuperCapitalShipDrive_res1_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11546",
		TargetName = "Tai_MissileDestroyer_hyp0",
		TargetType = Ship,
		Time = 120,
	},
	-- #66.0, supercapital_tech.lua
	{
		Cost = 3500,
		Description = "$11547",
		DisplayPriority = 44,
		DisplayedName = "$11546",
		Icon = Icon_Build,
		Name = "Tai_GuidedMissiles_hyp1",
		RequiredResearch = "Tai_SuperCapitalShipDrive_res0_hyp1 | Tai_SuperCapitalShipDrive_res1_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11546",
		TargetName = "Tai_MissileDestroyer_hyp1",
		TargetType = Ship,
		Time = 120,
	},
	-- #67.0, supercapital_tech.lua
	{
		Cost = 7000,
		Description = "$11551",
		DisplayPriority = 46,
		DisplayedName = "$11550",
		Icon = Icon_Build,
		Name = "Tai_HeavyGuns_hyp0",
		RequiredResearch = "(Tai_SuperCapitalShipDrive_res0_hyp0 | Tai_SuperCapitalShipDrive_res1_hyp0) & Tai_SuperHeavyChassis_hyp0 & Tai_IonCannons_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11550",
		TargetName = "Tai_HeavyCruiser_hyp0",
		TargetType = Ship,
		Time = 360,
	},
	-- #68.0, supercapital_tech.lua
	{
		Cost = 7000,
		Description = "$11551",
		DisplayPriority = 46,
		DisplayedName = "$11550",
		Icon = Icon_Build,
		Name = "Tai_HeavyGuns_hyp1",
		RequiredResearch = "(Tai_SuperCapitalShipDrive_res0_hyp1 | Tai_SuperCapitalShipDrive_res1_hyp1) & Tai_SuperHeavyChassis_hyp1 & Tai_IonCannons_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11550",
		TargetName = "Tai_HeavyCruiser_hyp1",
		TargetType = Ship,
		Time = 360,
	},
	-- #69.0, supercapital_tech.lua
	{
		Cost = 1500,
		Description = "$11543",
		DisplayPriority = 41,
		DisplayedName = "$11542",
		Icon = Icon_Build,
		Name = "Tai_SuperCapitalShipDrive_res0_hyp0",
		RequiredResearch = "Tai_CapitalShipChassis_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res0_hyp0",
		TargetType = Ship,
		Time = 50,
	},
	-- #70.0, supercapital_tech.lua
	{
		Cost = 1500,
		Description = "$11543",
		DisplayPriority = 41,
		DisplayedName = "$11542",
		Icon = Icon_Build,
		Name = "Tai_SuperCapitalShipDrive_res1_hyp0",
		RequiredResearch = "Tai_CapitalShipChassis_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res1_hyp0",
		TargetType = Ship,
		Time = 50,
	},
	-- #71.0, supercapital_tech.lua
	{
		Cost = 1500,
		Description = "$11543",
		DisplayPriority = 41,
		DisplayedName = "$11542",
		Icon = Icon_Build,
		Name = "Tai_SuperCapitalShipDrive_res0_hyp1",
		RequiredResearch = "Tai_CapitalShipChassis_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res0_hyp1",
		TargetType = Ship,
		Time = 50,
	},
	-- #72.0, supercapital_tech.lua
	{
		Cost = 1500,
		Description = "$11543",
		DisplayPriority = 41,
		DisplayedName = "$11542",
		Icon = Icon_Build,
		Name = "Tai_SuperCapitalShipDrive_res1_hyp1",
		RequiredResearch = "Tai_CapitalShipChassis_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res1_hyp1",
		TargetType = Ship,
		Time = 50,
	},
	-- #73.0, supercapital_tech.lua
	{
		Cost = 4000,
		Description = "$11561",
		DisplayPriority = 45,
		DisplayedName = "$11560",
		Icon = Icon_Build,
		Name = "Tai_SuperHeavyChassis_hyp0",
		RequiredResearch = "(Tai_SuperCapitalShipDrive_res0_hyp0 | Tai_SuperCapitalShipDrive_res1_hyp0) & Tai_IonCannons_hyp0",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11560",
		TargetName = "Tai_Destroyer_hyp0",
		TargetType = Ship,
		Time = 140,
	},
	-- #74.0, supercapital_tech.lua
	{
		Cost = 4000,
		Description = "$11561",
		DisplayPriority = 45,
		DisplayedName = "$11560",
		Icon = Icon_Build,
		Name = "Tai_SuperHeavyChassis_hyp1",
		RequiredResearch = "(Tai_SuperCapitalShipDrive_res0_hyp1 | Tai_SuperCapitalShipDrive_res1_hyp1) & Tai_IonCannons_hyp1",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11560",
		TargetName = "Tai_Destroyer_hyp1",
		TargetType = Ship,
		Time = 140,
	},
}
