research =
{
	-- #1.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_AllShipBuildSpeed",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.025,
	},
	-- #2.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_AllShipBuildSpeedExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.075,
	},
	-- #3.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_AllShipBuildSpeedHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.05,
	},
	-- #4.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_cpuplayers_aggressive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_fleet",
		TargetType = AllShips,
		Time = 1,
	},
	-- #5.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_cpuplayers_defensive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_fleet",
		TargetType = AllShips,
		Time = 1,
	},
	-- #6.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_cpuplayers_dynamic",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_fleet",
		TargetType = AllShips,
		Time = 1,
	},
	-- #7.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_cpuplayers_norushtime10",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_fleet",
		TargetType = AllShips,
		Time = 1,
	},
	-- #8.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_cpuplayers_norushtime15",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_fleet",
		TargetType = AllShips,
		Time = 1,
	},
	-- #9.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_cpuplayers_norushtime5",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_fleet",
		TargetType = AllShips,
		Time = 1,
	},
	-- #10.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_ResourceCollectionRateExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_ResourceCollector",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.09,
	},
	-- #11.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_ResourceCollectionRateHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_ResourceCollector",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.04,
	},
	-- #12.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_WeaponDamageUpgrade125",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_fleet",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #13.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_WeaponDamageUpgrade150",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_fleet",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.5,
	},
	-- #14.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_WeaponDamageUpgrade175",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_fleet",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.75,
	},
	-- #15.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_WeaponDamageUpgrade200",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Kus_fleet",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 2,
	},
	-- #16.0, corvette_tech.lua
	{
		Cost = 700,
		Description = "$11523",
		DisplayPriority = 22,
		DisplayedName = "$11522",
		Icon = Icon_Build,
		Name = "Kus_CorvetteChassis",
		RequiredResearch = "Kus_CorvetteDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11522",
		TargetName = "Kus_SalvageCorvette",
		TargetType = Ship,
		Time = 60,
	},
	-- #17.0, corvette_tech.lua
	{
		Cost = 1000,
		Description = "$11517",
		DisplayPriority = 21,
		DisplayedName = "$11516",
		Icon = Icon_Build,
		Name = "Kus_CorvetteDrive",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11516",
		TargetName = "Kus_LightCorvette",
		TargetType = Ship,
		Time = 75,
	},
	-- #18.0, corvette_tech.lua
	{
		Cost = 500,
		Description = "$11511",
		DisplayPriority = 24,
		DisplayedName = "$11510",
		Icon = Icon_Build,
		Name = "Kus_FastTrackingTurrets",
		RequiredResearch = "Kus_CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11510",
		TargetName = "Kus_MultiGunCorvette",
		TargetType = Ship,
		Time = 40,
	},
	-- #19.0, corvette_tech.lua
	{
		Cost = 400,
		Description = "$11519",
		DisplayPriority = 23,
		DisplayedName = "$11518",
		Icon = Icon_Build,
		Name = "Kus_HeavyCorvetteUpgrade",
		RequiredResearch = "Kus_CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11518",
		TargetName = "Kus_HeavyCorvette",
		TargetType = Ship,
		Time = 30,
	},
	-- #20.0, corvette_tech.lua
	{
		Cost = 1200,
		Description = "$11521",
		DisplayPriority = 25,
		DisplayedName = "$11520",
		Icon = Icon_Build,
		Name = "Kus_MinelayingTech",
		RequiredResearch = "Kus_CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11520",
		TargetName = "Kus_MinelayerCorvette",
		TargetType = Ship,
		Time = 100,
	},
	-- #21.0, default.lua
	{
		Cost = 500,
		Description = "$11559",
		DisplayPriority = 54,
		DisplayedName = "$11558",
		Icon = Icon_Build,
		Name = "Kus_CloakGenerator",
		RequiredResearch = "Kus_CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11558",
		TargetName = "Kus_CloakGenerator",
		TargetType = Ship,
		Time = 50,
	},
	-- #22.0, default.lua
	{
		Cost = 500,
		Description = "$11557",
		DisplayPriority = 53,
		DisplayedName = "$11556",
		Icon = Icon_Build,
		Name = "Kus_GravityGenerator",
		RequiredResearch = "Kus_CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11556",
		TargetName = "Kus_GravWellGenerator",
		TargetType = Ship,
		Time = 100,
	},
	-- #23.0, default.lua
	{
		Cost = 0,
		Description = "Enhances the fleet's hyperspace drive systems, reducing the hyperspace damage caused by gravity wells. Ships only take 10 11384919amage when forced out of hyperspace.",
		DisplayPriority = 950,
		DisplayedName = "Hyperspace Damage Reduction",
		DoNotGrant = 1,
		Name = "Kus_HyperspaceDamageReductionUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "10Hyperspace Exit Damage",
		TargetName = "Kus_fleet",
		TargetType = AllShips,
		Time = 0,
		UpgradeName = "HyperSpaceAbortDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0.4,
	},
	-- #24.0, default.lua
	{
		Cost = 0,
		Description = "Enhances the fleet's hyperspace drive systems, reducing the hyperspace damage caused by gravity wells. Heavy Cruisers only take 0 11384919amage when forced out of hyperspace.",
		DisplayPriority = 951,
		DisplayedName = "Hyperspace Damage Reduction",
		DoNotGrant = 1,
		Name = "Kus_HyperspaceDamageReductionUpgradeHC",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "0HC Hyperspace Exit Damage",
		TargetName = "Kus_HeavyCruiser",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "HyperSpaceAbortDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0,
	},
	-- #25.0, default.lua
	{
		Cost = 500,
		Description = "$11553",
		DisplayPriority = 51,
		DisplayedName = "$11552",
		Icon = Icon_Build,
		Name = "Kus_ProximitySensor",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11552",
		TargetName = "Kus_ProximitySensor",
		TargetType = Ship,
		Time = 40,
	},
	-- #26.0, default.lua
	{
		Cost = 500,
		Description = "$11555",
		DisplayPriority = 52,
		DisplayedName = "$11554",
		Icon = Icon_Build,
		Name = "Kus_SensorArray",
		RequiredResearch = "Kus_ProximitySensor",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11554",
		TargetName = "Kus_SensorArray",
		TargetType = Ship,
		Time = 50,
	},
	-- #27.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_SGMCapitalHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.5,
	},
	-- #28.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_SGMFrigateHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Frigate",
		TargetType = Family,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.45,
	},
	-- #29.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Kus_SGMGravWellHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Kus_GravWellGenerator",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.2,
	},
	-- #30.0, fighter_tech.lua
	{
		Cost = 1000,
		Description = "$11507",
		DisplayPriority = 15,
		DisplayedName = "$11506",
		Icon = Icon_Build,
		Name = "Kus_CloakedFighter",
		RequiredResearch = "Kus_FighterChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11506",
		TargetName = "Kus_CloakedFighter",
		TargetType = Ship,
		Time = 100,
	},
	-- #31.0, fighter_tech.lua
	{
		Cost = 800,
		Description = "$11529",
		DisplayPriority = 13,
		DisplayedName = "$11528",
		Icon = Icon_Build,
		Name = "Kus_DefenderSubSystems",
		RequiredResearch = "Kus_FighterDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11528",
		TargetName = "Kus_Defender",
		TargetType = Ship,
		Time = 75,
	},
	-- #32.0, fighter_tech.lua
	{
		Cost = 300,
		Description = "$11515",
		DisplayPriority = 12,
		DisplayedName = "$11514",
		Icon = Icon_Build,
		Name = "Kus_FighterChassis",
		RequiredResearch = "Kus_FighterDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11514",
		TargetName = "Kus_Interceptor",
		TargetType = Ship,
		Time = 30,
	},
	-- #33.0, fighter_tech.lua
	{
		Cost = 200,
		Description = "$11503",
		DisplayPriority = 11,
		DisplayedName = "$11502",
		Icon = Icon_Build,
		Name = "Kus_FighterDrive",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11502",
		TargetName = "Kus_Scout",
		TargetType = Ship,
		Time = 20,
	},
	-- #34.0, fighter_tech.lua
	{
		Cost = 400,
		Description = "$11513",
		DisplayPriority = 14,
		DisplayedName = "$11512",
		Icon = Icon_Build,
		Name = "Kus_PlasmaBombLauncher",
		RequiredResearch = "Kus_FighterChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11512",
		TargetName = "Kus_AttackBomber",
		TargetType = Ship,
		Time = 40,
	},
	-- #35.0, frigate_tech.lua
	{
		Cost = 1200,
		Description = "$11541",
		DisplayPriority = 32,
		DisplayedName = "$11540",
		Icon = Icon_Build,
		Name = "Kus_CapitalShipChassis",
		RequiredResearch = "Kus_CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11540",
		TargetName = "Kus_AssaultFrigate",
		TargetType = Ship,
		Time = 90,
	},
	-- #36.0, frigate_tech.lua
	{
		Cost = 1000,
		Description = "$11527",
		DisplayPriority = 31,
		DisplayedName = "$11526",
		Icon = Icon_Build,
		Name = "Kus_CapitalShipDrive",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11526",
		TargetName = "Kus_SupportFrigate",
		TargetType = Ship,
		Time = 75,
	},
	-- #37.0, frigate_tech.lua
	{
		Cost = 1100,
		Description = "$11537",
		DisplayPriority = 34,
		DisplayedName = "$11536",
		Icon = Icon_Build,
		Name = "Kus_DroneTechnology",
		RequiredResearch = "Kus_CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11536",
		TargetName = "Kus_DroneFrigate",
		TargetType = Ship,
		Time = 80,
	},
	-- #38.0, frigate_tech.lua
	{
		Cost = 1700,
		Description = "$11535",
		DisplayPriority = 33,
		DisplayedName = "$11534",
		Icon = Icon_Build,
		Name = "Kus_IonCannons",
		RequiredResearch = "Kus_CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11534",
		TargetName = "Kus_IonCannonFrigate",
		TargetType = Ship,
		Time = 120,
	},
	-- #39.0, supercapital_tech.lua
	{
		Cost = 3500,
		Description = "$11547",
		DisplayPriority = 44,
		DisplayedName = "$11546",
		Icon = Icon_Build,
		Name = "Kus_GuidedMissiles",
		RequiredResearch = "Kus_SuperCapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11546",
		TargetName = "Kus_MissileDestroyer",
		TargetType = Ship,
		Time = 120,
	},
	-- #40.0, supercapital_tech.lua
	{
		Cost = 7000,
		Description = "$11551",
		DisplayPriority = 46,
		DisplayedName = "$11550",
		Icon = Icon_Build,
		Name = "Kus_HeavyGuns",
		RequiredResearch = "Kus_SuperHeavyChassis & Kus_SuperCapitalShipDrive & Kus_IonCannons",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11550",
		TargetName = "Kus_HeavyCruiser",
		TargetType = Ship,
		Time = 360,
	},
	-- #41.0, supercapital_tech.lua
	{
		Cost = 1500,
		Description = "$11543",
		DisplayPriority = 41,
		DisplayedName = "$11542",
		Icon = Icon_Build,
		Name = "Kus_SuperCapitalShipDrive",
		RequiredResearch = "Kus_CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11542",
		TargetName = "Kus_Carrier",
		TargetType = Ship,
		Time = 50,
	},
	-- #42.0, supercapital_tech.lua
	{
		Cost = 4000,
		Description = "$11561",
		DisplayPriority = 45,
		DisplayedName = "$11560",
		Icon = Icon_Build,
		Name = "Kus_SuperHeavyChassis",
		RequiredResearch = "Kus_SuperCapitalShipDrive & Kus_IonCannons",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11560",
		TargetName = "Kus_Destroyer",
		TargetType = Ship,
		Time = 140,
	},
}
