VariantResearch =
{
	tai_allshipbuildspeed =
	{
		TAI_ALLSHIPBUILDSPEED,
	},
	tai_allshipbuildspeedexpert =
	{
		TAI_ALLSHIPBUILDSPEEDEXPERT,
	},
	tai_allshipbuildspeedhard =
	{
		TAI_ALLSHIPBUILDSPEEDHARD,
	},
	tai_cpuplayers_aggressive =
	{
		TAI_CPUPLAYERS_AGGRESSIVE,
	},
	tai_cpuplayers_defensive =
	{
		TAI_CPUPLAYERS_DEFENSIVE,
	},
	tai_cpuplayers_dynamic =
	{
		TAI_CPUPLAYERS_DYNAMIC,
	},
	tai_cpuplayers_norushtime10 =
	{
		TAI_CPUPLAYERS_NORUSHTIME10,
	},
	tai_cpuplayers_norushtime15 =
	{
		TAI_CPUPLAYERS_NORUSHTIME15,
	},
	tai_cpuplayers_norushtime5 =
	{
		TAI_CPUPLAYERS_NORUSHTIME5,
	},
	tai_resourcecollectionrateexpert =
	{
		TAI_RESOURCECOLLECTIONRATEEXPERT_RES0_HYP0,
		TAI_RESOURCECOLLECTIONRATEEXPERT_RES1_HYP0,
		TAI_RESOURCECOLLECTIONRATEEXPERT_RES0_HYP1,
		TAI_RESOURCECOLLECTIONRATEEXPERT_RES1_HYP1,
	},
	tai_resourcecollectionratehard =
	{
		TAI_RESOURCECOLLECTIONRATEHARD_RES0_HYP0,
		TAI_RESOURCECOLLECTIONRATEHARD_RES1_HYP0,
		TAI_RESOURCECOLLECTIONRATEHARD_RES0_HYP1,
		TAI_RESOURCECOLLECTIONRATEHARD_RES1_HYP1,
	},
	tai_weapondamageupgrade125 =
	{
		TAI_WEAPONDAMAGEUPGRADE125,
	},
	tai_weapondamageupgrade150 =
	{
		TAI_WEAPONDAMAGEUPGRADE150,
	},
	tai_weapondamageupgrade175 =
	{
		TAI_WEAPONDAMAGEUPGRADE175,
	},
	tai_weapondamageupgrade200 =
	{
		TAI_WEAPONDAMAGEUPGRADE200,
	},
	tai_corvettechassis =
	{
		TAI_CORVETTECHASSIS_HYP0,
		TAI_CORVETTECHASSIS_HYP1,
	},
	tai_corvettedrive =
	{
		TAI_CORVETTEDRIVE_HYP0,
		TAI_CORVETTEDRIVE_HYP1,
	},
	tai_fasttrackingturrets =
	{
		TAI_FASTTRACKINGTURRETS_HYP0,
		TAI_FASTTRACKINGTURRETS_HYP1,
	},
	tai_heavycorvetteupgrade =
	{
		TAI_HEAVYCORVETTEUPGRADE_HYP0,
		TAI_HEAVYCORVETTEUPGRADE_HYP1,
	},
	tai_minelayingtech =
	{
		TAI_MINELAYINGTECH_HYP0,
		TAI_MINELAYINGTECH_HYP1,
	},
	tai_cloakgenerator =
	{
		TAI_CLOAKGENERATOR_HYP0,
		TAI_CLOAKGENERATOR_HYP1,
	},
	tai_gravitygenerator =
	{
		TAI_GRAVITYGENERATOR_HYP0,
		TAI_GRAVITYGENERATOR_HYP1,
	},
	tai_hyperspacedamagereductionupgrade =
	{
		TAI_HYPERSPACEDAMAGEREDUCTIONUPGRADE,
	},
	tai_hyperspacedamagereductionupgradehc =
	{
		TAI_HYPERSPACEDAMAGEREDUCTIONUPGRADEHC_HYP0,
		TAI_HYPERSPACEDAMAGEREDUCTIONUPGRADEHC_HYP1,
	},
	tai_proximitysensor =
	{
		TAI_PROXIMITYSENSOR_HYP0,
		TAI_PROXIMITYSENSOR_HYP1,
	},
	tai_sensorarray =
	{
		TAI_SENSORARRAY_HYP0,
		TAI_SENSORARRAY_HYP1,
	},
	tai_sgmcapitalhealth =
	{
		TAI_SGMCAPITALHEALTH,
	},
	tai_sgmfrigatehealth =
	{
		TAI_SGMFRIGATEHEALTH,
	},
	tai_sgmgravwellhealth =
	{
		TAI_SGMGRAVWELLHEALTH_HYP0,
		TAI_SGMGRAVWELLHEALTH_HYP1,
	},
	tai_defendersubsystems =
	{
		TAI_DEFENDERSUBSYSTEMS_HYP0,
		TAI_DEFENDERSUBSYSTEMS_HYP1,
	},
	tai_defensefighter =
	{
		TAI_DEFENSEFIGHTER_HYP0,
		TAI_DEFENSEFIGHTER_HYP1,
	},
	tai_fighterchassis =
	{
		TAI_FIGHTERCHASSIS_HYP0,
		TAI_FIGHTERCHASSIS_HYP1,
	},
	tai_fighterdrive =
	{
		TAI_FIGHTERDRIVE_HYP0,
		TAI_FIGHTERDRIVE_HYP1,
	},
	tai_plasmabomblauncher =
	{
		TAI_PLASMABOMBLAUNCHER_HYP0,
		TAI_PLASMABOMBLAUNCHER_HYP1,
	},
	tai_capitalshipchassis =
	{
		TAI_CAPITALSHIPCHASSIS_HYP0,
		TAI_CAPITALSHIPCHASSIS_HYP1,
	},
	tai_capitalshipdrive =
	{
		TAI_CAPITALSHIPDRIVE_HYP0,
		TAI_CAPITALSHIPDRIVE_HYP1,
	},
	tai_defensefield =
	{
		TAI_DEFENSEFIELD_HYP0,
		TAI_DEFENSEFIELD_HYP1,
	},
	tai_ioncannons =
	{
		TAI_IONCANNONS_HYP0,
		TAI_IONCANNONS_HYP1,
	},
	tai_guidedmissiles =
	{
		TAI_GUIDEDMISSILES_HYP0,
		TAI_GUIDEDMISSILES_HYP1,
	},
	tai_heavyguns =
	{
		TAI_HEAVYGUNS_HYP0,
		TAI_HEAVYGUNS_HYP1,
	},
	tai_supercapitalshipdrive =
	{
		TAI_SUPERCAPITALSHIPDRIVE_RES0_HYP0,
		TAI_SUPERCAPITALSHIPDRIVE_RES1_HYP0,
		TAI_SUPERCAPITALSHIPDRIVE_RES0_HYP1,
		TAI_SUPERCAPITALSHIPDRIVE_RES1_HYP1,
	},
	tai_superheavychassis =
	{
		TAI_SUPERHEAVYCHASSIS_HYP0,
		TAI_SUPERHEAVYCHASSIS_HYP1,
	},
}
