VariantBuilds =
{
	hgn_battlecruiser =
	{
		HGN_BATTLECRUISER_HYP0,
		HGN_BATTLECRUISER_HYP1,
	},
	hgn_destroyer =
	{
		HGN_DESTROYER_HYP0,
		HGN_DESTROYER_HYP1,
	},
	hgn_carrier =
	{
		HGN_CARRIER_CAR0_RCH0_RES0_HYP0,
		HGN_CARRIER_CAR1_RCH0_RES0_HYP0,
		HGN_CARRIER_CAR0_RCH0_RES1_HYP0,
		HGN_CARRIER_CAR1_RCH0_RES1_HYP0,
		HGN_CARRIER_CAR0_RCH0_RES0_HYP1,
		HGN_CARRIER_CAR1_RCH0_RES0_HYP1,
		HGN_CARRIER_CAR0_RCH0_RES1_HYP1,
		HGN_CARRIER_CAR1_RCH0_RES1_HYP1,
		HGN_CARRIER_CAR0_RCH1_RES0_HYP0,
		HGN_CARRIER_CAR1_RCH1_RES0_HYP0,
		HGN_CARRIER_CAR0_RCH1_RES1_HYP0,
		HGN_CARRIER_CAR1_RCH1_RES1_HYP0,
		HGN_CARRIER_CAR0_RCH1_RES0_HYP1,
		HGN_CARRIER_CAR1_RCH1_RES0_HYP1,
		HGN_CARRIER_CAR0_RCH1_RES1_HYP1,
		HGN_CARRIER_CAR1_RCH1_RES1_HYP1,
	},
	hgn_shipyard =
	{
		HGN_SHIPYARD_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARD_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARD_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARD_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARD_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARD_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARD_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARD_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARD_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARD_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARD_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARD_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARD_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARD_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARD_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARD_CAR1_RCH1_RES1_HYP1,
	},
	hgn_c_module_cloakgenerator =
	{
		HGN_C_MODULE_CLOAKGENERATOR_RCH0,
		HGN_C_MODULE_CLOAKGENERATOR_RCH1,
	},
	hgn_c_module_firecontrol =
	{
		HGN_C_MODULE_FIRECONTROL_RCH0,
		HGN_C_MODULE_FIRECONTROL_RCH1,
	},
	hgn_c_module_hyperspace =
	{
		HGN_C_MODULE_HYPERSPACE_RCH0,
		HGN_C_MODULE_HYPERSPACE_RCH1,
	},
	hgn_c_module_hyperspaceinhibitor =
	{
		HGN_C_MODULE_HYPERSPACEINHIBITOR_RCH0,
		HGN_C_MODULE_HYPERSPACEINHIBITOR_RCH1,
	},
	hgn_c_module_research =
	{
		HGN_C_MODULE_RESEARCH,
	},
	hgn_c_module_researchadvanced =
	{
		HGN_C_MODULE_RESEARCHADVANCED,
	},
	hgn_c_sensors_advancedarray =
	{
		HGN_C_SENSORS_ADVANCEDARRAY,
	},
	hgn_c_sensors_detectcloaked =
	{
		HGN_C_SENSORS_DETECTCLOAKED,
	},
	hgn_c_sensors_detecthyperspace =
	{
		HGN_C_SENSORS_DETECTHYPERSPACE,
	},
	hgn_assaultcorvette =
	{
		HGN_ASSAULTCORVETTE_HYP0,
		HGN_ASSAULTCORVETTE_HYP1,
	},
	hgn_minelayercorvette =
	{
		HGN_MINELAYERCORVETTE_HYP0,
		HGN_MINELAYERCORVETTE_HYP1,
	},
	hgn_pulsarcorvette =
	{
		HGN_PULSARCORVETTE_HYP0,
		HGN_PULSARCORVETTE_HYP1,
	},
	hgn_attackbomber =
	{
		HGN_ATTACKBOMBER_HYP0,
		HGN_ATTACKBOMBER_HYP1,
	},
	hgn_interceptor =
	{
		HGN_INTERCEPTOR_HYP0,
		HGN_INTERCEPTOR_HYP1,
	},
	hgn_scout =
	{
		HGN_SCOUT_HYP0,
		HGN_SCOUT_HYP1,
	},
	hgn_assaultfrigate =
	{
		HGN_ASSAULTFRIGATE_HYP0,
		HGN_ASSAULTFRIGATE_HYP1,
	},
	hgn_defensefieldfrigate =
	{
		HGN_DEFENSEFIELDFRIGATE_HYP0,
		HGN_DEFENSEFIELDFRIGATE_HYP1,
	},
	hgn_ioncannonfrigate =
	{
		HGN_IONCANNONFRIGATE_HYP0,
		HGN_IONCANNONFRIGATE_HYP1,
	},
	hgn_marinefrigate =
	{
		HGN_MARINEFRIGATE_HYP0,
		HGN_MARINEFRIGATE_HYP1,
	},
	hgn_torpedofrigate =
	{
		HGN_TORPEDOFRIGATE_HYP0,
		HGN_TORPEDOFRIGATE_HYP1,
	},
	hgn_ms_module_cloakgenerator =
	{
		HGN_MS_MODULE_CLOAKGENERATOR_RCH0,
		HGN_MS_MODULE_CLOAKGENERATOR_RCH1,
	},
	hgn_ms_module_firecontrol =
	{
		HGN_MS_MODULE_FIRECONTROL_RCH0,
		HGN_MS_MODULE_FIRECONTROL_RCH1,
	},
	hgn_ms_module_hyperspace =
	{
		HGN_MS_MODULE_HYPERSPACE_RCH0,
		HGN_MS_MODULE_HYPERSPACE_RCH1,
	},
	hgn_ms_module_hyperspaceinhibitor =
	{
		HGN_MS_MODULE_HYPERSPACEINHIBITOR_RCH0,
		HGN_MS_MODULE_HYPERSPACEINHIBITOR_RCH1,
	},
	hgn_ms_module_research =
	{
		HGN_MS_MODULE_RESEARCH,
	},
	hgn_ms_module_researchadvanced =
	{
		HGN_MS_MODULE_RESEARCHADVANCED,
	},
	hgn_ms_sensors_advancedarray =
	{
		HGN_MS_SENSORS_ADVANCEDARRAY,
	},
	hgn_ms_sensors_detectcloaked =
	{
		HGN_MS_SENSORS_DETECTCLOAKED,
	},
	hgn_ms_sensors_detecthyperspace =
	{
		HGN_MS_SENSORS_DETECTHYPERSPACE,
	},
	hgn_gunturret =
	{
		HGN_GUNTURRET_HYP0,
		HGN_GUNTURRET_HYP1,
	},
	hgn_ionturret =
	{
		HGN_IONTURRET_HYP0,
		HGN_IONTURRET_HYP1,
	},
	hgn_c_module_platformcontrol =
	{
		HGN_C_MODULE_PLATFORMCONTROL,
	},
	hgn_c_production_corvette =
	{
		HGN_C_PRODUCTION_CORVETTE_RCH0,
		HGN_C_PRODUCTION_CORVETTE_RCH1,
	},
	hgn_c_production_fighter =
	{
		HGN_C_PRODUCTION_FIGHTER,
	},
	hgn_c_production_frigate =
	{
		HGN_C_PRODUCTION_FRIGATE_RCH0,
		HGN_C_PRODUCTION_FRIGATE_RCH1,
	},
	hgn_ms_module_platformcontrol =
	{
		HGN_MS_MODULE_PLATFORMCONTROL,
	},
	hgn_ms_production_capship =
	{
		HGN_MS_PRODUCTION_CAPSHIP,
	},
	hgn_ms_production_corvette =
	{
		HGN_MS_PRODUCTION_CORVETTE_RCH0,
		HGN_MS_PRODUCTION_CORVETTE_RCH1,
	},
	hgn_ms_production_fighter =
	{
		HGN_MS_PRODUCTION_FIGHTER,
	},
	hgn_ms_production_frigate =
	{
		HGN_MS_PRODUCTION_FRIGATE_RCH0,
		HGN_MS_PRODUCTION_FRIGATE_RCH1,
	},
	hgn_sy_production_capship =
	{
		HGN_SY_PRODUCTION_CAPSHIP,
	},
	hgn_shipyard_elohim =
	{
		HGN_SHIPYARD_ELOHIM_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARD_ELOHIM_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARD_ELOHIM_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARD_ELOHIM_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARD_ELOHIM_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARD_ELOHIM_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARD_ELOHIM_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARD_ELOHIM_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARD_ELOHIM_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARD_ELOHIM_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARD_ELOHIM_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARD_ELOHIM_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARD_ELOHIM_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARD_ELOHIM_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARD_ELOHIM_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARD_ELOHIM_CAR1_RCH1_RES1_HYP1,
	},
	hgn_shipyard_spg =
	{
		HGN_SHIPYARD_SPG_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARD_SPG_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARD_SPG_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARD_SPG_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARD_SPG_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARD_SPG_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARD_SPG_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARD_SPG_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARD_SPG_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARD_SPG_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARD_SPG_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARD_SPG_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARD_SPG_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARD_SPG_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARD_SPG_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARD_SPG_CAR1_RCH1_RES1_HYP1,
	},
	kpr_mover =
	{
		KPR_MOVER_HYP0,
		KPR_MOVER_HYP1,
	},
	hgn_ms_production_corvettemover =
	{
		HGN_MS_PRODUCTION_CORVETTEMOVER,
	},
	hgn_ecmprobe =
	{
		HGN_ECMPROBE_HYP0,
		HGN_ECMPROBE_HYP1,
	},
	hgn_probe =
	{
		HGN_PROBE_HYP0,
		HGN_PROBE_HYP1,
	},
	hgn_proximitysensor =
	{
		HGN_PROXIMITYSENSOR_HYP0,
		HGN_PROXIMITYSENSOR_HYP1,
	},
	hgn_resourcecollector =
	{
		HGN_RESOURCECOLLECTOR_RES0_HYP0,
		HGN_RESOURCECOLLECTOR_RES1_HYP0,
		HGN_RESOURCECOLLECTOR_RES0_HYP1,
		HGN_RESOURCECOLLECTOR_RES1_HYP1,
	},
	hgn_resourcecontroller =
	{
		HGN_RESOURCECONTROLLER_RES0_HYP0,
		HGN_RESOURCECONTROLLER_RES1_HYP0,
		HGN_RESOURCECONTROLLER_RES0_HYP1,
		HGN_RESOURCECONTROLLER_RES1_HYP1,
	},
}
