VariantResearch =
{
	hgn_attackbomberimprovedbombs =
	{
		HGN_ATTACKBOMBERIMPROVEDBOMBS_HYP0,
		HGN_ATTACKBOMBERIMPROVEDBOMBS_HYP1,
	},
	hgn_defensefieldfrigateshield =
	{
		HGN_DEFENSEFIELDFRIGATESHIELD_HYP0,
		HGN_DEFENSEFIELDFRIGATESHIELD_HYP1,
	},
	hgn_improvedtorpedo =
	{
		HGN_IMPROVEDTORPEDO_HYP0,
		HGN_IMPROVEDTORPEDO_HYP1,
	},
	hgn_repairability =
	{
		HGN_REPAIRABILITY_RES0_HYP0,
		HGN_REPAIRABILITY_RES1_HYP0,
		HGN_REPAIRABILITY_RES0_HYP1,
		HGN_REPAIRABILITY_RES1_HYP1,
	},
	hgn_scoutempability =
	{
		HGN_SCOUTEMPABILITY_HYP0,
		HGN_SCOUTEMPABILITY_HYP1,
	},
	hgn_scoutpingability =
	{
		HGN_SCOUTPINGABILITY_HYP0,
		HGN_SCOUTPINGABILITY_HYP1,
	},
	hgn_allshipbuildspeed =
	{
		HGN_ALLSHIPBUILDSPEED,
	},
	hgn_allshipbuildspeedexpert =
	{
		HGN_ALLSHIPBUILDSPEEDEXPERT,
	},
	hgn_allshipbuildspeedhard =
	{
		HGN_ALLSHIPBUILDSPEEDHARD,
	},
	hgn_cpuplayers_aggressive =
	{
		HGN_CPUPLAYERS_AGGRESSIVE,
	},
	hgn_cpuplayers_defensive =
	{
		HGN_CPUPLAYERS_DEFENSIVE,
	},
	hgn_cpuplayers_dynamic =
	{
		HGN_CPUPLAYERS_DYNAMIC,
	},
	hgn_cpuplayers_norushtime10 =
	{
		HGN_CPUPLAYERS_NORUSHTIME10,
	},
	hgn_cpuplayers_norushtime15 =
	{
		HGN_CPUPLAYERS_NORUSHTIME15,
	},
	hgn_cpuplayers_norushtime5 =
	{
		HGN_CPUPLAYERS_NORUSHTIME5,
	},
	hgn_resourcecollectionrateexpert =
	{
		HGN_RESOURCECOLLECTIONRATEEXPERT_RES0_HYP0,
		HGN_RESOURCECOLLECTIONRATEEXPERT_RES1_HYP0,
		HGN_RESOURCECOLLECTIONRATEEXPERT_RES0_HYP1,
		HGN_RESOURCECOLLECTIONRATEEXPERT_RES1_HYP1,
	},
	hgn_resourcecollectionratehard =
	{
		HGN_RESOURCECOLLECTIONRATEHARD_RES0_HYP0,
		HGN_RESOURCECOLLECTIONRATEHARD_RES1_HYP0,
		HGN_RESOURCECOLLECTIONRATEHARD_RES0_HYP1,
		HGN_RESOURCECOLLECTIONRATEHARD_RES1_HYP1,
	},
	hgn_weapondamageupgrade125 =
	{
		HGN_WEAPONDAMAGEUPGRADE125,
	},
	hgn_weapondamageupgrade150 =
	{
		HGN_WEAPONDAMAGEUPGRADE150,
	},
	hgn_weapondamageupgrade175 =
	{
		HGN_WEAPONDAMAGEUPGRADE175,
	},
	hgn_weapondamageupgrade200 =
	{
		HGN_WEAPONDAMAGEUPGRADE200,
	},
	hgn_battlecruiserhealthupgrade1 =
	{
		HGN_BATTLECRUISERHEALTHUPGRADE1_HYP0,
		HGN_BATTLECRUISERHEALTHUPGRADE1_HYP1,
	},
	hgn_battlecruisermaxspeedupgrade1 =
	{
		HGN_BATTLECRUISERMAXSPEEDUPGRADE1_HYP0,
		HGN_BATTLECRUISERMAXSPEEDUPGRADE1_HYP1,
	},
	hgn_carrierbuildspeedupgrade1 =
	{
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP0,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP0,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP0,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP0,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP1,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP1,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP1,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP1,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP0,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP0,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP0,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP0,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP1,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP1,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP1,
		HGN_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	hgn_carrierhealthupgrade1 =
	{
		HGN_CARRIERHEALTHUPGRADE1_CAR0_RCH0_RES0_HYP0,
		HGN_CARRIERHEALTHUPGRADE1_CAR1_RCH0_RES0_HYP0,
		HGN_CARRIERHEALTHUPGRADE1_CAR0_RCH0_RES1_HYP0,
		HGN_CARRIERHEALTHUPGRADE1_CAR1_RCH0_RES1_HYP0,
		HGN_CARRIERHEALTHUPGRADE1_CAR0_RCH0_RES0_HYP1,
		HGN_CARRIERHEALTHUPGRADE1_CAR1_RCH0_RES0_HYP1,
		HGN_CARRIERHEALTHUPGRADE1_CAR0_RCH0_RES1_HYP1,
		HGN_CARRIERHEALTHUPGRADE1_CAR1_RCH0_RES1_HYP1,
		HGN_CARRIERHEALTHUPGRADE1_CAR0_RCH1_RES0_HYP0,
		HGN_CARRIERHEALTHUPGRADE1_CAR1_RCH1_RES0_HYP0,
		HGN_CARRIERHEALTHUPGRADE1_CAR0_RCH1_RES1_HYP0,
		HGN_CARRIERHEALTHUPGRADE1_CAR1_RCH1_RES1_HYP0,
		HGN_CARRIERHEALTHUPGRADE1_CAR0_RCH1_RES0_HYP1,
		HGN_CARRIERHEALTHUPGRADE1_CAR1_RCH1_RES0_HYP1,
		HGN_CARRIERHEALTHUPGRADE1_CAR0_RCH1_RES1_HYP1,
		HGN_CARRIERHEALTHUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	hgn_carriermaxspeedupgrade1 =
	{
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP0,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP0,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP0,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP0,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP1,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP1,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP1,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP1,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP0,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP0,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP0,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP0,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP1,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP1,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP1,
		HGN_CARRIERMAXSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	hgn_assaultcorvettehealthupgrade1 =
	{
		HGN_ASSAULTCORVETTEHEALTHUPGRADE1_HYP0,
		HGN_ASSAULTCORVETTEHEALTHUPGRADE1_HYP1,
	},
	hgn_pulsarcorvettehealthupgrade1 =
	{
		HGN_PULSARCORVETTEHEALTHUPGRADE1_HYP0,
		HGN_PULSARCORVETTEHEALTHUPGRADE1_HYP1,
	},
	hgn_assaultcorvettemaxspeedupgrade1 =
	{
		HGN_ASSAULTCORVETTEMAXSPEEDUPGRADE1_HYP0,
		HGN_ASSAULTCORVETTEMAXSPEEDUPGRADE1_HYP1,
	},
	hgn_pulsarcorvettemaxspeedupgrade1 =
	{
		HGN_PULSARCORVETTEMAXSPEEDUPGRADE1_HYP0,
		HGN_PULSARCORVETTEMAXSPEEDUPGRADE1_HYP1,
	},
	hgn_battlecruiserionweapons =
	{
		HGN_BATTLECRUISERIONWEAPONS_HYP0,
		HGN_BATTLECRUISERIONWEAPONS_HYP1,
	},
	hgn_destroyertech =
	{
		HGN_DESTROYERTECH_HYP0,
		HGN_DESTROYERTECH_HYP1,
	},
	hgn_ecmprobe =
	{
		HGN_ECMPROBE_HYP0,
		HGN_ECMPROBE_HYP1,
	},
	hgn_graviticattractionmines =
	{
		HGN_GRAVITICATTRACTIONMINES_HYP0,
		HGN_GRAVITICATTRACTIONMINES_HYP1,
	},
	hgn_hyperspacedamagereductionupgrade =
	{
		HGN_HYPERSPACEDAMAGEREDUCTIONUPGRADE,
	},
	hgn_instaadvancedfrigatetech =
	{
		HGN_INSTAADVANCEDFRIGATETECH_CAR0_RCH0_RES0_HYP0,
		HGN_INSTAADVANCEDFRIGATETECH_CAR1_RCH0_RES0_HYP0,
		HGN_INSTAADVANCEDFRIGATETECH_CAR0_RCH0_RES1_HYP0,
		HGN_INSTAADVANCEDFRIGATETECH_CAR1_RCH0_RES1_HYP0,
		HGN_INSTAADVANCEDFRIGATETECH_CAR0_RCH0_RES0_HYP1,
		HGN_INSTAADVANCEDFRIGATETECH_CAR1_RCH0_RES0_HYP1,
		HGN_INSTAADVANCEDFRIGATETECH_CAR0_RCH0_RES1_HYP1,
		HGN_INSTAADVANCEDFRIGATETECH_CAR1_RCH0_RES1_HYP1,
		HGN_INSTAADVANCEDFRIGATETECH_CAR0_RCH1_RES0_HYP0,
		HGN_INSTAADVANCEDFRIGATETECH_CAR1_RCH1_RES0_HYP0,
		HGN_INSTAADVANCEDFRIGATETECH_CAR0_RCH1_RES1_HYP0,
		HGN_INSTAADVANCEDFRIGATETECH_CAR1_RCH1_RES1_HYP0,
		HGN_INSTAADVANCEDFRIGATETECH_CAR0_RCH1_RES0_HYP1,
		HGN_INSTAADVANCEDFRIGATETECH_CAR1_RCH1_RES0_HYP1,
		HGN_INSTAADVANCEDFRIGATETECH_CAR0_RCH1_RES1_HYP1,
		HGN_INSTAADVANCEDFRIGATETECH_CAR1_RCH1_RES1_HYP1,
	},
	hgn_platformionweapons =
	{
		HGN_PLATFORMIONWEAPONS_HYP0,
		HGN_PLATFORMIONWEAPONS_HYP1,
	},
	hgn_sensdisprobe =
	{
		HGN_SENSDISPROBE_HYP0,
		HGN_SENSDISPROBE_HYP1,
	},
	hgn_destroyerhealthupgrade1 =
	{
		HGN_DESTROYERHEALTHUPGRADE1_HYP0,
		HGN_DESTROYERHEALTHUPGRADE1_HYP1,
	},
	hgn_destroyermaxspeedupgrade1 =
	{
		HGN_DESTROYERMAXSPEEDUPGRADE1_HYP0,
		HGN_DESTROYERMAXSPEEDUPGRADE1_HYP1,
	},
	hgn_sgmcapitalhealth =
	{
		HGN_SGMCAPITALHEALTH_CAR0_RCH0_RES0_HYP0,
		HGN_SGMCAPITALHEALTH_CAR1_RCH0_RES0_HYP0,
		HGN_SGMCAPITALHEALTH_CAR0_RCH0_RES1_HYP0,
		HGN_SGMCAPITALHEALTH_CAR1_RCH0_RES1_HYP0,
		HGN_SGMCAPITALHEALTH_CAR0_RCH0_RES0_HYP1,
		HGN_SGMCAPITALHEALTH_CAR1_RCH0_RES0_HYP1,
		HGN_SGMCAPITALHEALTH_CAR0_RCH0_RES1_HYP1,
		HGN_SGMCAPITALHEALTH_CAR1_RCH0_RES1_HYP1,
		HGN_SGMCAPITALHEALTH_CAR0_RCH1_RES0_HYP0,
		HGN_SGMCAPITALHEALTH_CAR1_RCH1_RES0_HYP0,
		HGN_SGMCAPITALHEALTH_CAR0_RCH1_RES1_HYP0,
		HGN_SGMCAPITALHEALTH_CAR1_RCH1_RES1_HYP0,
		HGN_SGMCAPITALHEALTH_CAR0_RCH1_RES0_HYP1,
		HGN_SGMCAPITALHEALTH_CAR1_RCH1_RES0_HYP1,
		HGN_SGMCAPITALHEALTH_CAR0_RCH1_RES1_HYP1,
		HGN_SGMCAPITALHEALTH_CAR1_RCH1_RES1_HYP1,
	},
	hgn_sgmcarrierhealth =
	{
		HGN_SGMCARRIERHEALTH_CAR0_RCH0_RES0_HYP0,
		HGN_SGMCARRIERHEALTH_CAR1_RCH0_RES0_HYP0,
		HGN_SGMCARRIERHEALTH_CAR0_RCH0_RES1_HYP0,
		HGN_SGMCARRIERHEALTH_CAR1_RCH0_RES1_HYP0,
		HGN_SGMCARRIERHEALTH_CAR0_RCH0_RES0_HYP1,
		HGN_SGMCARRIERHEALTH_CAR1_RCH0_RES0_HYP1,
		HGN_SGMCARRIERHEALTH_CAR0_RCH0_RES1_HYP1,
		HGN_SGMCARRIERHEALTH_CAR1_RCH0_RES1_HYP1,
		HGN_SGMCARRIERHEALTH_CAR0_RCH1_RES0_HYP0,
		HGN_SGMCARRIERHEALTH_CAR1_RCH1_RES0_HYP0,
		HGN_SGMCARRIERHEALTH_CAR0_RCH1_RES1_HYP0,
		HGN_SGMCARRIERHEALTH_CAR1_RCH1_RES1_HYP0,
		HGN_SGMCARRIERHEALTH_CAR0_RCH1_RES0_HYP1,
		HGN_SGMCARRIERHEALTH_CAR1_RCH1_RES0_HYP1,
		HGN_SGMCARRIERHEALTH_CAR0_RCH1_RES1_HYP1,
		HGN_SGMCARRIERHEALTH_CAR1_RCH1_RES1_HYP1,
	},
	hgn_sgmfrigatehealth =
	{
		HGN_SGMFRIGATEHEALTH,
	},
	hgn_sgmshipyardhealth =
	{
		HGN_SGMSHIPYARDHEALTH_CAR0_RCH0_RES0_HYP0,
		HGN_SGMSHIPYARDHEALTH_CAR1_RCH0_RES0_HYP0,
		HGN_SGMSHIPYARDHEALTH_CAR0_RCH0_RES1_HYP0,
		HGN_SGMSHIPYARDHEALTH_CAR1_RCH0_RES1_HYP0,
		HGN_SGMSHIPYARDHEALTH_CAR0_RCH0_RES0_HYP1,
		HGN_SGMSHIPYARDHEALTH_CAR1_RCH0_RES0_HYP1,
		HGN_SGMSHIPYARDHEALTH_CAR0_RCH0_RES1_HYP1,
		HGN_SGMSHIPYARDHEALTH_CAR1_RCH0_RES1_HYP1,
		HGN_SGMSHIPYARDHEALTH_CAR0_RCH1_RES0_HYP0,
		HGN_SGMSHIPYARDHEALTH_CAR1_RCH1_RES0_HYP0,
		HGN_SGMSHIPYARDHEALTH_CAR0_RCH1_RES1_HYP0,
		HGN_SGMSHIPYARDHEALTH_CAR1_RCH1_RES1_HYP0,
		HGN_SGMSHIPYARDHEALTH_CAR0_RCH1_RES0_HYP1,
		HGN_SGMSHIPYARDHEALTH_CAR1_RCH1_RES0_HYP1,
		HGN_SGMSHIPYARDHEALTH_CAR0_RCH1_RES1_HYP1,
		HGN_SGMSHIPYARDHEALTH_CAR1_RCH1_RES1_HYP1,
	},
	hgn_attackbombermaxspeedupgrade1 =
	{
		HGN_ATTACKBOMBERMAXSPEEDUPGRADE1_HYP0,
		HGN_ATTACKBOMBERMAXSPEEDUPGRADE1_HYP1,
	},
	hgn_interceptormaxspeedupgrade1 =
	{
		HGN_INTERCEPTORMAXSPEEDUPGRADE1_HYP0,
		HGN_INTERCEPTORMAXSPEEDUPGRADE1_HYP1,
	},
	hgn_assaultfrigatehealthupgrade1 =
	{
		HGN_ASSAULTFRIGATEHEALTHUPGRADE1_HYP0,
		HGN_ASSAULTFRIGATEHEALTHUPGRADE1_HYP1,
	},
	hgn_ioncannonfrigatehealthupgrade1 =
	{
		HGN_IONCANNONFRIGATEHEALTHUPGRADE1_HYP0,
		HGN_IONCANNONFRIGATEHEALTHUPGRADE1_HYP1,
	},
	hgn_torpedofrigatehealthupgrade1 =
	{
		HGN_TORPEDOFRIGATEHEALTHUPGRADE1_HYP0,
		HGN_TORPEDOFRIGATEHEALTHUPGRADE1_HYP1,
	},
	hgn_assaultfrigatemaxspeedupgrade1 =
	{
		HGN_ASSAULTFRIGATEMAXSPEEDUPGRADE1_HYP0,
		HGN_ASSAULTFRIGATEMAXSPEEDUPGRADE1_HYP1,
	},
	hgn_ioncannonfrigatemaxspeedupgrade1 =
	{
		HGN_IONCANNONFRIGATEMAXSPEEDUPGRADE1_HYP0,
		HGN_IONCANNONFRIGATEMAXSPEEDUPGRADE1_HYP1,
	},
	hgn_torpedofrigatemaxspeedupgrade1 =
	{
		HGN_TORPEDOFRIGATEMAXSPEEDUPGRADE1_HYP0,
		HGN_TORPEDOFRIGATEMAXSPEEDUPGRADE1_HYP1,
	},
	hgn_hyperspacecostupgrade1 =
	{
		HGN_HYPERSPACECOSTUPGRADE1,
	},
	hgn_hyperspacecostupgrade2 =
	{
		HGN_HYPERSPACECOSTUPGRADE2,
	},
	hgn_mothershipbuildspeedupgrade1 =
	{
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP0,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP0,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP0,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP0,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP1,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP1,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP1,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP1,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP0,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP0,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP0,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP0,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP1,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP1,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP1,
		HGN_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	hgn_mothershiphealthupgrade1 =
	{
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR0_RCH0_RES0_HYP0,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR1_RCH0_RES0_HYP0,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR0_RCH0_RES1_HYP0,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR1_RCH0_RES1_HYP0,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR0_RCH0_RES0_HYP1,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR1_RCH0_RES0_HYP1,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR0_RCH0_RES1_HYP1,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR1_RCH0_RES1_HYP1,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR0_RCH1_RES0_HYP0,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR1_RCH1_RES0_HYP0,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR0_RCH1_RES1_HYP0,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR1_RCH1_RES1_HYP0,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR0_RCH1_RES0_HYP1,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR1_RCH1_RES0_HYP1,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR0_RCH1_RES1_HYP1,
		HGN_MOTHERSHIPHEALTHUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	hgn_mothershipmaxspeedupgrade1 =
	{
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP0,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP0,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP0,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP0,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP1,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP1,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP1,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP1,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP0,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP0,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP0,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP0,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP1,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP1,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP1,
		HGN_MOTHERSHIPMAXSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	hgn_gunturrethealthupgrade1 =
	{
		HGN_GUNTURRETHEALTHUPGRADE1_HYP0,
		HGN_GUNTURRETHEALTHUPGRADE1_HYP1,
	},
	hgn_ionturrethealthupgrade1 =
	{
		HGN_IONTURRETHEALTHUPGRADE1_HYP0,
		HGN_IONTURRETHEALTHUPGRADE1_HYP1,
	},
	hgn_shipyardbuildspeedupgrade1 =
	{
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	hgn_shipyardbuildspeedupgrade1_elohim =
	{
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_ELOHIM_CAR1_RCH1_RES1_HYP1,
	},
	hgn_shipyardbuildspeedupgrade1_spg =
	{
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARDBUILDSPEEDUPGRADE1_SPG_CAR1_RCH1_RES1_HYP1,
	},
	hgn_shipyardhealthupgrade1 =
	{
		HGN_SHIPYARDHEALTHUPGRADE1_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	hgn_shipyardhealthupgrade1_elohim =
	{
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_ELOHIM_CAR1_RCH1_RES1_HYP1,
	},
	hgn_shipyardhealthupgrade1_spg =
	{
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARDHEALTHUPGRADE1_SPG_CAR1_RCH1_RES1_HYP1,
	},
	hgn_shipyardmaxspeedupgrade1 =
	{
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	hgn_shipyardmaxspeedupgrade1_elohim =
	{
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_ELOHIM_CAR1_RCH1_RES1_HYP1,
	},
	hgn_shipyardmaxspeedupgrade1_spg =
	{
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR0_RCH0_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR1_RCH0_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR0_RCH0_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR1_RCH0_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR0_RCH0_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR1_RCH0_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR0_RCH0_RES1_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR1_RCH0_RES1_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR0_RCH1_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR1_RCH1_RES0_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR0_RCH1_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR1_RCH1_RES1_HYP0,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR0_RCH1_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR1_RCH1_RES0_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR0_RCH1_RES1_HYP1,
		HGN_SHIPYARDMAXSPEEDUPGRADE1_SPG_CAR1_RCH1_RES1_HYP1,
	},
	hgn_assaultcorvetteeliteweaponupgrade =
	{
		HGN_ASSAULTCORVETTEELITEWEAPONUPGRADE_HYP0,
		HGN_ASSAULTCORVETTEELITEWEAPONUPGRADE_HYP1,
	},
	hgn_attackbombereliteweaponupgrade =
	{
		HGN_ATTACKBOMBERELITEWEAPONUPGRADE_HYP0,
		HGN_ATTACKBOMBERELITEWEAPONUPGRADE_HYP1,
	},
	hgn_attackdroidhealthupgradespgame_high =
	{
		HGN_ATTACKDROIDHEALTHUPGRADESPGAME_HIGH_HYP0,
		HGN_ATTACKDROIDHEALTHUPGRADESPGAME_HIGH_HYP1,
	},
	hgn_attackdroidhealthupgradespgame_low =
	{
		HGN_ATTACKDROIDHEALTHUPGRADESPGAME_LOW_HYP0,
		HGN_ATTACKDROIDHEALTHUPGRADESPGAME_LOW_HYP1,
	},
	hgn_attackdroidhealthupgradespgame_med =
	{
		HGN_ATTACKDROIDHEALTHUPGRADESPGAME_MED_HYP0,
		HGN_ATTACKDROIDHEALTHUPGRADESPGAME_MED_HYP1,
	},
	hgn_attackdroidweaponupgradespgame_high =
	{
		HGN_ATTACKDROIDWEAPONUPGRADESPGAME_HIGH_HYP0,
		HGN_ATTACKDROIDWEAPONUPGRADESPGAME_HIGH_HYP1,
	},
	hgn_attackdroidweaponupgradespgame_low =
	{
		HGN_ATTACKDROIDWEAPONUPGRADESPGAME_LOW_HYP0,
		HGN_ATTACKDROIDWEAPONUPGRADESPGAME_LOW_HYP1,
	},
	hgn_attackdroidweaponupgradespgame_med =
	{
		HGN_ATTACKDROIDWEAPONUPGRADESPGAME_MED_HYP0,
		HGN_ATTACKDROIDWEAPONUPGRADESPGAME_MED_HYP1,
	},
	hgn_damagemovertech =
	{
		HGN_DAMAGEMOVERTECH_CAR0_RCH0_RES0_HYP0,
		HGN_DAMAGEMOVERTECH_CAR1_RCH0_RES0_HYP0,
		HGN_DAMAGEMOVERTECH_CAR0_RCH0_RES1_HYP0,
		HGN_DAMAGEMOVERTECH_CAR1_RCH0_RES1_HYP0,
		HGN_DAMAGEMOVERTECH_CAR0_RCH0_RES0_HYP1,
		HGN_DAMAGEMOVERTECH_CAR1_RCH0_RES0_HYP1,
		HGN_DAMAGEMOVERTECH_CAR0_RCH0_RES1_HYP1,
		HGN_DAMAGEMOVERTECH_CAR1_RCH0_RES1_HYP1,
		HGN_DAMAGEMOVERTECH_CAR0_RCH1_RES0_HYP0,
		HGN_DAMAGEMOVERTECH_CAR1_RCH1_RES0_HYP0,
		HGN_DAMAGEMOVERTECH_CAR0_RCH1_RES1_HYP0,
		HGN_DAMAGEMOVERTECH_CAR1_RCH1_RES1_HYP0,
		HGN_DAMAGEMOVERTECH_CAR0_RCH1_RES0_HYP1,
		HGN_DAMAGEMOVERTECH_CAR1_RCH1_RES0_HYP1,
		HGN_DAMAGEMOVERTECH_CAR0_RCH1_RES1_HYP1,
		HGN_DAMAGEMOVERTECH_CAR1_RCH1_RES1_HYP1,
	},
	hgn_frigatehealthupgradespgame =
	{
		HGN_FRIGATEHEALTHUPGRADESPGAME,
	},
	hgn_keeperhealthupgradespgame_high =
	{
		HGN_KEEPERHEALTHUPGRADESPGAME_HIGH_HYP0,
		HGN_KEEPERHEALTHUPGRADESPGAME_HIGH_HYP1,
	},
	hgn_keeperhealthupgradespgame_low =
	{
		HGN_KEEPERHEALTHUPGRADESPGAME_LOW_HYP0,
		HGN_KEEPERHEALTHUPGRADESPGAME_LOW_HYP1,
	},
	hgn_keeperhealthupgradespgame_m10_lvl_1 =
	{
		HGN_KEEPERHEALTHUPGRADESPGAME_M10_LVL_1_HYP0,
		HGN_KEEPERHEALTHUPGRADESPGAME_M10_LVL_1_HYP1,
	},
	hgn_keeperhealthupgradespgame_m10_lvl_2 =
	{
		HGN_KEEPERHEALTHUPGRADESPGAME_M10_LVL_2_HYP0,
		HGN_KEEPERHEALTHUPGRADESPGAME_M10_LVL_2_HYP1,
	},
	hgn_keeperhealthupgradespgame_m10_lvl_3 =
	{
		HGN_KEEPERHEALTHUPGRADESPGAME_M10_LVL_3_HYP0,
		HGN_KEEPERHEALTHUPGRADESPGAME_M10_LVL_3_HYP1,
	},
	hgn_keeperhealthupgradespgame_med =
	{
		HGN_KEEPERHEALTHUPGRADESPGAME_MED_HYP0,
		HGN_KEEPERHEALTHUPGRADESPGAME_MED_HYP1,
	},
	hgn_keeperweaponupgradespgame_m10_lvl_1 =
	{
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_1_HYP0,
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_1_HYP1,
	},
	hgn_keeperweaponupgradespgame_m10_lvl_2 =
	{
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_2_HYP0,
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_2_HYP1,
	},
	hgn_keeperweaponupgradespgame_m10_lvl_3 =
	{
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_3_HYP0,
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_3_HYP1,
	},
	hgn_keeperweaponupgradespgame_m10_lvl_4 =
	{
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_4_HYP0,
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_4_HYP1,
	},
	hgn_keeperweaponupgradespgame_m10_lvl_5 =
	{
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_5_HYP0,
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_5_HYP1,
	},
	hgn_keeperweaponupgradespgame_m10_lvl_6 =
	{
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_6_HYP0,
		HGN_KEEPERWEAPONUPGRADESPGAME_M10_LVL_6_HYP1,
	},
	hgn_moverhealthdowngrade =
	{
		HGN_MOVERHEALTHDOWNGRADE_HYP0,
		HGN_MOVERHEALTHDOWNGRADE_HYP1,
	},
	hgn_moverhealthupgrade =
	{
		HGN_MOVERHEALTHUPGRADE_HYP0,
		HGN_MOVERHEALTHUPGRADE_HYP1,
	},
	hgn_radiationdefensefield =
	{
		HGN_RADIATIONDEFENSEFIELD_HYP0,
		HGN_RADIATIONDEFENSEFIELD_HYP1,
	},
	hgn_sensorsbacktonormal1 =
	{
		HGN_SENSORSBACKTONORMAL1_CAR0_RCH0_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL1_CAR1_RCH0_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL1_CAR0_RCH0_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL1_CAR1_RCH0_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL1_CAR0_RCH0_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL1_CAR1_RCH0_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL1_CAR0_RCH0_RES1_HYP1,
		HGN_SENSORSBACKTONORMAL1_CAR1_RCH0_RES1_HYP1,
		HGN_SENSORSBACKTONORMAL1_CAR0_RCH1_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL1_CAR1_RCH1_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL1_CAR0_RCH1_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL1_CAR1_RCH1_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL1_CAR0_RCH1_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL1_CAR1_RCH1_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL1_CAR0_RCH1_RES1_HYP1,
		HGN_SENSORSBACKTONORMAL1_CAR1_RCH1_RES1_HYP1,
	},
	hgn_sensorsbacktonormal2 =
	{
		HGN_SENSORSBACKTONORMAL2_CAR0_RCH0_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL2_CAR1_RCH0_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL2_CAR0_RCH0_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL2_CAR1_RCH0_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL2_CAR0_RCH0_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL2_CAR1_RCH0_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL2_CAR0_RCH0_RES1_HYP1,
		HGN_SENSORSBACKTONORMAL2_CAR1_RCH0_RES1_HYP1,
		HGN_SENSORSBACKTONORMAL2_CAR0_RCH1_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL2_CAR1_RCH1_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL2_CAR0_RCH1_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL2_CAR1_RCH1_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL2_CAR0_RCH1_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL2_CAR1_RCH1_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL2_CAR0_RCH1_RES1_HYP1,
		HGN_SENSORSBACKTONORMAL2_CAR1_RCH1_RES1_HYP1,
	},
	hgn_sensorsbacktonormal3 =
	{
		HGN_SENSORSBACKTONORMAL3_CAR0_RCH0_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL3_CAR1_RCH0_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL3_CAR0_RCH0_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL3_CAR1_RCH0_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL3_CAR0_RCH0_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL3_CAR1_RCH0_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL3_CAR0_RCH0_RES1_HYP1,
		HGN_SENSORSBACKTONORMAL3_CAR1_RCH0_RES1_HYP1,
		HGN_SENSORSBACKTONORMAL3_CAR0_RCH1_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL3_CAR1_RCH1_RES0_HYP0,
		HGN_SENSORSBACKTONORMAL3_CAR0_RCH1_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL3_CAR1_RCH1_RES1_HYP0,
		HGN_SENSORSBACKTONORMAL3_CAR0_RCH1_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL3_CAR1_RCH1_RES0_HYP1,
		HGN_SENSORSBACKTONORMAL3_CAR0_RCH1_RES1_HYP1,
		HGN_SENSORSBACKTONORMAL3_CAR1_RCH1_RES1_HYP1,
	},
	hgn_sensorsdowngrade1 =
	{
		HGN_SENSORSDOWNGRADE1_CAR0_RCH0_RES0_HYP0,
		HGN_SENSORSDOWNGRADE1_CAR1_RCH0_RES0_HYP0,
		HGN_SENSORSDOWNGRADE1_CAR0_RCH0_RES1_HYP0,
		HGN_SENSORSDOWNGRADE1_CAR1_RCH0_RES1_HYP0,
		HGN_SENSORSDOWNGRADE1_CAR0_RCH0_RES0_HYP1,
		HGN_SENSORSDOWNGRADE1_CAR1_RCH0_RES0_HYP1,
		HGN_SENSORSDOWNGRADE1_CAR0_RCH0_RES1_HYP1,
		HGN_SENSORSDOWNGRADE1_CAR1_RCH0_RES1_HYP1,
		HGN_SENSORSDOWNGRADE1_CAR0_RCH1_RES0_HYP0,
		HGN_SENSORSDOWNGRADE1_CAR1_RCH1_RES0_HYP0,
		HGN_SENSORSDOWNGRADE1_CAR0_RCH1_RES1_HYP0,
		HGN_SENSORSDOWNGRADE1_CAR1_RCH1_RES1_HYP0,
		HGN_SENSORSDOWNGRADE1_CAR0_RCH1_RES0_HYP1,
		HGN_SENSORSDOWNGRADE1_CAR1_RCH1_RES0_HYP1,
		HGN_SENSORSDOWNGRADE1_CAR0_RCH1_RES1_HYP1,
		HGN_SENSORSDOWNGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	hgn_sensorsdowngrade2 =
	{
		HGN_SENSORSDOWNGRADE2_CAR0_RCH0_RES0_HYP0,
		HGN_SENSORSDOWNGRADE2_CAR1_RCH0_RES0_HYP0,
		HGN_SENSORSDOWNGRADE2_CAR0_RCH0_RES1_HYP0,
		HGN_SENSORSDOWNGRADE2_CAR1_RCH0_RES1_HYP0,
		HGN_SENSORSDOWNGRADE2_CAR0_RCH0_RES0_HYP1,
		HGN_SENSORSDOWNGRADE2_CAR1_RCH0_RES0_HYP1,
		HGN_SENSORSDOWNGRADE2_CAR0_RCH0_RES1_HYP1,
		HGN_SENSORSDOWNGRADE2_CAR1_RCH0_RES1_HYP1,
		HGN_SENSORSDOWNGRADE2_CAR0_RCH1_RES0_HYP0,
		HGN_SENSORSDOWNGRADE2_CAR1_RCH1_RES0_HYP0,
		HGN_SENSORSDOWNGRADE2_CAR0_RCH1_RES1_HYP0,
		HGN_SENSORSDOWNGRADE2_CAR1_RCH1_RES1_HYP0,
		HGN_SENSORSDOWNGRADE2_CAR0_RCH1_RES0_HYP1,
		HGN_SENSORSDOWNGRADE2_CAR1_RCH1_RES0_HYP1,
		HGN_SENSORSDOWNGRADE2_CAR0_RCH1_RES1_HYP1,
		HGN_SENSORSDOWNGRADE2_CAR1_RCH1_RES1_HYP1,
	},
	hgn_sensorsdowngrade3 =
	{
		HGN_SENSORSDOWNGRADE3_CAR0_RCH0_RES0_HYP0,
		HGN_SENSORSDOWNGRADE3_CAR1_RCH0_RES0_HYP0,
		HGN_SENSORSDOWNGRADE3_CAR0_RCH0_RES1_HYP0,
		HGN_SENSORSDOWNGRADE3_CAR1_RCH0_RES1_HYP0,
		HGN_SENSORSDOWNGRADE3_CAR0_RCH0_RES0_HYP1,
		HGN_SENSORSDOWNGRADE3_CAR1_RCH0_RES0_HYP1,
		HGN_SENSORSDOWNGRADE3_CAR0_RCH0_RES1_HYP1,
		HGN_SENSORSDOWNGRADE3_CAR1_RCH0_RES1_HYP1,
		HGN_SENSORSDOWNGRADE3_CAR0_RCH1_RES0_HYP0,
		HGN_SENSORSDOWNGRADE3_CAR1_RCH1_RES0_HYP0,
		HGN_SENSORSDOWNGRADE3_CAR0_RCH1_RES1_HYP0,
		HGN_SENSORSDOWNGRADE3_CAR1_RCH1_RES1_HYP0,
		HGN_SENSORSDOWNGRADE3_CAR0_RCH1_RES0_HYP1,
		HGN_SENSORSDOWNGRADE3_CAR1_RCH1_RES0_HYP1,
		HGN_SENSORSDOWNGRADE3_CAR0_RCH1_RES1_HYP1,
		HGN_SENSORSDOWNGRADE3_CAR1_RCH1_RES1_HYP1,
	},
	hgn_resourcecollectorhealthupgrade1 =
	{
		HGN_RESOURCECOLLECTORHEALTHUPGRADE1_RES0_HYP0,
		HGN_RESOURCECOLLECTORHEALTHUPGRADE1_RES1_HYP0,
		HGN_RESOURCECOLLECTORHEALTHUPGRADE1_RES0_HYP1,
		HGN_RESOURCECOLLECTORHEALTHUPGRADE1_RES1_HYP1,
	},
	hgn_resourcecontrollerhealthupgrade1 =
	{
		HGN_RESOURCECONTROLLERHEALTHUPGRADE1_RES0_HYP0,
		HGN_RESOURCECONTROLLERHEALTHUPGRADE1_RES1_HYP0,
		HGN_RESOURCECONTROLLERHEALTHUPGRADE1_RES0_HYP1,
		HGN_RESOURCECONTROLLERHEALTHUPGRADE1_RES1_HYP1,
	},
}
