VariantResearch =
{
	kus_allshipbuildspeed =
	{
		KUS_ALLSHIPBUILDSPEED,
	},
	kus_allshipbuildspeedexpert =
	{
		KUS_ALLSHIPBUILDSPEEDEXPERT,
	},
	kus_allshipbuildspeedhard =
	{
		KUS_ALLSHIPBUILDSPEEDHARD,
	},
	kus_cpuplayers_aggressive =
	{
		KUS_CPUPLAYERS_AGGRESSIVE,
	},
	kus_cpuplayers_defensive =
	{
		KUS_CPUPLAYERS_DEFENSIVE,
	},
	kus_cpuplayers_dynamic =
	{
		KUS_CPUPLAYERS_DYNAMIC,
	},
	kus_cpuplayers_norushtime10 =
	{
		KUS_CPUPLAYERS_NORUSHTIME10,
	},
	kus_cpuplayers_norushtime15 =
	{
		KUS_CPUPLAYERS_NORUSHTIME15,
	},
	kus_cpuplayers_norushtime5 =
	{
		KUS_CPUPLAYERS_NORUSHTIME5,
	},
	kus_resourcecollectionrateexpert =
	{
		KUS_RESOURCECOLLECTIONRATEEXPERT_RES0_HYP0,
		KUS_RESOURCECOLLECTIONRATEEXPERT_RES1_HYP0,
		KUS_RESOURCECOLLECTIONRATEEXPERT_RES0_HYP1,
		KUS_RESOURCECOLLECTIONRATEEXPERT_RES1_HYP1,
	},
	kus_resourcecollectionratehard =
	{
		KUS_RESOURCECOLLECTIONRATEHARD_RES0_HYP0,
		KUS_RESOURCECOLLECTIONRATEHARD_RES1_HYP0,
		KUS_RESOURCECOLLECTIONRATEHARD_RES0_HYP1,
		KUS_RESOURCECOLLECTIONRATEHARD_RES1_HYP1,
	},
	kus_weapondamageupgrade125 =
	{
		KUS_WEAPONDAMAGEUPGRADE125,
	},
	kus_weapondamageupgrade150 =
	{
		KUS_WEAPONDAMAGEUPGRADE150,
	},
	kus_weapondamageupgrade175 =
	{
		KUS_WEAPONDAMAGEUPGRADE175,
	},
	kus_weapondamageupgrade200 =
	{
		KUS_WEAPONDAMAGEUPGRADE200,
	},
	kus_corvettechassis =
	{
		KUS_CORVETTECHASSIS_HYP0,
		KUS_CORVETTECHASSIS_HYP1,
	},
	kus_corvettedrive =
	{
		KUS_CORVETTEDRIVE_HYP0,
		KUS_CORVETTEDRIVE_HYP1,
	},
	kus_fasttrackingturrets =
	{
		KUS_FASTTRACKINGTURRETS_HYP0,
		KUS_FASTTRACKINGTURRETS_HYP1,
	},
	kus_heavycorvetteupgrade =
	{
		KUS_HEAVYCORVETTEUPGRADE_HYP0,
		KUS_HEAVYCORVETTEUPGRADE_HYP1,
	},
	kus_minelayingtech =
	{
		KUS_MINELAYINGTECH_HYP0,
		KUS_MINELAYINGTECH_HYP1,
	},
	kus_cloakgenerator =
	{
		KUS_CLOAKGENERATOR_HYP0,
		KUS_CLOAKGENERATOR_HYP1,
	},
	kus_gravitygenerator =
	{
		KUS_GRAVITYGENERATOR_HYP0,
		KUS_GRAVITYGENERATOR_HYP1,
	},
	kus_hyperspacedamagereductionupgrade =
	{
		KUS_HYPERSPACEDAMAGEREDUCTIONUPGRADE,
	},
	kus_hyperspacedamagereductionupgradehc =
	{
		KUS_HYPERSPACEDAMAGEREDUCTIONUPGRADEHC_HYP0,
		KUS_HYPERSPACEDAMAGEREDUCTIONUPGRADEHC_HYP1,
	},
	kus_proximitysensor =
	{
		KUS_PROXIMITYSENSOR_HYP0,
		KUS_PROXIMITYSENSOR_HYP1,
	},
	kus_sensorarray =
	{
		KUS_SENSORARRAY_HYP0,
		KUS_SENSORARRAY_HYP1,
	},
	kus_sgmcapitalhealth =
	{
		KUS_SGMCAPITALHEALTH,
	},
	kus_sgmfrigatehealth =
	{
		KUS_SGMFRIGATEHEALTH,
	},
	kus_sgmgravwellhealth =
	{
		KUS_SGMGRAVWELLHEALTH_HYP0,
		KUS_SGMGRAVWELLHEALTH_HYP1,
	},
	kus_cloakedfighter =
	{
		KUS_CLOAKEDFIGHTER_HYP0,
		KUS_CLOAKEDFIGHTER_HYP1,
	},
	kus_defendersubsystems =
	{
		KUS_DEFENDERSUBSYSTEMS_HYP0,
		KUS_DEFENDERSUBSYSTEMS_HYP1,
	},
	kus_fighterchassis =
	{
		KUS_FIGHTERCHASSIS_HYP0,
		KUS_FIGHTERCHASSIS_HYP1,
	},
	kus_fighterdrive =
	{
		KUS_FIGHTERDRIVE_HYP0,
		KUS_FIGHTERDRIVE_HYP1,
	},
	kus_plasmabomblauncher =
	{
		KUS_PLASMABOMBLAUNCHER_HYP0,
		KUS_PLASMABOMBLAUNCHER_HYP1,
	},
	kus_capitalshipchassis =
	{
		KUS_CAPITALSHIPCHASSIS_HYP0,
		KUS_CAPITALSHIPCHASSIS_HYP1,
	},
	kus_capitalshipdrive =
	{
		KUS_CAPITALSHIPDRIVE_HYP0,
		KUS_CAPITALSHIPDRIVE_HYP1,
	},
	kus_dronetechnology =
	{
		KUS_DRONETECHNOLOGY_HYP0,
		KUS_DRONETECHNOLOGY_HYP1,
	},
	kus_ioncannons =
	{
		KUS_IONCANNONS_HYP0,
		KUS_IONCANNONS_HYP1,
	},
	kus_guidedmissiles =
	{
		KUS_GUIDEDMISSILES_HYP0,
		KUS_GUIDEDMISSILES_HYP1,
	},
	kus_heavyguns =
	{
		KUS_HEAVYGUNS_HYP0,
		KUS_HEAVYGUNS_HYP1,
	},
	kus_supercapitalshipdrive =
	{
		KUS_SUPERCAPITALSHIPDRIVE_RES0_HYP0,
		KUS_SUPERCAPITALSHIPDRIVE_RES1_HYP0,
		KUS_SUPERCAPITALSHIPDRIVE_RES0_HYP1,
		KUS_SUPERCAPITALSHIPDRIVE_RES1_HYP1,
	},
	kus_superheavychassis =
	{
		KUS_SUPERHEAVYCHASSIS_HYP0,
		KUS_SUPERHEAVYCHASSIS_HYP1,
	},
}
