VariantResearch =
{
	vgr_bomberimprovedbombs =
	{
		VGR_BOMBERIMPROVEDBOMBS_HYP0,
		VGR_BOMBERIMPROVEDBOMBS_HYP1,
	},
	vgr_repairability =
	{
		VGR_REPAIRABILITY_RES0_HYP0,
		VGR_REPAIRABILITY_RES1_HYP0,
		VGR_REPAIRABILITY_RES0_HYP1,
		VGR_REPAIRABILITY_RES1_HYP1,
	},
	vgr_scoutempability =
	{
		VGR_SCOUTEMPABILITY_HYP0,
		VGR_SCOUTEMPABILITY_HYP1,
	},
	vgr_allshipbuildspeed =
	{
		VGR_ALLSHIPBUILDSPEED,
	},
	vgr_allshipbuildspeedexpert =
	{
		VGR_ALLSHIPBUILDSPEEDEXPERT,
	},
	vgr_allshipbuildspeedhard =
	{
		VGR_ALLSHIPBUILDSPEEDHARD,
	},
	vgr_cpuplayers_aggressive =
	{
		VGR_CPUPLAYERS_AGGRESSIVE,
	},
	vgr_cpuplayers_defensive =
	{
		VGR_CPUPLAYERS_DEFENSIVE,
	},
	vgr_cpuplayers_dynamic =
	{
		VGR_CPUPLAYERS_DYNAMIC,
	},
	vgr_cpuplayers_norushtime10 =
	{
		VGR_CPUPLAYERS_NORUSHTIME10,
	},
	vgr_cpuplayers_norushtime15 =
	{
		VGR_CPUPLAYERS_NORUSHTIME15,
	},
	vgr_cpuplayers_norushtime5 =
	{
		VGR_CPUPLAYERS_NORUSHTIME5,
	},
	vgr_resourcecollectionrateexpert =
	{
		VGR_RESOURCECOLLECTIONRATEEXPERT_RES0_HYP0,
		VGR_RESOURCECOLLECTIONRATEEXPERT_RES1_HYP0,
		VGR_RESOURCECOLLECTIONRATEEXPERT_RES0_HYP1,
		VGR_RESOURCECOLLECTIONRATEEXPERT_RES1_HYP1,
	},
	vgr_resourcecollectionratehard =
	{
		VGR_RESOURCECOLLECTIONRATEHARD_RES0_HYP0,
		VGR_RESOURCECOLLECTIONRATEHARD_RES1_HYP0,
		VGR_RESOURCECOLLECTIONRATEHARD_RES0_HYP1,
		VGR_RESOURCECOLLECTIONRATEHARD_RES1_HYP1,
	},
	vgr_weapondamageupgrade125 =
	{
		VGR_WEAPONDAMAGEUPGRADE125,
	},
	vgr_weapondamageupgrade150 =
	{
		VGR_WEAPONDAMAGEUPGRADE150,
	},
	vgr_weapondamageupgrade175 =
	{
		VGR_WEAPONDAMAGEUPGRADE175,
	},
	vgr_weapondamageupgrade200 =
	{
		VGR_WEAPONDAMAGEUPGRADE200,
	},
	vgr_supercaphealthupgrade1 =
	{
		VGR_SUPERCAPHEALTHUPGRADE1,
	},
	vgr_supercapspeedupgrade1 =
	{
		VGR_SUPERCAPSPEEDUPGRADE1,
	},
	vgr_carrierbuildspeedupgrade1 =
	{
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP0,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP0,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP0,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP0,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP1,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP1,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP1,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP1,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP0,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP0,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP0,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP0,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP1,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP1,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP1,
		VGR_CARRIERBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	vgr_mothershipbuildspeedupgrade1 =
	{
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	vgr_mothershipbuildspeedupgrade1_makaan =
	{
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR0_RCH0_RES0_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR1_RCH0_RES0_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR0_RCH0_RES1_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR1_RCH0_RES1_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR0_RCH0_RES0_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR1_RCH0_RES0_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR0_RCH0_RES1_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR1_RCH0_RES1_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR0_RCH1_RES0_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR1_RCH1_RES0_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR0_RCH1_RES1_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR1_RCH1_RES1_HYP0,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR0_RCH1_RES0_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR1_RCH1_RES0_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR0_RCH1_RES1_HYP1,
		VGR_MOTHERSHIPBUILDSPEEDUPGRADE1_MAKAAN_CAR1_RCH1_RES1_HYP1,
	},
	vgr_shipyardbuildspeedupgrade1 =
	{
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP0,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP0,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP0,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP0,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH0_RES0_HYP1,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH0_RES0_HYP1,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH0_RES1_HYP1,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH0_RES1_HYP1,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP0,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP0,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP0,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP0,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH1_RES0_HYP1,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH1_RES0_HYP1,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR0_RCH1_RES1_HYP1,
		VGR_SHIPYARDBUILDSPEEDUPGRADE1_CAR1_RCH1_RES1_HYP1,
	},
	vgr_corvettehealthupgrade1 =
	{
		VGR_CORVETTEHEALTHUPGRADE1,
	},
	vgr_corvettespeedupgrade1 =
	{
		VGR_CORVETTESPEEDUPGRADE1,
	},
	vgr_battlecruiserionweapons =
	{
		VGR_BATTLECRUISERIONWEAPONS_HYP0,
		VGR_BATTLECRUISERIONWEAPONS_HYP1,
	},
	vgr_corvettecommand =
	{
		VGR_CORVETTECOMMAND_HYP0,
		VGR_CORVETTECOMMAND_HYP1,
	},
	vgr_corvettegraviticattraction =
	{
		VGR_CORVETTEGRAVITICATTRACTION_HYP0,
		VGR_CORVETTEGRAVITICATTRACTION_HYP1,
	},
	vgr_corvettelaser =
	{
		VGR_CORVETTELASER_HYP0,
		VGR_CORVETTELASER_HYP1,
	},
	vgr_corvettetech =
	{
		VGR_CORVETTETECH,
	},
	vgr_destroyerguns =
	{
		VGR_DESTROYERGUNS_HYP0,
		VGR_DESTROYERGUNS_HYP1,
	},
	vgr_frigateassault =
	{
		VGR_FRIGATEASSAULT_HYP0,
		VGR_FRIGATEASSAULT_HYP1,
	},
	vgr_frigateinfiltrationtech =
	{
		VGR_FRIGATEINFILTRATIONTECH_HYP0,
		VGR_FRIGATEINFILTRATIONTECH_HYP1,
	},
	vgr_frigatetech =
	{
		VGR_FRIGATETECH,
	},
	vgr_hyperspacedamagereductionupgrade =
	{
		VGR_HYPERSPACEDAMAGEREDUCTIONUPGRADE,
	},
	vgr_hyperspacegatetech =
	{
		VGR_HYPERSPACEGATETECH_HYP0,
		VGR_HYPERSPACEGATETECH_HYP1,
	},
	vgr_lancebeams =
	{
		VGR_LANCEBEAMS_HYP0,
		VGR_LANCEBEAMS_HYP1,
	},
	vgr_plasmabombs =
	{
		VGR_PLASMABOMBS_HYP0,
		VGR_PLASMABOMBS_HYP1,
	},
	vgr_platformheavymissiles =
	{
		VGR_PLATFORMHEAVYMISSILES_HYP0,
		VGR_PLATFORMHEAVYMISSILES_HYP1,
	},
	vgr_probeproxsensor =
	{
		VGR_PROBEPROXSENSOR_HYP0,
		VGR_PROBEPROXSENSOR_HYP1,
	},
	vgr_probesensordisruption =
	{
		VGR_PROBESENSORDISRUPTION_HYP0,
		VGR_PROBESENSORDISRUPTION_HYP1,
	},
	vgr_sgmcapitalhealth =
	{
		VGR_SGMCAPITALHEALTH_CAR0_RCH0_RES0_HYP0,
		VGR_SGMCAPITALHEALTH_CAR1_RCH0_RES0_HYP0,
		VGR_SGMCAPITALHEALTH_CAR0_RCH0_RES1_HYP0,
		VGR_SGMCAPITALHEALTH_CAR1_RCH0_RES1_HYP0,
		VGR_SGMCAPITALHEALTH_CAR0_RCH0_RES0_HYP1,
		VGR_SGMCAPITALHEALTH_CAR1_RCH0_RES0_HYP1,
		VGR_SGMCAPITALHEALTH_CAR0_RCH0_RES1_HYP1,
		VGR_SGMCAPITALHEALTH_CAR1_RCH0_RES1_HYP1,
		VGR_SGMCAPITALHEALTH_CAR0_RCH1_RES0_HYP0,
		VGR_SGMCAPITALHEALTH_CAR1_RCH1_RES0_HYP0,
		VGR_SGMCAPITALHEALTH_CAR0_RCH1_RES1_HYP0,
		VGR_SGMCAPITALHEALTH_CAR1_RCH1_RES1_HYP0,
		VGR_SGMCAPITALHEALTH_CAR0_RCH1_RES0_HYP1,
		VGR_SGMCAPITALHEALTH_CAR1_RCH1_RES0_HYP1,
		VGR_SGMCAPITALHEALTH_CAR0_RCH1_RES1_HYP1,
		VGR_SGMCAPITALHEALTH_CAR1_RCH1_RES1_HYP1,
	},
	vgr_sgmcapitalhealth_makaan =
	{
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR0_RCH0_RES0_HYP0,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR1_RCH0_RES0_HYP0,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR0_RCH0_RES1_HYP0,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR1_RCH0_RES1_HYP0,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR0_RCH0_RES0_HYP1,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR1_RCH0_RES0_HYP1,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR0_RCH0_RES1_HYP1,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR1_RCH0_RES1_HYP1,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR0_RCH1_RES0_HYP0,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR1_RCH1_RES0_HYP0,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR0_RCH1_RES1_HYP0,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR1_RCH1_RES1_HYP0,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR0_RCH1_RES0_HYP1,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR1_RCH1_RES0_HYP1,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR0_RCH1_RES1_HYP1,
		VGR_SGMCAPITALHEALTH_MAKAAN_CAR1_RCH1_RES1_HYP1,
	},
	vgr_sgmcarrierhealth =
	{
		VGR_SGMCARRIERHEALTH_CAR0_RCH0_RES0_HYP0,
		VGR_SGMCARRIERHEALTH_CAR1_RCH0_RES0_HYP0,
		VGR_SGMCARRIERHEALTH_CAR0_RCH0_RES1_HYP0,
		VGR_SGMCARRIERHEALTH_CAR1_RCH0_RES1_HYP0,
		VGR_SGMCARRIERHEALTH_CAR0_RCH0_RES0_HYP1,
		VGR_SGMCARRIERHEALTH_CAR1_RCH0_RES0_HYP1,
		VGR_SGMCARRIERHEALTH_CAR0_RCH0_RES1_HYP1,
		VGR_SGMCARRIERHEALTH_CAR1_RCH0_RES1_HYP1,
		VGR_SGMCARRIERHEALTH_CAR0_RCH1_RES0_HYP0,
		VGR_SGMCARRIERHEALTH_CAR1_RCH1_RES0_HYP0,
		VGR_SGMCARRIERHEALTH_CAR0_RCH1_RES1_HYP0,
		VGR_SGMCARRIERHEALTH_CAR1_RCH1_RES1_HYP0,
		VGR_SGMCARRIERHEALTH_CAR0_RCH1_RES0_HYP1,
		VGR_SGMCARRIERHEALTH_CAR1_RCH1_RES0_HYP1,
		VGR_SGMCARRIERHEALTH_CAR0_RCH1_RES1_HYP1,
		VGR_SGMCARRIERHEALTH_CAR1_RCH1_RES1_HYP1,
	},
	vgr_sgmfrigatehealth =
	{
		VGR_SGMFRIGATEHEALTH,
	},
	vgr_sgmshipyardhealth =
	{
		VGR_SGMSHIPYARDHEALTH_CAR0_RCH0_RES0_HYP0,
		VGR_SGMSHIPYARDHEALTH_CAR1_RCH0_RES0_HYP0,
		VGR_SGMSHIPYARDHEALTH_CAR0_RCH0_RES1_HYP0,
		VGR_SGMSHIPYARDHEALTH_CAR1_RCH0_RES1_HYP0,
		VGR_SGMSHIPYARDHEALTH_CAR0_RCH0_RES0_HYP1,
		VGR_SGMSHIPYARDHEALTH_CAR1_RCH0_RES0_HYP1,
		VGR_SGMSHIPYARDHEALTH_CAR0_RCH0_RES1_HYP1,
		VGR_SGMSHIPYARDHEALTH_CAR1_RCH0_RES1_HYP1,
		VGR_SGMSHIPYARDHEALTH_CAR0_RCH1_RES0_HYP0,
		VGR_SGMSHIPYARDHEALTH_CAR1_RCH1_RES0_HYP0,
		VGR_SGMSHIPYARDHEALTH_CAR0_RCH1_RES1_HYP0,
		VGR_SGMSHIPYARDHEALTH_CAR1_RCH1_RES1_HYP0,
		VGR_SGMSHIPYARDHEALTH_CAR0_RCH1_RES0_HYP1,
		VGR_SGMSHIPYARDHEALTH_CAR1_RCH1_RES0_HYP1,
		VGR_SGMSHIPYARDHEALTH_CAR0_RCH1_RES1_HYP1,
		VGR_SGMSHIPYARDHEALTH_CAR1_RCH1_RES1_HYP1,
	},
	vgr_fighterspeedupgrade1 =
	{
		VGR_FIGHTERSPEEDUPGRADE1,
	},
	vgr_frigatehealthupgrade1 =
	{
		VGR_FRIGATEHEALTHUPGRADE1,
	},
	vgr_frigatespeedupgrade1 =
	{
		VGR_FRIGATESPEEDUPGRADE1,
	},
	vgr_platformhealthupgrade1 =
	{
		VGR_PLATFORMHEALTHUPGRADE1,
	},
	vgr_corvettehealthupgradespgame =
	{
		VGR_CORVETTEHEALTHUPGRADESPGAME,
	},
	vgr_extrastrongvgrheavymissilesspgame =
	{
		VGR_EXTRASTRONGVGRHEAVYMISSILESSPGAME_HYP0,
		VGR_EXTRASTRONGVGRHEAVYMISSILESSPGAME_HYP1,
	},
	vgr_hyperspacerecoverytimeupgradespgame =
	{
		VGR_HYPERSPACERECOVERYTIMEUPGRADESPGAME,
	},
	vgr_hyperspacetransitiontimeupgradespgame =
	{
		VGR_HYPERSPACETRANSITIONTIMEUPGRADESPGAME,
	},
	vgr_makaanbattlecruiserhealth =
	{
		VGR_MAKAANBATTLECRUISERHEALTH_HYP0,
		VGR_MAKAANBATTLECRUISERHEALTH_HYP1,
	},
	vgr_makaancarrierhealth =
	{
		VGR_MAKAANCARRIERHEALTH_CAR0_RCH0_RES0_HYP0,
		VGR_MAKAANCARRIERHEALTH_CAR1_RCH0_RES0_HYP0,
		VGR_MAKAANCARRIERHEALTH_CAR0_RCH0_RES1_HYP0,
		VGR_MAKAANCARRIERHEALTH_CAR1_RCH0_RES1_HYP0,
		VGR_MAKAANCARRIERHEALTH_CAR0_RCH0_RES0_HYP1,
		VGR_MAKAANCARRIERHEALTH_CAR1_RCH0_RES0_HYP1,
		VGR_MAKAANCARRIERHEALTH_CAR0_RCH0_RES1_HYP1,
		VGR_MAKAANCARRIERHEALTH_CAR1_RCH0_RES1_HYP1,
		VGR_MAKAANCARRIERHEALTH_CAR0_RCH1_RES0_HYP0,
		VGR_MAKAANCARRIERHEALTH_CAR1_RCH1_RES0_HYP0,
		VGR_MAKAANCARRIERHEALTH_CAR0_RCH1_RES1_HYP0,
		VGR_MAKAANCARRIERHEALTH_CAR1_RCH1_RES1_HYP0,
		VGR_MAKAANCARRIERHEALTH_CAR0_RCH1_RES0_HYP1,
		VGR_MAKAANCARRIERHEALTH_CAR1_RCH1_RES0_HYP1,
		VGR_MAKAANCARRIERHEALTH_CAR0_RCH1_RES1_HYP1,
		VGR_MAKAANCARRIERHEALTH_CAR1_RCH1_RES1_HYP1,
	},
	vgr_makaancorvettehealth =
	{
		VGR_MAKAANCORVETTEHEALTH,
	},
	vgr_makaandestroyerhealth =
	{
		VGR_MAKAANDESTROYERHEALTH_HYP0,
		VGR_MAKAANDESTROYERHEALTH_HYP1,
	},
	vgr_makaanfighterhealth =
	{
		VGR_MAKAANFIGHTERHEALTH,
	},
	vgr_makaanfrigatehealth =
	{
		VGR_MAKAANFRIGATEHEALTH,
	},
	vgr_makaanplatformhealth =
	{
		VGR_MAKAANPLATFORMHEALTH,
	},
	vgr_makaanshipyardhealth =
	{
		VGR_MAKAANSHIPYARDHEALTH_CAR0_RCH0_RES0_HYP0,
		VGR_MAKAANSHIPYARDHEALTH_CAR1_RCH0_RES0_HYP0,
		VGR_MAKAANSHIPYARDHEALTH_CAR0_RCH0_RES1_HYP0,
		VGR_MAKAANSHIPYARDHEALTH_CAR1_RCH0_RES1_HYP0,
		VGR_MAKAANSHIPYARDHEALTH_CAR0_RCH0_RES0_HYP1,
		VGR_MAKAANSHIPYARDHEALTH_CAR1_RCH0_RES0_HYP1,
		VGR_MAKAANSHIPYARDHEALTH_CAR0_RCH0_RES1_HYP1,
		VGR_MAKAANSHIPYARDHEALTH_CAR1_RCH0_RES1_HYP1,
		VGR_MAKAANSHIPYARDHEALTH_CAR0_RCH1_RES0_HYP0,
		VGR_MAKAANSHIPYARDHEALTH_CAR1_RCH1_RES0_HYP0,
		VGR_MAKAANSHIPYARDHEALTH_CAR0_RCH1_RES1_HYP0,
		VGR_MAKAANSHIPYARDHEALTH_CAR1_RCH1_RES1_HYP0,
		VGR_MAKAANSHIPYARDHEALTH_CAR0_RCH1_RES0_HYP1,
		VGR_MAKAANSHIPYARDHEALTH_CAR1_RCH1_RES0_HYP1,
		VGR_MAKAANSHIPYARDHEALTH_CAR0_RCH1_RES1_HYP1,
		VGR_MAKAANSHIPYARDHEALTH_CAR1_RCH1_RES1_HYP1,
	},
	vgr_makaanutilityhealth =
	{
		VGR_MAKAANUTILITYHEALTH,
	},
	vgr_shipyardspeeddowngradespgame =
	{
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR0_RCH0_RES0_HYP0,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR1_RCH0_RES0_HYP0,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR0_RCH0_RES1_HYP0,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR1_RCH0_RES1_HYP0,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR0_RCH0_RES0_HYP1,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR1_RCH0_RES0_HYP1,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR0_RCH0_RES1_HYP1,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR1_RCH0_RES1_HYP1,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR0_RCH1_RES0_HYP0,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR1_RCH1_RES0_HYP0,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR0_RCH1_RES1_HYP0,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR1_RCH1_RES1_HYP0,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR0_RCH1_RES0_HYP1,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR1_RCH1_RES0_HYP1,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR0_RCH1_RES1_HYP1,
		VGR_SHIPYARDSPEEDDOWNGRADESPGAME_CAR1_RCH1_RES1_HYP1,
	},
	vgr_strongergunplats =
	{
		VGR_STRONGERGUNPLATS_HYP0,
		VGR_STRONGERGUNPLATS_HYP1,
	},
	vgr_strongermissileplats =
	{
		VGR_STRONGERMISSILEPLATS_HYP0,
		VGR_STRONGERMISSILEPLATS_HYP1,
	},
	vgr_supercapdamageappliedspgame =
	{
		VGR_SUPERCAPDAMAGEAPPLIEDSPGAME,
	},
	vgr_supercaphealthupgradespgame =
	{
		VGR_SUPERCAPHEALTHUPGRADESPGAME,
	},
	vgr_vaygrcapturehack =
	{
		VGR_VAYGRCAPTUREHACK_HYP0,
		VGR_VAYGRCAPTUREHACK_HYP1,
	},
	vgr_vaygrcarrierhealthregendowngrade =
	{
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR0_RCH0_RES0_HYP0,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR1_RCH0_RES0_HYP0,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR0_RCH0_RES1_HYP0,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR1_RCH0_RES1_HYP0,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR0_RCH0_RES0_HYP1,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR1_RCH0_RES0_HYP1,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR0_RCH0_RES1_HYP1,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR1_RCH0_RES1_HYP1,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR0_RCH1_RES0_HYP0,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR1_RCH1_RES0_HYP0,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR0_RCH1_RES1_HYP0,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR1_RCH1_RES1_HYP0,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR0_RCH1_RES0_HYP1,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR1_RCH1_RES0_HYP1,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR0_RCH1_RES1_HYP1,
		VGR_VAYGRCARRIERHEALTHREGENDOWNGRADE_CAR1_RCH1_RES1_HYP1,
	},
	vgr_vaygrcarrierhealthupgrade =
	{
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR0_RCH0_RES0_HYP0,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR1_RCH0_RES0_HYP0,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR0_RCH0_RES1_HYP0,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR1_RCH0_RES1_HYP0,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR0_RCH0_RES0_HYP1,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR1_RCH0_RES0_HYP1,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR0_RCH0_RES1_HYP1,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR1_RCH0_RES1_HYP1,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR0_RCH1_RES0_HYP0,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR1_RCH1_RES0_HYP0,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR0_RCH1_RES1_HYP0,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR1_RCH1_RES1_HYP0,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR0_RCH1_RES0_HYP1,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR1_RCH1_RES0_HYP1,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR0_RCH1_RES1_HYP1,
		VGR_VAYGRCARRIERHEALTHUPGRADE_CAR1_RCH1_RES1_HYP1,
	},
	vgr_vaygrfrigatehealthregendowngradespgame =
	{
		VGR_VAYGRFRIGATEHEALTHREGENDOWNGRADESPGAME,
	},
	vgr_vaygrfrigatehealthupgradespgame =
	{
		VGR_VAYGRFRIGATEHEALTHUPGRADESPGAME,
	},
	vgr_vaygrradiationimmunityhack =
	{
		VGR_VAYGRRADIATIONIMMUNITYHACK,
	},
	vgr_vaygrreducecapturehack =
	{
		VGR_VAYGRREDUCECAPTUREHACK_HYP0,
		VGR_VAYGRREDUCECAPTUREHACK_HYP1,
	},
	vgr_weakvgrheavymissiles =
	{
		VGR_WEAKVGRHEAVYMISSILES_HYP0,
		VGR_WEAKVGRHEAVYMISSILES_HYP1,
	},
	vgr_utilityhealthupgrade1 =
	{
		VGR_UTILITYHEALTHUPGRADE1,
	},
}
