VariantBuilds =
{
	vgr_battlecruiser =
	{
		VGR_BATTLECRUISER_HYP0,
		VGR_BATTLECRUISER_HYP1,
	},
	vgr_carrier =
	{
		VGR_CARRIER_CAR0_RCH0_RES0_HYP0,
		VGR_CARRIER_CAR1_RCH0_RES0_HYP0,
		VGR_CARRIER_CAR0_RCH0_RES1_HYP0,
		VGR_CARRIER_CAR1_RCH0_RES1_HYP0,
		VGR_CARRIER_CAR0_RCH0_RES0_HYP1,
		VGR_CARRIER_CAR1_RCH0_RES0_HYP1,
		VGR_CARRIER_CAR0_RCH0_RES1_HYP1,
		VGR_CARRIER_CAR1_RCH0_RES1_HYP1,
		VGR_CARRIER_CAR0_RCH1_RES0_HYP0,
		VGR_CARRIER_CAR1_RCH1_RES0_HYP0,
		VGR_CARRIER_CAR0_RCH1_RES1_HYP0,
		VGR_CARRIER_CAR1_RCH1_RES1_HYP0,
		VGR_CARRIER_CAR0_RCH1_RES0_HYP1,
		VGR_CARRIER_CAR1_RCH1_RES0_HYP1,
		VGR_CARRIER_CAR0_RCH1_RES1_HYP1,
		VGR_CARRIER_CAR1_RCH1_RES1_HYP1,
	},
	vgr_destroyer =
	{
		VGR_DESTROYER_HYP0,
		VGR_DESTROYER_HYP1,
	},
	vgr_shipyard =
	{
		VGR_SHIPYARD_CAR0_RCH0_RES0_HYP0,
		VGR_SHIPYARD_CAR1_RCH0_RES0_HYP0,
		VGR_SHIPYARD_CAR0_RCH0_RES1_HYP0,
		VGR_SHIPYARD_CAR1_RCH0_RES1_HYP0,
		VGR_SHIPYARD_CAR0_RCH0_RES0_HYP1,
		VGR_SHIPYARD_CAR1_RCH0_RES0_HYP1,
		VGR_SHIPYARD_CAR0_RCH0_RES1_HYP1,
		VGR_SHIPYARD_CAR1_RCH0_RES1_HYP1,
		VGR_SHIPYARD_CAR0_RCH1_RES0_HYP0,
		VGR_SHIPYARD_CAR1_RCH1_RES0_HYP0,
		VGR_SHIPYARD_CAR0_RCH1_RES1_HYP0,
		VGR_SHIPYARD_CAR1_RCH1_RES1_HYP0,
		VGR_SHIPYARD_CAR0_RCH1_RES0_HYP1,
		VGR_SHIPYARD_CAR1_RCH1_RES0_HYP1,
		VGR_SHIPYARD_CAR0_RCH1_RES1_HYP1,
		VGR_SHIPYARD_CAR1_RCH1_RES1_HYP1,
	},
	vgr_commandcorvette =
	{
		VGR_COMMANDCORVETTE_HYP0,
		VGR_COMMANDCORVETTE_HYP1,
	},
	vgr_lasercorvette =
	{
		VGR_LASERCORVETTE_HYP0,
		VGR_LASERCORVETTE_HYP1,
	},
	vgr_minelayercorvette =
	{
		VGR_MINELAYERCORVETTE_HYP0,
		VGR_MINELAYERCORVETTE_HYP1,
	},
	vgr_missilecorvette =
	{
		VGR_MISSILECORVETTE_HYP0,
		VGR_MISSILECORVETTE_HYP1,
	},
	vgr_bomber =
	{
		VGR_BOMBER_HYP0,
		VGR_BOMBER_HYP1,
	},
	vgr_interceptor =
	{
		VGR_INTERCEPTOR_HYP0,
		VGR_INTERCEPTOR_HYP1,
	},
	vgr_lancefighter =
	{
		VGR_LANCEFIGHTER_HYP0,
		VGR_LANCEFIGHTER_HYP1,
	},
	vgr_scout =
	{
		VGR_SCOUT_HYP0,
		VGR_SCOUT_HYP1,
	},
	vgr_assaultfrigate =
	{
		VGR_ASSAULTFRIGATE_HYP0,
		VGR_ASSAULTFRIGATE_HYP1,
	},
	vgr_heavymissilefrigate =
	{
		VGR_HEAVYMISSILEFRIGATE_HYP0,
		VGR_HEAVYMISSILEFRIGATE_HYP1,
	},
	vgr_infiltratorfrigate =
	{
		VGR_INFILTRATORFRIGATE_HYP0,
		VGR_INFILTRATORFRIGATE_HYP1,
	},
	vgr_weaponplatform_gun =
	{
		VGR_WEAPONPLATFORM_GUN_HYP0,
		VGR_WEAPONPLATFORM_GUN_HYP1,
	},
	vgr_weaponplatform_missile =
	{
		VGR_WEAPONPLATFORM_MISSILE_HYP0,
		VGR_WEAPONPLATFORM_MISSILE_HYP1,
	},
	vgr_planetkillermissile =
	{
		VGR_PLANETKILLERMISSILE,
	},
	vgr_c_module_cloakgenerator =
	{
		VGR_C_MODULE_CLOAKGENERATOR_RCH0,
		VGR_C_MODULE_CLOAKGENERATOR_RCH1,
	},
	vgr_c_module_firecontrol =
	{
		VGR_C_MODULE_FIRECONTROL_RCH0,
		VGR_C_MODULE_FIRECONTROL_RCH1,
	},
	vgr_c_module_hyperspace =
	{
		VGR_C_MODULE_HYPERSPACE,
	},
	vgr_c_module_hyperspaceinhibitor =
	{
		VGR_C_MODULE_HYPERSPACEINHIBITOR_RCH0,
		VGR_C_MODULE_HYPERSPACEINHIBITOR_RCH1,
	},
	vgr_c_module_platformcontrol =
	{
		VGR_C_MODULE_PLATFORMCONTROL,
	},
	vgr_c_module_research =
	{
		VGR_C_MODULE_RESEARCH,
	},
	vgr_c_production_corvette =
	{
		VGR_C_PRODUCTION_CORVETTE_CAR0,
		VGR_C_PRODUCTION_CORVETTE_CAR1,
	},
	vgr_c_production_fighter =
	{
		VGR_C_PRODUCTION_FIGHTER_CAR0,
		VGR_C_PRODUCTION_FIGHTER_CAR1,
	},
	vgr_c_production_frigate =
	{
		VGR_C_PRODUCTION_FRIGATE,
	},
	vgr_c_sensors_advancedarray =
	{
		VGR_C_SENSORS_ADVANCEDARRAY,
	},
	vgr_c_sensors_detecthyperspace =
	{
		VGR_C_SENSORS_DETECTHYPERSPACE,
	},
	vgr_ms_module_cloakgenerator =
	{
		VGR_MS_MODULE_CLOAKGENERATOR_RCH0,
		VGR_MS_MODULE_CLOAKGENERATOR_RCH1,
	},
	vgr_ms_module_firecontrol =
	{
		VGR_MS_MODULE_FIRECONTROL_RCH0,
		VGR_MS_MODULE_FIRECONTROL_RCH1,
	},
	vgr_ms_module_hyperspace =
	{
		VGR_MS_MODULE_HYPERSPACE,
	},
	vgr_ms_module_hyperspaceinhibitor =
	{
		VGR_MS_MODULE_HYPERSPACEINHIBITOR_RCH0,
		VGR_MS_MODULE_HYPERSPACEINHIBITOR_RCH1,
	},
	vgr_ms_module_platformcontrol =
	{
		VGR_MS_MODULE_PLATFORMCONTROL,
	},
	vgr_ms_module_research =
	{
		VGR_MS_MODULE_RESEARCH,
	},
	vgr_ms_production_capship =
	{
		VGR_MS_PRODUCTION_CAPSHIP,
	},
	vgr_ms_production_corvette =
	{
		VGR_MS_PRODUCTION_CORVETTE,
	},
	vgr_ms_production_fighter =
	{
		VGR_MS_PRODUCTION_FIGHTER,
	},
	vgr_ms_production_frigate =
	{
		VGR_MS_PRODUCTION_FRIGATE,
	},
	vgr_ms_sensors_advancedarray =
	{
		VGR_MS_SENSORS_ADVANCEDARRAY,
	},
	vgr_ms_sensors_detecthyperspace =
	{
		VGR_MS_SENSORS_DETECTHYPERSPACE,
	},
	vgr_sy_production_capship =
	{
		VGR_SY_PRODUCTION_CAPSHIP,
	},
	vgr_hyperspace_platform =
	{
		VGR_HYPERSPACE_PLATFORM_HYP0,
		VGR_HYPERSPACE_PLATFORM_HYP1,
	},
	vgr_probe =
	{
		VGR_PROBE_HYP0,
		VGR_PROBE_HYP1,
	},
	vgr_probe_ecm =
	{
		VGR_PROBE_ECM_HYP0,
		VGR_PROBE_ECM_HYP1,
	},
	vgr_probe_prox =
	{
		VGR_PROBE_PROX_HYP0,
		VGR_PROBE_PROX_HYP1,
	},
	vgr_resourcecollector =
	{
		VGR_RESOURCECOLLECTOR_RES0_HYP0,
		VGR_RESOURCECOLLECTOR_RES1_HYP0,
		VGR_RESOURCECOLLECTOR_RES0_HYP1,
		VGR_RESOURCECOLLECTOR_RES1_HYP1,
	},
	vgr_resourcecontroller =
	{
		VGR_RESOURCECONTROLLER_RES0_HYP0,
		VGR_RESOURCECONTROLLER_RES1_HYP0,
		VGR_RESOURCECONTROLLER_RES0_HYP1,
		VGR_RESOURCECONTROLLER_RES1_HYP1,
	},
}
