-- Research, ships & modules restricted by individual gamerules
RestrictedBy =
{
	-- see "restrict.lua"
	-- make sure all variants are listed
	MPRestrict =
	{
		hiigaran_hwce =
		{
			build = {},
			research =
			{
				"AssaultCorvetteEliteWeaponUpgrade",
				"AttackBomberEliteWeaponUpgrade",
				"SensorsDowngrade1",
				"SensorsDowngrade2",
				"SensorsDowngrade3",
				"SensorsBackToNormal1",
				"SensorsBackToNormal2",
				"SensorsBackToNormal3",
				"MoverHealthDowngrade",
				"MoverHealthUpgrade",
				"FrigateHealthUpgradeSPGAME",
				"DamageMoverTech",
				"KeeperHealthUpgradeSPGAME_LOW",
				"KeeperHealthUpgradeSPGAME_MED",
				"KeeperHealthUpgradeSPGAME_HIGH",
				"KeeperWeaponUpgradeSPGAME_M10_LVL_1",
				"KeeperWeaponUpgradeSPGAME_M10_LVL_2",
				"KeeperWeaponUpgradeSPGAME_M10_LVL_3",
				"KeeperWeaponUpgradeSPGAME_M10_LVL_4",
				"KeeperWeaponUpgradeSPGAME_M10_LVL_5",
				"KeeperWeaponUpgradeSPGAME_M10_LVL_6",
				"KeeperHealthUpgradeSPGAME_M10_LVL_1",
				"KeeperHealthUpgradeSPGAME_M10_LVL_2",
				"KeeperHealthUpgradeSPGAME_M10_LVL_3",
				"AttackDroidHealthUpgradeSPGAME_LOW",
				"AttackDroidHealthUpgradeSPGAME_MED",
				"AttackDroidHealthUpgradeSPGAME_HIGH",
				"AttackDroidWeaponUpgradeSPGAME_LOW",
				"AttackDroidWeaponUpgradeSPGAME_MED",
				"AttackDroidWeaponUpgradeSPGAME_HIGH",
				"RadiationDefenseField",
			},
		},
		vaygr_hwce =
		{
			build = {},
			research =
			{
				"WeakVgrHeavyMissiles",
				"HyperspaceRecoveryTimeUpgradeSPGAME",
				"HyperspaceTransitionTimeUpgradeSPGAME",
				"VaygrCarrierHealthRegenDowngrade",
				"ShipyardSpeedDowngradeSPGAME",
				"SuperCapHealthUpgradeSPGAME",
				"VaygrFrigateHealthUpgradeSPGAME",
				"VaygrFrigateHealthRegenDowngradeSPGAME",
				"CorvetteHealthUpgradeSPGAME",
				"ExtraStrongVgrHeavyMissilesSPGAME",
				"VaygrCaptureHack",
				"VaygrReduceCaptureHack",
				"VaygrRadiationImmunityHack",
				"VaygrCarrierHealthUpgrade",
			},
		},
		kushan_hwce =
		{
			build = {},
			research = {},
		},
		taiidan_hwce =
		{
			build = {},
			research = {},
		},
	},
	-- need to restrict these for human players since they are only meant to be used by the AI
	-- make sure all variants are listed
	HumanPlayer =
	{
		hiigaran_hwce =
		{
			build = {},
			research =
			{
				"AllShipBuildSpeed",
				"AllShipBuildSpeedExpert",
				"AllShipBuildSpeedHard",
				"cpuplayers_aggressive",
				"cpuplayers_defensive",
				"cpuplayers_dynamic",
				"cpuplayers_norushtime10",
				"cpuplayers_norushtime15",
				"cpuplayers_norushtime5",
				"ResourceCollectionRateExpert",
				"ResourceCollectionRateHard",
				"WeaponDamageUpgrade125",
				"WeaponDamageUpgrade150",
				"WeaponDamageUpgrade175",
				"WeaponDamageUpgrade200",
			},
		},
		vaygr_hwce =
		{
			build = {},
			research =
			{
				"AllShipBuildSpeed",
				"AllShipBuildSpeedExpert",
				"AllShipBuildSpeedHard",
				"cpuplayers_aggressive",
				"cpuplayers_defensive",
				"cpuplayers_dynamic",
				"cpuplayers_norushtime10",
				"cpuplayers_norushtime15",
				"cpuplayers_norushtime5",
				"ResourceCollectionRateExpert",
				"ResourceCollectionRateHard",
				"WeaponDamageUpgrade125",
				"WeaponDamageUpgrade150",
				"WeaponDamageUpgrade175",
				"WeaponDamageUpgrade200",
			},
		},
		kushan_hwce =
		{
			build = {},
			research =
			{
				"cpuplayers_defensive",
				"cpuplayers_aggressive",
				"cpuplayers_dynamic",
				"cpuplayers_norushtime5",
				"cpuplayers_norushtime10",
				"cpuplayers_norushtime15",
				"AllShipBuildSpeed",
				"AllShipBuildSpeedHard",
				"AllShipBuildSpeedExpert",
				"ResourceCollectionRateHard",
				"ResourceCollectionRateExpert",
				"WeaponDamageUpgrade125",
				"WeaponDamageUpgrade150",
				"WeaponDamageUpgrade175",
				"WeaponDamageUpgrade200",
			},
		},
		taiidan_hwce =
		{
			build = {},
			research =
			{
				"AllShipBuildSpeed",
				"AllShipBuildSpeedExpert",
				"AllShipBuildSpeedHard",
				"cpuplayers_aggressive",
				"cpuplayers_defensive",
				"cpuplayers_dynamic",
				"cpuplayers_norushtime10",
				"cpuplayers_norushtime15",
				"cpuplayers_norushtime5",
				"ResourceCollectionRateExpert",
				"ResourceCollectionRateHard",
				"WeaponDamageUpgrade125",
				"WeaponDamageUpgrade150",
				"WeaponDamageUpgrade175",
				"WeaponDamageUpgrade200",
			},
		},
	},
	-- "Start With" is set to "Mothership".
	-- this is the "normal" mode
	StartWithMothership =
	{
		hiigaran_hwce =
		{
			build =
			{
				"hgn_mothership_car1_rch0_res0_hyp0",
				"hgn_mothership_car1_rch0_res0_hyp1",
				"hgn_mothership_car1_rch0_res1_hyp0",
				"hgn_mothership_car1_rch0_res1_hyp1",
				"hgn_mothership_car1_rch1_res0_hyp0",
				"hgn_mothership_car1_rch1_res0_hyp1",
				"hgn_mothership_car1_rch1_res1_hyp0",
				"hgn_mothership_car1_rch1_res1_hyp1",
				"hgn_shipyard_car1_rch0_res0_hyp0",
				"hgn_shipyard_car1_rch0_res0_hyp1",
				"hgn_shipyard_car1_rch0_res1_hyp0",
				"hgn_shipyard_car1_rch0_res1_hyp1",
				"hgn_shipyard_car1_rch1_res0_hyp0",
				"hgn_shipyard_car1_rch1_res0_hyp1",
				"hgn_shipyard_car1_rch1_res1_hyp0",
				"hgn_shipyard_car1_rch1_res1_hyp1",
				"hgn_shipyard_spg_car1_rch0_res0_hyp0",
				"hgn_shipyard_spg_car1_rch0_res0_hyp1",
				"hgn_shipyard_spg_car1_rch0_res1_hyp0",
				"hgn_shipyard_spg_car1_rch0_res1_hyp1",
				"hgn_shipyard_spg_car1_rch1_res0_hyp0",
				"hgn_shipyard_spg_car1_rch1_res0_hyp1",
				"hgn_shipyard_spg_car1_rch1_res1_hyp0",
				"hgn_shipyard_spg_car1_rch1_res1_hyp1",
				"hgn_shipyard_elohim_car1_rch0_res0_hyp0",
				"hgn_shipyard_elohim_car1_rch0_res0_hyp1",
				"hgn_shipyard_elohim_car1_rch0_res1_hyp0",
				"hgn_shipyard_elohim_car1_rch0_res1_hyp1",
				"hgn_shipyard_elohim_car1_rch1_res0_hyp0",
				"hgn_shipyard_elohim_car1_rch1_res0_hyp1",
				"hgn_shipyard_elohim_car1_rch1_res1_hyp0",
				"hgn_shipyard_elohim_car1_rch1_res1_hyp1",
				"hgn_carrier_car1_rch0_res0_hyp0",
				"hgn_carrier_car1_rch0_res0_hyp1",
				"hgn_carrier_car1_rch0_res1_hyp0",
				"hgn_carrier_car1_rch0_res1_hyp1",
				"hgn_carrier_car1_rch1_res0_hyp0",
				"hgn_carrier_car1_rch1_res0_hyp1",
				"hgn_carrier_car1_rch1_res1_hyp0",
				"hgn_carrier_car1_rch1_res1_hyp1",
			},
			research = {},
		},
		vaygr_hwce =
		{
			build =
			{
				"Vgr_C_Production_Fighter_car1",
				"Vgr_C_Production_Corvette_car1",
				"vgr_mothership_car1_rch0_res0_hyp0",
				"vgr_mothership_car1_rch0_res0_hyp1",
				"vgr_mothership_car1_rch0_res1_hyp0",
				"vgr_mothership_car1_rch0_res1_hyp1",
				"vgr_mothership_car1_rch1_res0_hyp0",
				"vgr_mothership_car1_rch1_res0_hyp1",
				"vgr_mothership_car1_rch1_res1_hyp0",
				"vgr_mothership_car1_rch1_res1_hyp1",
				"vgr_mothership_makaan_car1_rch0_res0_hyp0",
				"vgr_mothership_makaan_car1_rch0_res0_hyp1",
				"vgr_mothership_makaan_car1_rch0_res1_hyp0",
				"vgr_mothership_makaan_car1_rch0_res1_hyp1",
				"vgr_mothership_makaan_car1_rch1_res0_hyp0",
				"vgr_mothership_makaan_car1_rch1_res0_hyp1",
				"vgr_mothership_makaan_car1_rch1_res1_hyp0",
				"vgr_mothership_makaan_car1_rch1_res1_hyp1",
				"vgr_shipyard_car1_rch0_res0_hyp0",
				"vgr_shipyard_car1_rch0_res0_hyp1",
				"vgr_shipyard_car1_rch0_res1_hyp0",
				"vgr_shipyard_car1_rch0_res1_hyp1",
				"vgr_shipyard_car1_rch1_res0_hyp0",
				"vgr_shipyard_car1_rch1_res0_hyp1",
				"vgr_shipyard_car1_rch1_res1_hyp0",
				"vgr_shipyard_car1_rch1_res1_hyp1",
				"vgr_carrier_car1_rch0_res0_hyp0",
				"vgr_carrier_car1_rch0_res0_hyp1",
				"vgr_carrier_car1_rch0_res1_hyp0",
				"vgr_carrier_car1_rch0_res1_hyp1",
				"vgr_carrier_car1_rch1_res0_hyp0",
				"vgr_carrier_car1_rch1_res0_hyp1",
				"vgr_carrier_car1_rch1_res1_hyp0",
				"vgr_carrier_car1_rch1_res1_hyp1",
			},
			research = {},
		},
		kushan_hwce =
		{
			build =
			{
				"kus_mothership_car1_res0_hyp0",
				"kus_mothership_car1_res1_hyp0",
				"kus_mothership_car1_res0_hyp1",
				"kus_mothership_car1_res1_hyp1",
			},
			research = {},
		},
		taiidan_hwce =
		{
			build =
			{
				"tai_mothership_car1_res0_hyp0",
				"tai_mothership_car1_res1_hyp0",
				"tai_mothership_car1_res0_hyp1",
				"tai_mothership_car1_res1_hyp1",
			},
			research = {},
		},
	},
	-- "Start With" is set to "HW1 Map Default".
	-- still need to decide how I want to handle this gamerule
	-- maybe create a routine to swap all unsuffixed "from the map" ships with suffixed versions while still obeying the other gamerules
	-- for the time being I am simply restricting all suffixed ships here
	StartWithMapDefault =
	{
		hiigaran_hwce =
		{
			build = {},
			research = {},
		},
		vaygr_hwce =
		{
			build = {},
			research = {}
		},
		kushan_hwce =
		{
			build = {},
			research = {},
		},
		taiidan_hwce =
		{
			build = {},
			research = {},
		},
	},
	-- "Start With" is set to "Carrier Only".
	-- this could be called the "anti-capital" mode since the construction and upgrading of capital ships is restricted here
	-- should the building or capture of capital ships really be restricted?
	-- should every possibility of capital ships (except the carrier you start with) appearing in this mode be removed?
	StartWithCarrierOnly =
	{
		hiigaran_hwce =
		{
			build =
			{
				"Hgn_MS_Production_CapShip",
				"Hgn_SY_Production_CapShip",
				"hgn_mothership_car0_rch0_res0_hyp0",
				"hgn_mothership_car0_rch0_res0_hyp1",
				"hgn_mothership_car0_rch0_res1_hyp0",
				"hgn_mothership_car0_rch0_res1_hyp1",
				"hgn_mothership_car0_rch1_res0_hyp0",
				"hgn_mothership_car0_rch1_res0_hyp1",
				"hgn_mothership_car0_rch1_res1_hyp0",
				"hgn_mothership_car0_rch1_res1_hyp1",
				"hgn_shipyard_car0_rch0_res0_hyp0",
				"hgn_shipyard_car0_rch0_res0_hyp1",
				"hgn_shipyard_car0_rch0_res1_hyp0",
				"hgn_shipyard_car0_rch0_res1_hyp1",
				"hgn_shipyard_car0_rch1_res0_hyp0",
				"hgn_shipyard_car0_rch1_res0_hyp1",
				"hgn_shipyard_car0_rch1_res1_hyp0",
				"hgn_shipyard_car0_rch1_res1_hyp1",
				"hgn_shipyard_spg_car0_rch0_res0_hyp0",
				"hgn_shipyard_spg_car0_rch0_res0_hyp1",
				"hgn_shipyard_spg_car0_rch0_res1_hyp0",
				"hgn_shipyard_spg_car0_rch0_res1_hyp1",
				"hgn_shipyard_spg_car0_rch1_res0_hyp0",
				"hgn_shipyard_spg_car0_rch1_res0_hyp1",
				"hgn_shipyard_spg_car0_rch1_res1_hyp0",
				"hgn_shipyard_spg_car0_rch1_res1_hyp1",
				"hgn_shipyard_elohim_car0_rch0_res0_hyp0",
				"hgn_shipyard_elohim_car0_rch0_res0_hyp1",
				"hgn_shipyard_elohim_car0_rch0_res1_hyp0",
				"hgn_shipyard_elohim_car0_rch0_res1_hyp1",
				"hgn_shipyard_elohim_car0_rch1_res0_hyp0",
				"hgn_shipyard_elohim_car0_rch1_res0_hyp1",
				"hgn_shipyard_elohim_car0_rch1_res1_hyp0",
				"hgn_shipyard_elohim_car0_rch1_res1_hyp1",
				"hgn_carrier_car0_rch0_res0_hyp0",
				"hgn_carrier_car0_rch0_res0_hyp1",
				"hgn_carrier_car0_rch0_res1_hyp0",
				"hgn_carrier_car0_rch0_res1_hyp1",
				"hgn_carrier_car0_rch1_res0_hyp0",
				"hgn_carrier_car0_rch1_res0_hyp1",
				"hgn_carrier_car0_rch1_res1_hyp0",
				"hgn_carrier_car0_rch1_res1_hyp1",
				"Hgn_Battlecruiser_hyp0",
				"Hgn_Battlecruiser_hyp1",
			},
			research =
			{
				"MothershipHealthUpgrade1",
				"MothershipMAXSPEEDUpgrade1",
				"MothershipBUILDSPEEDUpgrade1",
				"ShipyardHealthUpgrade1",
				"ShipyardMAXSPEEDUpgrade1",
				"ShipyardBUILDSPEEDUpgrade1",
				--"CarrierHealthUpgrade1",
				--"CarrierMAXSPEEDUpgrade1",
				--"CarrierBUILDSPEEDUpgrade1",
				"BattlecruiserHealthUpgrade1",
				"BattlecruiserMAXSPEEDUpgrade1",
				"BattlecruiserIonWeapons",
				"DestroyerTech",
				"DestroyerHealthUpgrade1",
				"DestroyerMAXSPEEDUpgrade1",
			},
		},
		vaygr_hwce =
		{
			build =
			{
				"Vgr_C_Production_Fighter_car0",
				"Vgr_C_Production_Corvette_car0",
				"Vgr_MS_Production_CapShip",
				"Vgr_SY_Production_CapShip",
				"vgr_mothership_car0_rch0_res0_hyp0",
				"vgr_mothership_car0_rch0_res0_hyp1",
				"vgr_mothership_car0_rch0_res1_hyp0",
				"vgr_mothership_car0_rch0_res1_hyp1",
				"vgr_mothership_car0_rch1_res0_hyp0",
				"vgr_mothership_car0_rch1_res0_hyp1",
				"vgr_mothership_car0_rch1_res1_hyp0",
				"vgr_mothership_car0_rch1_res1_hyp1",
				"vgr_mothership_makaan_car0_rch0_res0_hyp0",
				"vgr_mothership_makaan_car0_rch0_res0_hyp1",
				"vgr_mothership_makaan_car0_rch0_res1_hyp0",
				"vgr_mothership_makaan_car0_rch0_res1_hyp1",
				"vgr_mothership_makaan_car0_rch1_res0_hyp0",
				"vgr_mothership_makaan_car0_rch1_res0_hyp1",
				"vgr_mothership_makaan_car0_rch1_res1_hyp0",
				"vgr_mothership_makaan_car0_rch1_res1_hyp1",
				"vgr_shipyard_car0_rch0_res0_hyp0",
				"vgr_shipyard_car0_rch0_res0_hyp1",
				"vgr_shipyard_car0_rch0_res1_hyp0",
				"vgr_shipyard_car0_rch0_res1_hyp1",
				"vgr_shipyard_car0_rch1_res0_hyp0",
				"vgr_shipyard_car0_rch1_res0_hyp1",
				"vgr_shipyard_car0_rch1_res1_hyp0",
				"vgr_shipyard_car0_rch1_res1_hyp1",
				"vgr_carrier_car0_rch0_res0_hyp0",
				"vgr_carrier_car0_rch0_res0_hyp1",
				"vgr_carrier_car0_rch0_res1_hyp0",
				"vgr_carrier_car0_rch0_res1_hyp1",
				"vgr_carrier_car0_rch1_res0_hyp0",
				"vgr_carrier_car0_rch1_res0_hyp1",
				"vgr_carrier_car0_rch1_res1_hyp0",
				"vgr_carrier_car0_rch1_res1_hyp1",
				"Vgr_Battlecruiser_hyp0",
				"Vgr_Battlecruiser_hyp1",
			},
			research =
			{
				"MothershipBUILDSPEEDUpgrade1",
				--"CarrierBUILDSPEEDUpgrade1",
				"ShipyardBUILDSPEEDUpgrade1_hyp0",
				"ShipyardBUILDSPEEDUpgrade1_hyp1",
				"SuperCapHealthUpgrade1",
				"SuperCapSpeedUpgrade1",
				"BattlecruiserIonWeapons",
				"DestroyerGuns",
			},
		},
		kushan_hwce =
		{
			build =
			{
				"hw1_production_capital",
				"kus_mothership_car0_res0_hyp0",
				"kus_mothership_car0_res1_hyp0",
				"kus_mothership_car0_res0_hyp1",
				"kus_mothership_car0_res1_hyp1",
				"kus_carrier_res0_hyp0",
				"kus_carrier_res1_hyp0",
				"kus_carrier_res0_hyp1",
				"kus_carrier_res1_hyp1",
				"Kus_Destroyer_hyp0",
				"Kus_Destroyer_hyp1",
				"Kus_MissileDestroyer_hyp0",
				"Kus_MissileDestroyer_hyp1",
				"Kus_HeavyCruiser_hyp0",
				"Kus_HeavyCruiser_hyp1",
			},
			research =
			{
				"SuperCapitalShipDrive",
				"GuidedMissiles",
				"SuperHeavyChassis",
				"HeavyGuns",
			},
		},
		taiidan_hwce =
		{
			build =
			{
				"hw1_production_capital",
				"tai_mothership_car0_res0_hyp0",
				"tai_mothership_car0_res1_hyp0",
				"tai_mothership_car0_res0_hyp1",
				"tai_mothership_car0_res1_hyp1",
				"tai_carrier_res0_hyp0",
				"tai_carrier_res1_hyp0",
				"tai_carrier_res0_hyp1",
				"tai_carrier_res1_hyp1",
				"Tai_Destroyer_hyp0",
				"Tai_Destroyer_hyp1",
				"Tai_MissileDestroyer_hyp0",
				"Tai_MissileDestroyer_hyp1",
				"Tai_HeavyCruiser_hyp0",
				"Tai_HeavyCruiser_hyp1",
			},
			research =
			{
				"SuperCapitalShipDrive",
				"GuidedMissiles",
				"SuperHeavyChassis",
				"HeavyGuns",
			},
		},
	},
	-- "Research" is set to "Off".
	-- should maybe also remove dependency on research modules from research items
	-- should maybe create innate indestructible research subsystems on each capital ship instead of what I am currently doing
	ResearchOff =
	{
		hiigaran_hwce =
		{
			build =
			{
				"Hgn_C_Module_Research",
				"Hgn_MS_Module_Research",
				"Hgn_C_Module_ResearchAdvanced",
				"Hgn_MS_Module_ResearchAdvanced",
				"Hgn_C_Module_Hyperspace_rch1",
				"Hgn_C_Module_HyperspaceInhibitor_rch1",
				"Hgn_C_Module_CloakGenerator_rch1",
				"Hgn_C_Module_FireControl_rch1",
				"Hgn_MS_Module_Hyperspace_rch1",
				"Hgn_MS_Module_HyperspaceInhibitor_rch1",
				"Hgn_MS_Module_CloakGenerator_rch1",
				"Hgn_MS_Module_FireControl_rch1",
				"Hgn_C_Production_Frigate_rch1",
				"Hgn_MS_Production_Frigate_rch1",
				"hgn_mothership_car0_rch1_res0_hyp0",
				"hgn_mothership_car0_rch1_res0_hyp1",
				"hgn_mothership_car0_rch1_res1_hyp0",
				"hgn_mothership_car0_rch1_res1_hyp1",
				"hgn_mothership_car1_rch1_res0_hyp0",
				"hgn_mothership_car1_rch1_res0_hyp1",
				"hgn_mothership_car1_rch1_res1_hyp0",
				"hgn_mothership_car1_rch1_res1_hyp1",
				"hgn_carrier_car0_rch1_res0_hyp0",
				"hgn_carrier_car0_rch1_res0_hyp1",
				"hgn_carrier_car0_rch1_res1_hyp0",
				"hgn_carrier_car0_rch1_res1_hyp1",
				"hgn_carrier_car1_rch1_res0_hyp0",
				"hgn_carrier_car1_rch1_res0_hyp1",
				"hgn_carrier_car1_rch1_res1_hyp0",
				"hgn_carrier_car1_rch1_res1_hyp1",
				"hgn_shipyard_car0_rch1_res0_hyp0",
				"hgn_shipyard_car0_rch1_res0_hyp1",
				"hgn_shipyard_car0_rch1_res1_hyp0",
				"hgn_shipyard_car0_rch1_res1_hyp1",
				"hgn_shipyard_car1_rch1_res0_hyp0",
				"hgn_shipyard_car1_rch1_res0_hyp1",
				"hgn_shipyard_car1_rch1_res1_hyp0",
				"hgn_shipyard_car1_rch1_res1_hyp1",
				"hgn_shipyard_spg_car0_rch1_res0_hyp0",
				"hgn_shipyard_spg_car0_rch1_res0_hyp1",
				"hgn_shipyard_spg_car0_rch1_res1_hyp0",
				"hgn_shipyard_spg_car0_rch1_res1_hyp1",
				"hgn_shipyard_spg_car1_rch1_res0_hyp0",
				"hgn_shipyard_spg_car1_rch1_res0_hyp1",
				"hgn_shipyard_spg_car1_rch1_res1_hyp0",
				"hgn_shipyard_spg_car1_rch1_res1_hyp1",
				"hgn_shipyard_elohim_car0_rch1_res0_hyp0",
				"hgn_shipyard_elohim_car0_rch1_res0_hyp1",
				"hgn_shipyard_elohim_car0_rch1_res1_hyp0",
				"hgn_shipyard_elohim_car0_rch1_res1_hyp1",
				"hgn_shipyard_elohim_car1_rch1_res0_hyp0",
				"hgn_shipyard_elohim_car1_rch1_res0_hyp1",
				"hgn_shipyard_elohim_car1_rch1_res1_hyp0",
				"hgn_shipyard_elohim_car1_rch1_res1_hyp1",
			},
			research = {},
		},
		vaygr_hwce =
		{
			build =
			{
				"Vgr_C_Module_Research",
				"Vgr_MS_Module_Research",
				--"Vgr_C_Module_Hyperspace_rch1",		-- item does not require research module
				"Vgr_C_Module_HyperspaceInhibitor_rch1",
				"Vgr_C_Module_CloakGenerator_rch1",
				"Vgr_C_Module_FireControl_rch1",
				--"Vgr_MS_Module_Hyperspace_rch1",		-- item does not require research module
				"Vgr_MS_Module_HyperspaceInhibitor_rch1",
				"Vgr_MS_Module_CloakGenerator_rch1",
				"Vgr_MS_Module_FireControl_rch1",
				"vgr_mothership_car0_rch1_res0_hyp0",
				"vgr_mothership_car0_rch1_res0_hyp1",
				"vgr_mothership_car0_rch1_res1_hyp0",
				"vgr_mothership_car0_rch1_res1_hyp1",
				"vgr_mothership_car1_rch1_res0_hyp0",
				"vgr_mothership_car1_rch1_res0_hyp1",
				"vgr_mothership_car1_rch1_res1_hyp0",
				"vgr_mothership_car1_rch1_res1_hyp1",
				"vgr_mothership_makaan_car0_rch1_res0_hyp0",
				"vgr_mothership_makaan_car0_rch1_res0_hyp1",
				"vgr_mothership_makaan_car0_rch1_res1_hyp0",
				"vgr_mothership_makaan_car0_rch1_res1_hyp1",
				"vgr_mothership_makaan_car1_rch1_res0_hyp0",
				"vgr_mothership_makaan_car1_rch1_res0_hyp1",
				"vgr_mothership_makaan_car1_rch1_res1_hyp0",
				"vgr_mothership_makaan_car1_rch1_res1_hyp1",
				"vgr_carrier_car0_rch1_res0_hyp0",
				"vgr_carrier_car0_rch1_res0_hyp1",
				"vgr_carrier_car0_rch1_res1_hyp0",
				"vgr_carrier_car0_rch1_res1_hyp1",
				"vgr_carrier_car1_rch1_res0_hyp0",
				"vgr_carrier_car1_rch1_res0_hyp1",
				"vgr_carrier_car1_rch1_res1_hyp0",
				"vgr_carrier_car1_rch1_res1_hyp1",
				"vgr_shipyard_car0_rch1_res0_hyp0",
				"vgr_shipyard_car0_rch1_res0_hyp1",
				"vgr_shipyard_car0_rch1_res1_hyp0",
				"vgr_shipyard_car0_rch1_res1_hyp1",
				"vgr_shipyard_car1_rch1_res0_hyp0",
				"vgr_shipyard_car1_rch1_res0_hyp1",
				"vgr_shipyard_car1_rch1_res1_hyp0",
				"vgr_shipyard_car1_rch1_res1_hyp1",
				"vgr_shipyard_spg_car0_rch1_res0_hyp0",
				"vgr_shipyard_spg_car0_rch1_res0_hyp1",
				"vgr_shipyard_spg_car0_rch1_res1_hyp0",
				"vgr_shipyard_spg_car0_rch1_res1_hyp1",
				"vgr_shipyard_spg_car1_rch1_res0_hyp0",
				"vgr_shipyard_spg_car1_rch1_res0_hyp1",
				"vgr_shipyard_spg_car1_rch1_res1_hyp0",
				"vgr_shipyard_spg_car1_rch1_res1_hyp1",
			},
			research = {},
		},
		kushan_hwce =
		{
			build =
			{
				"Kus_Researchship",
				"Kus_ResearchShip_1",
				"Kus_ResearchShip_2",
				"Kus_ResearchShip_3",
				"Kus_ResearchShip_4",
				"Kus_ResearchShip_5",
			},
			research = {},
		},
		taiidan_hwce =
		{
			build =
			{
				"Tai_Researchship",
				"Tai_ResearchShip_1",
				"Tai_ResearchShip_2",
				"Tai_ResearchShip_3",
				"Tai_ResearchShip_4",
				"Tai_ResearchShip_5",
			},
			research = {},
		},
	},
	-- "Research" is set to "On".
	ResearchOn =
	{
		hiigaran_hwce =
		{
			build =
			{
				"Hgn_C_Module_Hyperspace_rch0",
				"Hgn_C_Module_HyperspaceInhibitor_rch0",
				"Hgn_C_Module_CloakGenerator_rch0",
				"Hgn_C_Module_FireControl_rch0",
				"Hgn_MS_Module_Hyperspace_rch0",
				"Hgn_MS_Module_HyperspaceInhibitor_rch0",
				"Hgn_MS_Module_CloakGenerator_rch0",
				"Hgn_MS_Module_FireControl_rch0",
				"hgn_mothership_car0_rch0_res0_hyp0",
				"hgn_mothership_car0_rch0_res0_hyp1",
				"hgn_mothership_car0_rch0_res1_hyp0",
				"hgn_mothership_car0_rch0_res1_hyp1",
				"hgn_mothership_car1_rch0_res0_hyp0",
				"hgn_mothership_car1_rch0_res0_hyp1",
				"hgn_mothership_car1_rch0_res1_hyp0",
				"hgn_mothership_car1_rch0_res1_hyp1",
				"hgn_carrier_car0_rch0_res0_hyp0",
				"hgn_carrier_car0_rch0_res0_hyp1",
				"hgn_carrier_car0_rch0_res1_hyp0",
				"hgn_carrier_car0_rch0_res1_hyp1",
				"hgn_carrier_car1_rch0_res0_hyp0",
				"hgn_carrier_car1_rch0_res0_hyp1",
				"hgn_carrier_car1_rch0_res1_hyp0",
				"hgn_carrier_car1_rch0_res1_hyp1",
				"hgn_shipyard_car0_rch0_res0_hyp0",
				"hgn_shipyard_car0_rch0_res0_hyp1",
				"hgn_shipyard_car0_rch0_res1_hyp0",
				"hgn_shipyard_car0_rch0_res1_hyp1",
				"hgn_shipyard_car1_rch0_res0_hyp0",
				"hgn_shipyard_car1_rch0_res0_hyp1",
				"hgn_shipyard_car1_rch0_res1_hyp0",
				"hgn_shipyard_car1_rch0_res1_hyp1",
				"hgn_shipyard_spg_car0_rch0_res0_hyp0",
				"hgn_shipyard_spg_car0_rch0_res0_hyp1",
				"hgn_shipyard_spg_car0_rch0_res1_hyp0",
				"hgn_shipyard_spg_car0_rch0_res1_hyp1",
				"hgn_shipyard_spg_car1_rch0_res0_hyp0",
				"hgn_shipyard_spg_car1_rch0_res0_hyp1",
				"hgn_shipyard_spg_car1_rch0_res1_hyp0",
				"hgn_shipyard_spg_car1_rch0_res1_hyp1",
				"hgn_shipyard_elohim_car0_rch0_res0_hyp0",
				"hgn_shipyard_elohim_car0_rch0_res0_hyp1",
				"hgn_shipyard_elohim_car0_rch0_res1_hyp0",
				"hgn_shipyard_elohim_car0_rch0_res1_hyp1",
				"hgn_shipyard_elohim_car1_rch0_res0_hyp0",
				"hgn_shipyard_elohim_car1_rch0_res0_hyp1",
				"hgn_shipyard_elohim_car1_rch0_res1_hyp0",
				"hgn_shipyard_elohim_car1_rch0_res1_hyp1",
			},
			research = {},
		},
		vaygr_hwce =
		{
			build =
			{
				--"Vgr_C_Module_Hyperspace_rch0",		-- does not require research module
				"Vgr_C_Module_HyperspaceInhibitor_rch0",
				"Vgr_C_Module_CloakGenerator_rch0",
				"Vgr_C_Module_FireControl_rch0",
				--"Vgr_MS_Module_Hyperspace_rch0",		-- does not require research module
				"Vgr_MS_Module_HyperspaceInhibitor_rch0",
				"Vgr_MS_Module_CloakGenerator_rch0",
				"Vgr_MS_Module_FireControl_rch0",
				"vgr_mothership_car0_rch0_res0_hyp0",
				"vgr_mothership_car0_rch0_res0_hyp1",
				"vgr_mothership_car0_rch0_res1_hyp0",
				"vgr_mothership_car0_rch0_res1_hyp1",
				"vgr_mothership_car1_rch0_res0_hyp0",
				"vgr_mothership_car1_rch0_res0_hyp1",
				"vgr_mothership_car1_rch0_res1_hyp0",
				"vgr_mothership_car1_rch0_res1_hyp1",
				"vgr_mothership_makaan_car0_rch0_res0_hyp0",
				"vgr_mothership_makaan_car0_rch0_res0_hyp1",
				"vgr_mothership_makaan_car0_rch0_res1_hyp0",
				"vgr_mothership_makaan_car0_rch0_res1_hyp1",
				"vgr_mothership_makaan_car1_rch0_res0_hyp0",
				"vgr_mothership_makaan_car1_rch0_res0_hyp1",
				"vgr_mothership_makaan_car1_rch0_res1_hyp0",
				"vgr_mothership_makaan_car1_rch0_res1_hyp1",
				"vgr_carrier_car0_rch0_res0_hyp0",
				"vgr_carrier_car0_rch0_res0_hyp1",
				"vgr_carrier_car0_rch0_res1_hyp0",
				"vgr_carrier_car0_rch0_res1_hyp1",
				"vgr_carrier_car1_rch0_res0_hyp0",
				"vgr_carrier_car1_rch0_res0_hyp1",
				"vgr_carrier_car1_rch0_res1_hyp0",
				"vgr_carrier_car1_rch0_res1_hyp1",
				"vgr_shipyard_car0_rch0_res0_hyp0",
				"vgr_shipyard_car0_rch0_res0_hyp1",
				"vgr_shipyard_car0_rch0_res1_hyp0",
				"vgr_shipyard_car0_rch0_res1_hyp1",
				"vgr_shipyard_car1_rch0_res0_hyp0",
				"vgr_shipyard_car1_rch0_res0_hyp1",
				"vgr_shipyard_car1_rch0_res1_hyp0",
				"vgr_shipyard_car1_rch0_res1_hyp1",
				"vgr_shipyard_spg_car0_rch0_res0_hyp0",
				"vgr_shipyard_spg_car0_rch0_res0_hyp1",
				"vgr_shipyard_spg_car0_rch0_res1_hyp0",
				"vgr_shipyard_spg_car0_rch0_res1_hyp1",
				"vgr_shipyard_spg_car1_rch0_res0_hyp0",
				"vgr_shipyard_spg_car1_rch0_res0_hyp1",
				"vgr_shipyard_spg_car1_rch0_res1_hyp0",
				"vgr_shipyard_spg_car1_rch0_res1_hyp1",
			},
			research = {},
		},
		kushan_hwce =
		{
			build = {},
			research = {},
		},
		taiidan_hwce =
		{
			build = {},
			research = {},
		},
	},
	-- "Hyperspace" is set to "Off".
	HyperspaceOff =
	{
		hiigaran_hwce =
		{
			build =
			{
				"Hgn_C_Module_Hyperspace_rch0",
				"Hgn_C_Module_Hyperspace_rch1",
				"Hgn_C_Module_HyperspaceInhibitor_rch0",
				"Hgn_C_Module_HyperspaceInhibitor_rch1",
				"Hgn_C_Sensors_DetectHyperspace",
				"Hgn_MS_Module_Hyperspace_rch0",
				"Hgn_MS_Module_Hyperspace_rch1",
				"Hgn_MS_Module_HyperspaceInhibitor_rch0",
				"Hgn_MS_Module_HyperspaceInhibitor_rch1",
				"Hgn_MS_Sensors_DetectHyperspace",
				"hgn_mothership_car0_rch0_res0_hyp1",
				"hgn_mothership_car0_rch0_res1_hyp1",
				"hgn_mothership_car0_rch1_res0_hyp1",
				"hgn_mothership_car0_rch1_res1_hyp1",
				"hgn_mothership_car1_rch0_res0_hyp1",
				"hgn_mothership_car1_rch0_res1_hyp1",
				"hgn_mothership_car1_rch1_res0_hyp1",
				"hgn_mothership_car1_rch1_res1_hyp1",
				"hgn_shipyard_car0_rch0_res0_hyp1",
				"hgn_shipyard_car0_rch0_res1_hyp1",
				"hgn_shipyard_car0_rch1_res0_hyp1",
				"hgn_shipyard_car0_rch1_res1_hyp1",
				"hgn_shipyard_car1_rch0_res0_hyp1",
				"hgn_shipyard_car1_rch0_res1_hyp1",
				"hgn_shipyard_car1_rch1_res0_hyp1",
				"hgn_shipyard_car1_rch1_res1_hyp1",
				"hgn_shipyard_spg_car0_rch0_res0_hyp1",
				"hgn_shipyard_spg_car0_rch0_res1_hyp1",
				"hgn_shipyard_spg_car0_rch1_res0_hyp1",
				"hgn_shipyard_spg_car0_rch1_res1_hyp1",
				"hgn_shipyard_spg_car1_rch0_res0_hyp1",
				"hgn_shipyard_spg_car1_rch0_res1_hyp1",
				"hgn_shipyard_spg_car1_rch1_res0_hyp1",
				"hgn_shipyard_spg_car1_rch1_res1_hyp1",
				"hgn_shipyard_elohim_car0_rch0_res0_hyp1",
				"hgn_shipyard_elohim_car0_rch0_res1_hyp1",
				"hgn_shipyard_elohim_car0_rch1_res0_hyp1",
				"hgn_shipyard_elohim_car0_rch1_res1_hyp1",
				"hgn_shipyard_elohim_car1_rch0_res0_hyp1",
				"hgn_shipyard_elohim_car1_rch0_res1_hyp1",
				"hgn_shipyard_elohim_car1_rch1_res0_hyp1",
				"hgn_shipyard_elohim_car1_rch1_res1_hyp1",
				"hgn_carrier_car0_rch0_res0_hyp1",
				"hgn_carrier_car0_rch0_res1_hyp1",
				"hgn_carrier_car0_rch1_res0_hyp1",
				"hgn_carrier_car0_rch1_res1_hyp1",
				"hgn_carrier_car1_rch0_res0_hyp1",
				"hgn_carrier_car1_rch0_res1_hyp1",
				"hgn_carrier_car1_rch1_res0_hyp1",
				"hgn_carrier_car1_rch1_res1_hyp1",
				"Hgn_Battlecruiser_hyp1",
				"Hgn_Destroyer_hyp1",
				"Hgn_AssaultFrigate_hyp1",
				"Hgn_TorpedoFrigate_hyp1",
				"Hgn_IonCannonFrigate_hyp1",
				"Hgn_MarineFrigate_hyp1",
				"Hgn_DefenseFieldFrigate_hyp1",
				"Hgn_ResourceController_hyp1",
			},
			research =
			{
				"HyperspaceCostUpgrade1",
			},
		},
		vaygr_hwce =
		{
			build =
			{
				"Vgr_C_Module_Hyperspace",		-- does not require research module
				"Vgr_C_Module_HyperspaceInhibitor_rch0",
				"Vgr_C_Module_HyperspaceInhibitor_rch1",
				"Vgr_C_Sensors_DetectHyperspace",
				"Vgr_MS_Module_Hyperspace",		-- does not require research module
				"Vgr_MS_Module_HyperspaceInhibitor_rch0",
				"Vgr_MS_Module_HyperspaceInhibitor_rch1",
				"Vgr_MS_Sensors_DetectHyperspace",
				"vgr_mothership_car0_rch0_res0_hyp1",
				"vgr_mothership_car0_rch0_res1_hyp1",
				"vgr_mothership_car0_rch1_res0_hyp1",
				"vgr_mothership_car0_rch1_res1_hyp1",
				"vgr_mothership_car1_rch0_res0_hyp1",
				"vgr_mothership_car1_rch0_res1_hyp1",
				"vgr_mothership_car1_rch1_res0_hyp1",
				"vgr_mothership_car1_rch1_res1_hyp1",
				"vgr_mothership_makaan_car0_rch0_res0_hyp1",
				"vgr_mothership_makaan_car0_rch0_res1_hyp1",
				"vgr_mothership_makaan_car0_rch1_res0_hyp1",
				"vgr_mothership_makaan_car0_rch1_res1_hyp1",
				"vgr_mothership_makaan_car1_rch0_res0_hyp1",
				"vgr_mothership_makaan_car1_rch0_res1_hyp1",
				"vgr_mothership_makaan_car1_rch1_res0_hyp1",
				"vgr_mothership_makaan_car1_rch1_res1_hyp1",
				"vgr_shipyard_car0_rch0_res0_hyp1",
				"vgr_shipyard_car0_rch0_res1_hyp1",
				"vgr_shipyard_car0_rch1_res0_hyp1",
				"vgr_shipyard_car0_rch1_res1_hyp1",
				"vgr_shipyard_car1_rch0_res0_hyp1",
				"vgr_shipyard_car1_rch0_res1_hyp1",
				"vgr_shipyard_car1_rch1_res0_hyp1",
				"vgr_shipyard_car1_rch1_res1_hyp1",
				"vgr_carrier_car0_rch0_res0_hyp1",
				"vgr_carrier_car0_rch0_res1_hyp1",
				"vgr_carrier_car0_rch1_res0_hyp1",
				"vgr_carrier_car0_rch1_res1_hyp1",
				"vgr_carrier_car1_rch0_res0_hyp1",
				"vgr_carrier_car1_rch0_res1_hyp1",
				"vgr_carrier_car1_rch1_res0_hyp1",
				"vgr_carrier_car1_rch1_res1_hyp1",
				"Vgr_Battlecruiser_hyp1",
				"Vgr_Destroyer_hyp1",
				"Vgr_AssaultFrigate_hyp1",
				"Vgr_HeavyMissileFrigate_hyp1",
				"Vgr_InfiltratorFrigate_hyp1",
				"Vgr_ResourceController_hyp1",
				"Vgr_HyperSpace_Platform",
			},
			research =
			{
				"HyperspaceGateTech",
			},
		},
		kushan_hwce =
		{
			build =
			{
				"kus_mothership_car0_res0_hyp1",
				"kus_mothership_car0_res1_hyp1",
				"kus_mothership_car1_res0_hyp1",
				"kus_mothership_car1_res1_hyp1",
				"kus_carrier_res0_hyp1",
				"kus_carrier_res1_hyp1",
				"kus_assaultfrigate_hyp1",
				"kus_destroyer_hyp1",
				"kus_dronefrigate_hyp1",
				"kus_heavycruiser_hyp1",
				"kus_ioncannonfrigate_hyp1",
				"kus_missiledestroyer_hyp1",
				"kus_resourcecontroller_hyp1",
				"kus_supportfrigate_hyp1",
			},
			research = {},
		},
		taiidan_hwce =
		{
			build =
			{
				"tai_mothership_car0_res0_hyp1",
				"tai_mothership_car0_res1_hyp1",
				"tai_mothership_car1_res0_hyp1",
				"tai_mothership_car1_res1_hyp1",
				"tai_carrier_res0_hyp1",
				"tai_carrier_res1_hyp1",
				"tai_assaultfrigate_hyp1",
				"tai_destroyer_hyp1",
				"tai_fieldfrigate_hyp1",
				"tai_heavycruiser_hyp1",
				"tai_ioncannonfrigate_hyp1",
				"tai_missiledestroyer_hyp1",
				"tai_resourcecontroller_hyp1",
				"tai_supportfrigate_hyp1",
			},
			research = {},
		},
	},
	-- "Hyperspace" is set to "On".
	HyperspaceOn =
	{
		hiigaran_hwce =
		{
			build =
			{
				"hgn_mothership_car0_rch0_res0_hyp0",
				"hgn_mothership_car0_rch0_res1_hyp0",
				"hgn_mothership_car0_rch1_res0_hyp0",
				"hgn_mothership_car0_rch1_res1_hyp0",
				"hgn_mothership_car1_rch0_res0_hyp0",
				"hgn_mothership_car1_rch0_res1_hyp0",
				"hgn_mothership_car1_rch1_res0_hyp0",
				"hgn_mothership_car1_rch1_res1_hyp0",
				"hgn_shipyard_car0_rch0_res0_hyp0",
				"hgn_shipyard_car0_rch0_res1_hyp0",
				"hgn_shipyard_car0_rch1_res0_hyp0",
				"hgn_shipyard_car0_rch1_res1_hyp0",
				"hgn_shipyard_car1_rch0_res0_hyp0",
				"hgn_shipyard_car1_rch0_res1_hyp0",
				"hgn_shipyard_car1_rch1_res0_hyp0",
				"hgn_shipyard_car1_rch1_res1_hyp0",
				"hgn_shipyard_spg_car0_rch0_res0_hyp0",
				"hgn_shipyard_spg_car0_rch0_res1_hyp0",
				"hgn_shipyard_spg_car0_rch1_res0_hyp0",
				"hgn_shipyard_spg_car0_rch1_res1_hyp0",
				"hgn_shipyard_spg_car1_rch0_res0_hyp0",
				"hgn_shipyard_spg_car1_rch0_res1_hyp0",
				"hgn_shipyard_spg_car1_rch1_res0_hyp0",
				"hgn_shipyard_spg_car1_rch1_res1_hyp0",
				"hgn_shipyard_elohim_car0_rch0_res0_hyp0",
				"hgn_shipyard_elohim_car0_rch0_res1_hyp0",
				"hgn_shipyard_elohim_car0_rch1_res0_hyp0",
				"hgn_shipyard_elohim_car0_rch1_res1_hyp0",
				"hgn_shipyard_elohim_car1_rch0_res0_hyp0",
				"hgn_shipyard_elohim_car1_rch0_res1_hyp0",
				"hgn_shipyard_elohim_car1_rch1_res0_hyp0",
				"hgn_shipyard_elohim_car1_rch1_res1_hyp0",
				"hgn_carrier_car0_rch0_res0_hyp0",
				"hgn_carrier_car0_rch0_res1_hyp0",
				"hgn_carrier_car0_rch1_res0_hyp0",
				"hgn_carrier_car0_rch1_res1_hyp0",
				"hgn_carrier_car1_rch0_res0_hyp0",
				"hgn_carrier_car1_rch0_res1_hyp0",
				"hgn_carrier_car1_rch1_res0_hyp0",
				"hgn_carrier_car1_rch1_res1_hyp0",
				"Hgn_Battlecruiser_hyp0",
				"Hgn_Destroyer_hyp0",
				"Hgn_AssaultFrigate_hyp0",
				"Hgn_TorpedoFrigate_hyp0",
				"Hgn_IonCannonFrigate_hyp0",
				"Hgn_MarineFrigate_hyp0",
				"Hgn_DefenseFieldFrigate_hyp0",
				"Hgn_ResourceController_hyp0",
			},
			research = {},
		},
		vaygr_hwce =
		{
			build =
			{
				"vgr_mothership_car0_rch0_res0_hyp0",
				"vgr_mothership_car0_rch0_res1_hyp0",
				"vgr_mothership_car0_rch1_res0_hyp0",
				"vgr_mothership_car0_rch1_res1_hyp0",
				"vgr_mothership_car1_rch0_res0_hyp0",
				"vgr_mothership_car1_rch0_res1_hyp0",
				"vgr_mothership_car1_rch1_res0_hyp0",
				"vgr_mothership_car1_rch1_res1_hyp0",
				"vgr_mothership_makaan_car0_rch0_res0_hyp0",
				"vgr_mothership_makaan_car0_rch0_res1_hyp0",
				"vgr_mothership_makaan_car0_rch1_res0_hyp0",
				"vgr_mothership_makaan_car0_rch1_res1_hyp0",
				"vgr_mothership_makaan_car1_rch0_res0_hyp0",
				"vgr_mothership_makaan_car1_rch0_res1_hyp0",
				"vgr_mothership_makaan_car1_rch1_res0_hyp0",
				"vgr_mothership_makaan_car1_rch1_res1_hyp0",
				"vgr_shipyard_car0_rch0_res0_hyp0",
				"vgr_shipyard_car0_rch0_res1_hyp0",
				"vgr_shipyard_car0_rch1_res0_hyp0",
				"vgr_shipyard_car0_rch1_res1_hyp0",
				"vgr_shipyard_car1_rch0_res0_hyp0",
				"vgr_shipyard_car1_rch0_res1_hyp0",
				"vgr_shipyard_car1_rch1_res0_hyp0",
				"vgr_shipyard_car1_rch1_res1_hyp0",
				"vgr_carrier_car0_rch0_res0_hyp0",
				"vgr_carrier_car0_rch0_res1_hyp0",
				"vgr_carrier_car0_rch1_res0_hyp0",
				"vgr_carrier_car0_rch1_res1_hyp0",
				"vgr_carrier_car1_rch0_res0_hyp0",
				"vgr_carrier_car1_rch0_res1_hyp0",
				"vgr_carrier_car1_rch1_res0_hyp0",
				"vgr_carrier_car1_rch1_res1_hyp0",
				"Vgr_Battlecruiser_hyp0",
				"Vgr_Destroyer_hyp0",
				"Vgr_AssaultFrigate_hyp0",
				"Vgr_HeavyMissileFrigate_hyp0",
				"Vgr_InfiltratorFrigate_hyp0",
				"Vgr_ResourceController_hyp0",
			},
			research = {},
		},
		kushan_hwce =
		{
			build =
			{
				"kus_mothership_car0_res0_hyp0",
				"kus_mothership_car0_res1_hyp0",
				"kus_mothership_car1_res0_hyp0",
				"kus_mothership_car1_res1_hyp0",
				"kus_carrier_res0_hyp0",
				"kus_carrier_res1_hyp0",
				"kus_assaultfrigate_hyp0",
				"kus_destroyer_hyp0",
				"kus_dronefrigate_hyp0",
				"kus_heavycruiser_hyp0",
				"kus_ioncannonfrigate_hyp0",
				"kus_missiledestroyer_hyp0",
				"kus_resourcecontroller_hyp0",
				"kus_supportfrigate_hyp0",
			},
			research = {},
		},
		taiidan_hwce =
		{
			build =
			{
				"tai_mothership_car0_res0_hyp0",
				"tai_mothership_car0_res1_hyp0",
				"tai_mothership_car1_res0_hyp0",
				"tai_mothership_car1_res1_hyp0",
				"tai_carrier_res0_hyp0",
				"tai_carrier_res1_hyp0",
				"tai_assaultfrigate_hyp0",
				"tai_destroyer_hyp0",
				"tai_fieldfrigate_hyp0",
				"tai_heavycruiser_hyp0",
				"tai_ioncannonfrigate_hyp0",
				"tai_missiledestroyer_hyp0",
				"tai_resourcecontroller_hyp0",
				"tai_supportfrigate_hyp0",
			},
			research = {},
		},
	},
	-- resourcing is disabled
	ResourceOff =
	{
		hiigaran_hwce =
		{
			build =
			{
				"Hgn_ResourceCollector",
				"Hgn_ResourceController_hyp0",
				"Hgn_ResourceController_hyp1",
				"hgn_mothership_car0_rch0_res1_hyp0",
				"hgn_mothership_car0_rch1_res1_hyp0",
				"hgn_mothership_car1_rch0_res1_hyp0",
				"hgn_mothership_car1_rch1_res1_hyp0",
				"hgn_mothership_car0_rch0_res1_hyp1",
				"hgn_mothership_car0_rch1_res1_hyp1",
				"hgn_mothership_car1_rch0_res1_hyp1",
				"hgn_mothership_car1_rch1_res1_hyp1",
				"hgn_shipyard_car0_rch0_res1_hyp0",
				"hgn_shipyard_car0_rch1_res1_hyp0",
				"hgn_shipyard_car1_rch0_res1_hyp0",
				"hgn_shipyard_car1_rch1_res1_hyp0",
				"hgn_shipyard_car0_rch0_res1_hyp1",
				"hgn_shipyard_car0_rch1_res1_hyp1",
				"hgn_shipyard_car1_rch0_res1_hyp1",
				"hgn_shipyard_car1_rch1_res1_hyp1",
				"hgn_shipyard_spg_car0_rch0_res1_hyp0",
				"hgn_shipyard_spg_car0_rch1_res1_hyp0",
				"hgn_shipyard_spg_car1_rch0_res1_hyp0",
				"hgn_shipyard_spg_car1_rch1_res1_hyp0",
				"hgn_shipyard_spg_car0_rch0_res1_hyp1",
				"hgn_shipyard_spg_car0_rch1_res1_hyp1",
				"hgn_shipyard_spg_car1_rch0_res1_hyp1",
				"hgn_shipyard_spg_car1_rch1_res1_hyp1",
				"hgn_shipyard_elohim_car0_rch0_res1_hyp0",
				"hgn_shipyard_elohim_car0_rch1_res1_hyp0",
				"hgn_shipyard_elohim_car1_rch0_res1_hyp0",
				"hgn_shipyard_elohim_car1_rch1_res1_hyp0",
				"hgn_shipyard_elohim_car0_rch0_res1_hyp1",
				"hgn_shipyard_elohim_car0_rch1_res1_hyp1",
				"hgn_shipyard_elohim_car1_rch0_res1_hyp1",
				"hgn_shipyard_elohim_car1_rch1_res1_hyp1",
				"hgn_carrier_car0_rch0_res1_hyp0",
				"hgn_carrier_car0_rch1_res1_hyp0",
				"hgn_carrier_car1_rch0_res1_hyp0",
				"hgn_carrier_car1_rch1_res1_hyp0",
				"hgn_carrier_car0_rch0_res1_hyp1",
				"hgn_carrier_car0_rch1_res1_hyp1",
				"hgn_carrier_car1_rch0_res1_hyp1",
				"hgn_carrier_car1_rch1_res1_hyp1",
			},
			research =
			{
				"RepairAbility",
				"ResourceCollectorHealthUpgrade1",
				"ResourceControllerHealthUpgrade1",
			},
		},
		vaygr_hwce =
		{
			build =
			{
				"Vgr_ResourceCollector",
				"Vgr_ResourceController_hyp0",
				"Vgr_ResourceController_hyp1",
				"vgr_mothership_car0_rch0_res1_hyp0",
				"vgr_mothership_car0_rch0_res1_hyp0",
				"vgr_mothership_car0_rch1_res1_hyp0",
				"vgr_mothership_car0_rch1_res1_hyp0",
				"vgr_mothership_car1_rch0_res1_hyp1",
				"vgr_mothership_car1_rch0_res1_hyp1",
				"vgr_mothership_car1_rch1_res1_hyp1",
				"vgr_mothership_car1_rch1_res1_hyp1",
				"vgr_mothership_makaan_car0_rch0_res1_hyp0",
				"vgr_mothership_makaan_car0_rch0_res1_hyp0",
				"vgr_mothership_makaan_car0_rch1_res1_hyp0",
				"vgr_mothership_makaan_car0_rch1_res1_hyp0",
				"vgr_mothership_makaan_car1_rch0_res1_hyp1",
				"vgr_mothership_makaan_car1_rch0_res1_hyp1",
				"vgr_mothership_makaan_car1_rch1_res1_hyp1",
				"vgr_mothership_makaan_car1_rch1_res1_hyp1",
				"vgr_shipyard_car0_rch0_res1_hyp0",
				"vgr_shipyard_car0_rch0_res1_hyp0",
				"vgr_shipyard_car0_rch1_res1_hyp0",
				"vgr_shipyard_car0_rch1_res1_hyp0",
				"vgr_shipyard_car1_rch0_res1_hyp1",
				"vgr_shipyard_car1_rch0_res1_hyp1",
				"vgr_shipyard_car1_rch1_res1_hyp1",
				"vgr_shipyard_car1_rch1_res1_hyp1",
				"vgr_carrier_car0_rch0_res1_hyp0",
				"vgr_carrier_car0_rch0_res1_hyp0",
				"vgr_carrier_car0_rch1_res1_hyp0",
				"vgr_carrier_car0_rch1_res1_hyp0",
				"vgr_carrier_car1_rch0_res1_hyp1",
				"vgr_carrier_car1_rch0_res1_hyp1",
				"vgr_carrier_car1_rch1_res1_hyp1",
				"vgr_carrier_car1_rch1_res1_hyp1",
			},
			research =
			{
				"RepairAbility",
				"UtilityHealthUpgrade1",
			},
		},
		kushan_hwce =
		{
			build =
			{
				"Kus_ResourceCollector",
				"Kus_ResourceController",
				"kus_mothership_car0_res1_hyp0",
				"kus_mothership_car1_res1_hyp0",
				"kus_mothership_car0_res1_hyp1",
				"kus_mothership_car1_res1_hyp1",
				"kus_carrier_res1_hyp0",
				"kus_carrier_res1_hyp1",
			},
			research =
			{
				"ResourceCollectionRateExpert",
			},
		},
		taiidan_hwce =
		{
			build =
			{
				"Tai_ResourceCollector",
				"Tai_ResourceController",
				"tai_mothership_car0_res1_hyp0",
				"tai_mothership_car1_res1_hyp0",
				"tai_mothership_car0_res1_hyp1",
				"tai_mothership_car1_res1_hyp1",
				"tai_carrier_res1_hyp0",
				"tai_carrier_res1_hyp1",
			},
			research =
			{
				"ResourceCollectionRateExpert",
			},
		},
	},
	-- resourcing is enabled
	ResourceOn =
	{
		hiigaran_hwce =
		{
			build =
			{
				"hgn_mothership_car0_rch0_res0_hyp0",
				"hgn_mothership_car0_rch1_res0_hyp0",
				"hgn_mothership_car1_rch0_res0_hyp0",
				"hgn_mothership_car1_rch1_res0_hyp0",
				"hgn_mothership_car0_rch0_res0_hyp1",
				"hgn_mothership_car0_rch1_res0_hyp1",
				"hgn_mothership_car1_rch0_res0_hyp1",
				"hgn_mothership_car1_rch1_res0_hyp1",
				"hgn_shipyard_car0_rch0_res0_hyp0",
				"hgn_shipyard_car0_rch1_res0_hyp0",
				"hgn_shipyard_car1_rch0_res0_hyp0",
				"hgn_shipyard_car1_rch1_res0_hyp0",
				"hgn_shipyard_car0_rch0_res0_hyp1",
				"hgn_shipyard_car0_rch1_res0_hyp1",
				"hgn_shipyard_car1_rch0_res0_hyp1",
				"hgn_shipyard_car1_rch1_res0_hyp1",
				"hgn_shipyard_spg_car0_rch0_res0_hyp0",
				"hgn_shipyard_spg_car0_rch1_res0_hyp0",
				"hgn_shipyard_spg_car1_rch0_res0_hyp0",
				"hgn_shipyard_spg_car1_rch1_res0_hyp0",
				"hgn_shipyard_spg_car0_rch0_res0_hyp1",
				"hgn_shipyard_spg_car0_rch1_res0_hyp1",
				"hgn_shipyard_spg_car1_rch0_res0_hyp1",
				"hgn_shipyard_spg_car1_rch1_res0_hyp1",
				"hgn_shipyard_elohim_car0_rch0_res0_hyp0",
				"hgn_shipyard_elohim_car0_rch1_res0_hyp0",
				"hgn_shipyard_elohim_car1_rch0_res0_hyp0",
				"hgn_shipyard_elohim_car1_rch1_res0_hyp0",
				"hgn_shipyard_elohim_car0_rch0_res0_hyp1",
				"hgn_shipyard_elohim_car0_rch1_res0_hyp1",
				"hgn_shipyard_elohim_car1_rch0_res0_hyp1",
				"hgn_shipyard_elohim_car1_rch1_res0_hyp1",
				"hgn_carrier_car0_rch0_res0_hyp0",
				"hgn_carrier_car0_rch1_res0_hyp0",
				"hgn_carrier_car1_rch0_res0_hyp0",
				"hgn_carrier_car1_rch1_res0_hyp0",
				"hgn_carrier_car0_rch0_res0_hyp1",
				"hgn_carrier_car0_rch1_res0_hyp1",
				"hgn_carrier_car1_rch0_res0_hyp1",
				"hgn_carrier_car1_rch1_res0_hyp1",
			},
			research = {},
		},
		vaygr_hwce =
		{
			build =
			{
				"vgr_mothership_car0_rch0_res0_hyp0",
				"vgr_mothership_car0_rch0_res0_hyp0",
				"vgr_mothership_car0_rch1_res0_hyp0",
				"vgr_mothership_car0_rch1_res0_hyp0",
				"vgr_mothership_car1_rch0_res0_hyp1",
				"vgr_mothership_car1_rch0_res0_hyp1",
				"vgr_mothership_car1_rch1_res0_hyp1",
				"vgr_mothership_car1_rch1_res0_hyp1",
				"vgr_mothership_makaan_car0_rch0_res0_hyp0",
				"vgr_mothership_makaan_car0_rch0_res0_hyp0",
				"vgr_mothership_makaan_car0_rch1_res0_hyp0",
				"vgr_mothership_makaan_car0_rch1_res0_hyp0",
				"vgr_mothership_makaan_car1_rch0_res0_hyp1",
				"vgr_mothership_makaan_car1_rch0_res0_hyp1",
				"vgr_mothership_makaan_car1_rch1_res0_hyp1",
				"vgr_mothership_makaan_car1_rch1_res0_hyp1",
				"vgr_shipyard_car0_rch0_res0_hyp0",
				"vgr_shipyard_car0_rch0_res0_hyp0",
				"vgr_shipyard_car0_rch1_res0_hyp0",
				"vgr_shipyard_car0_rch1_res0_hyp0",
				"vgr_shipyard_car1_rch0_res0_hyp1",
				"vgr_shipyard_car1_rch0_res0_hyp1",
				"vgr_shipyard_car1_rch1_res0_hyp1",
				"vgr_shipyard_car1_rch1_res0_hyp1",
				"vgr_carrier_car0_rch0_res0_hyp0",
				"vgr_carrier_car0_rch0_res0_hyp0",
				"vgr_carrier_car0_rch1_res0_hyp0",
				"vgr_carrier_car0_rch1_res0_hyp0",
				"vgr_carrier_car1_rch0_res0_hyp1",
				"vgr_carrier_car1_rch0_res0_hyp1",
				"vgr_carrier_car1_rch1_res0_hyp1",
				"vgr_carrier_car1_rch1_res0_hyp1",
			},
			research = {},
		},
		kushan_hwce =
		{
			build =
			{
				"kus_mothership_car0_res0_hyp0",
				"kus_mothership_car1_res0_hyp0",
				"kus_mothership_car0_res0_hyp1",
				"kus_mothership_car1_res0_hyp1",
				"kus_carrier_res0_hyp0",
				"kus_carrier_res0_hyp1",
			},
			research = {},
		},
		taiidan_hwce =
		{
			build =
			{
				"tai_mothership_car0_res0_hyp0",
				"tai_mothership_car1_res0_hyp0",
				"tai_mothership_car0_res0_hyp1",
				"tai_mothership_car1_res0_hyp1",
				"tai_carrier_res0_hyp0",
				"tai_carrier_res0_hyp1",
			},
			research = {},
		},
	},
	-- changes are needed based on whether the 'player' is human or AI
	PlayerHuman =
	{
		hiigaran_hwce =
		{
			build = {},
			research =
			{
				"cpuplayers_defensive",
				"cpuplayers_aggressive",
				"cpuplayers_dynamic",
				"cpuplayers_norushtime5",
				"cpuplayers_norushtime10",
				"cpuplayers_norushtime15",
				"AllShipBuildSpeed",
				"AllShipBuildSpeedHard",
				"AllShipBuildSpeedExpert",
				"ResourceCollectionRateHard",
				"ResourceCollectionRateExpert",
			},
		},
		vaygr_hwce =
		{
			build = {},
			research =
			{
				"cpuplayers_defensive",
				"cpuplayers_aggressive",
				"cpuplayers_dynamic",
				"cpuplayers_norushtime5",
				"cpuplayers_norushtime10",
				"cpuplayers_norushtime15",
				"AllShipBuildSpeed",
				"AllShipBuildSpeedHard",
				"AllShipBuildSpeedExpert",
				"ResourceCollectionRateHard",
				"ResourceCollectionRateExpert",
			},
		},
		kushan_hwce =
		{
			build = {},
			research =
			{
				"CPUPlayers_Defensive",
				"CPUPlayers_Aggressive",
				"CPUPlayers_Dynamic",
				"CPUPlayers_Norushtime5",
				"CPUPlayers_Norushtime10",
				"CPUPlayers_Norushtime15",
				"AllShipBuildSpeed",
				"AllShipBuildSpeedHard",
				"AllShipBuildSpeedExpert",
				"ResourceCollectionRateHard",
				"ResourceCollectionRateExpert",
				"MissileDestroyerVolley",
				"HeavyCorvetteAttackBurst",
			},
		},
		taiidan_hwce =
		{
			build = {},
			research =
			{
				"CPUPlayers_Defensive",
				"CPUPlayers_Aggressive",
				"CPUPlayers_Dynamic",
				"CPUPlayers_Norushtime5",
				"CPUPlayers_Norushtime10",
				"CPUPlayers_Norushtime15",
				"AllShipBuildSpeed",
				"AllShipBuildSpeedHard",
				"AllShipBuildSpeedExpert",
				"ResourceCollectionRateHard",
				"ResourceCollectionRateExpert",
				"MissileDestroyerVolley",
				"HeavyCorvetteAttackBurst",
			},
		},
	},
	PlayerComputer =
	{
		hiigaran_hwce =
		{
			build = {},
			research = {}
		},
		vaygr_hwce =
		{
			build = {},
			research = {}
		},
		kushan_hwce =
		{
			build = {},
			research = {}
		},
		taiidan_hwce =
		{
			build = {},
			research = {}
		},
	},
	Misc =
	{
		hiigaran_hwce =
		{
			build =
			{
				"Hgn_Shipyard_SPG",
				"Hgn_MS_Production_CorvetteMover",
				"Kpr_Mover",
			},
			research =
			{
				"SGMCapitalHealth",
				"SGMCarrierHealth",
				"SGMFrigateHealth",
				"SGMShipyardHealth",
			},
		},
		vaygr_hwce =
		{
			build =
			{
				"Vgr_PlanetKillerMissile",
			},
			research =
			{
				"SGMCapitalHealth",
				"SGMCarrierHealth",
				"SGMFrigateHealth",
				"SGMShipyardHealth",
			},
		},
		kushan_hwce =
		{
			build =
			{
				"kus_drone0",
				"kus_drone1",
				"kus_drone2",
				"kus_drone3",
				"kus_drone4",
				"kus_drone5",
				"kus_drone6",
				"kus_drone7",
				"kus_drone8",
				"kus_drone9",
				"kus_drone10",
				"kus_drone11",
				"kus_drone12",
				"kus_drone13",
			},
			research =
			{
				"SGMCapitalHealth",
				"SGMFrigateHealth",
				"SGMGravWellHealth",
			},
		},
		taiidan_hwce =
		{
			build = {},
			research =
			{
				"SGMCapitalHealth",
				"SGMFrigateHealth",
				"SGMGravWellHealth",
			},
		},
	},
	NonVanilla =
	{
		hiigaran_hwce =
		{
			build =
			{
			},
			research =
			{
			},
		},
		vaygr_hwce =
		{
			build =
			{
				
			},
			research =
			{
			},
		},
		kushan_hwce =
		{
			build =
			{
			},
			research =
			{
			},
		},
		taiidan_hwce =
		{
			build =
			{
			},
			research =
			{
			},
		},
	},
	-- these unsuffixed ships should not normally appear in the game since there are mod-specific suffixed versions that are meant to take precedence
	-- this list is based on the Players Patch 2.3
	Vanilla =
	{
		hiigaran_hwce =
		{
			build =
			{
				"Hgn_C_Production_Fighter",
				"Hgn_MS_Production_Fighter",
				"Hgn_C_Production_Corvette",
				"Hgn_MS_Production_Corvette",
				"Hgn_C_Production_Frigate",
				"Hgn_MS_Production_Frigate",
				"Hgn_MS_Production_CapShip",
				"Hgn_SY_Production_CapShip",
				"Hgn_C_Module_PlatformControl",
				"Hgn_MS_Module_PlatformControl",
				"Hgn_C_Module_Research",
				"Hgn_MS_Module_Research",
				"Hgn_C_Module_ResearchAdvanced",
				"Hgn_MS_Module_ResearchAdvanced",
				"Hgn_C_Module_Hyperspace",
				"Hgn_MS_Module_Hyperspace",
				"Hgn_C_Module_HyperspaceInhibitor",
				"Hgn_MS_Module_HyperspaceInhibitor",
				"Hgn_C_Module_CloakGenerator",
				"Hgn_MS_Module_CloakGenerator",
				"Hgn_C_Module_FireControl",
				"Hgn_MS_Module_FireControl",
				"Hgn_C_Sensors_DetectHyperspace",
				"Hgn_MS_Sensors_DetectHyperspace",
				"Hgn_C_Sensors_AdvancedArray",
				"Hgn_MS_Sensors_AdvancedArray",
				"Hgn_C_Sensors_DetectCloaked",
				"Hgn_MS_Sensors_DetectCloaked",
				"Kpr_Mover",
				"Hgn_MS_Production_CorvetteMover",
				"Hgn_Scout",
				"Hgn_Interceptor",
				"Hgn_AttackBomber",
				"Hgn_AssaultCorvette",
				"Hgn_PulsarCorvette",
				"Hgn_MinelayerCorvette",
				"Hgn_AssaultFrigate",
				"Hgn_TorpedoFrigate",
				"Hgn_IonCannonFrigate",
				"Hgn_MarineFrigate",
				"Hgn_DefenseFieldFrigate",
				"Hgn_Carrier",
				"Hgn_Destroyer",
				"Hgn_Shipyard",
				"Hgn_Battlecruiser",
				"Hgn_GunTurret",
				"Hgn_IonTurret",
				"Hgn_ResourceCollector",
				"Hgn_ResourceController",
				"Hgn_Probe",
				"Hgn_ProximitySensor",
				"Hgn_ECMProbe",
				"Hgn_Shipyard_SPG",
			},
			research =
			{
				"RepairAbility",
				"ScoutPingAbility",
				"ImprovedTorpedo",
				"AttackBomberImprovedBombs",
				"ScoutEMPAbility",
				"DefenseFieldFrigateShield",
				"cpuplayers_defensive",
				"cpuplayers_aggressive",
				"cpuplayers_dynamic",
				"cpuplayers_norushtime5",
				"cpuplayers_norushtime10",
				"cpuplayers_norushtime15",
				"AllShipBuildSpeed",
				"AllShipBuildSpeedHard",
				"AllShipBuildSpeedExpert",
				"ResourceCollectionRateHard",
				"ResourceCollectionRateExpert",
				"WeaponDamageUpgrade125",
				"WeaponDamageUpgrade150",
				"WeaponDamageUpgrade175",
				"WeaponDamageUpgrade200",
				"BattlecruiserHealthUpgrade1",
				"BattlecruiserMAXSPEEDUpgrade1",
				"CarrierHealthUpgrade1",
				"CarrierMAXSPEEDUpgrade1",
				"CarrierBUILDSPEEDUpgrade1",
				"AssaultCorvetteHealthUpgrade1",
				"PulsarCorvetteHealthUpgrade1",
				"InstaAdvancedFrigateTech",
				"GraviticAttractionMines",
				"PlatformIonWeapons",
				"DestroyerTech",
				"BattlecruiserIonWeapons",
				"ECMProbe",
				"SensDisProbe",
				"HyperspaceDamageReductionUpgrade",
				"DestroyerHealthUpgrade1",
				"DestroyerMAXSPEEDUpgrade1",
				"InterceptorMAXSPEEDUpgrade1",
				"AttackBomberMAXSPEEDUpgrade1",
				"MothershipHealthUpgrade1",
				"MothershipMAXSPEEDUpgrade1",
				"MothershipBUILDSPEEDUpgrade1",
				"GunTurretHealthUpgrade1",
				"IonTurretHealthUpgrade1",
				"ShipyardHealthUpgrade1",
				"ShipyardMAXSPEEDUpgrade1",
				"ShipyardBUILDSPEEDUpgrade1",
				"ResourceCollectorHealthUpgrade1",
				"ResourceControllerHealthUpgrade1",
				"AssaultCorvetteMAXSPEEDUpgrade1",
				"PulsarCorvetteMAXSPEEDUpgrade1",
				"SGMCapitalHealth",
				"SGMCarrierHealth",
				"SGMFrigateHealth",
				"SGMShipyardHealth",
				"TorpedoFrigateHealthUpgrade1",
				"IonCannonFrigateHealthUpgrade1",
				"AssaultFrigateHealthUpgrade1",
				"TorpedoFrigateMAXSPEEDUpgrade1",
				"IonCannonFrigateMAXSPEEDUpgrade1",
				"AssaultFrigateMAXSPEEDUpgrade1",
				"HyperspaceCostUpgrade1",
				"HyperspaceCostUpgrade2",
			}
		},
		vaygr_hwce =
		{
			build =
			{
				"Vgr_C_Production_Fighter",
				"Vgr_MS_Production_Fighter",
				"Vgr_C_Production_Corvette",
				"Vgr_MS_Production_Corvette",
				"Vgr_C_Production_Frigate",
				"Vgr_MS_Production_Frigate",
				"Vgr_C_Module_PlatformControl",
				"Vgr_MS_Module_PlatformControl",
				"Vgr_MS_Production_CapShip",
				"Vgr_SY_Production_CapShip",
				"Vgr_C_Module_Research",
				"Vgr_MS_Module_Research",
				"Vgr_C_Module_CloakGenerator",
				"Vgr_MS_Module_CloakGenerator",
				"Vgr_C_Module_HyperspaceInhibitor",
				"Vgr_MS_Module_HyperspaceInhibitor",
				"Vgr_C_Module_FireControl",
				"Vgr_MS_Module_FireControl",
				"Vgr_C_Module_Hyperspace",
				"Vgr_MS_Module_Hyperspace",
				"Vgr_C_Sensors_AdvancedArray",
				"Vgr_MS_Sensors_AdvancedArray",
				"Vgr_C_Sensors_DetectHyperspace",
				"Vgr_MS_Sensors_DetectHyperspace",
				"Vgr_Scout",
				"Vgr_Interceptor",
				"Vgr_Bomber",
				"Vgr_LanceFighter",
				"Vgr_MissileCorvette",
				"Vgr_LaserCorvette",
				"Vgr_CommandCorvette",
				"Vgr_MinelayerCorvette",
				"Vgr_AssaultFrigate",
				"Vgr_HeavyMissileFrigate",
				"Vgr_InfiltratorFrigate",
				"Vgr_Destroyer",
				"Vgr_Carrier",
				"Vgr_ShipYard",
				"Vgr_BattleCruiser",
				"Vgr_WeaponPlatform_gun",
				"Vgr_WeaponPlatform_missile",
				"Vgr_ResourceCollector",
				"Vgr_ResourceController",
				"Vgr_HyperSpace_Platform",
				"Vgr_Probe",
				"Vgr_Probe_Prox",
				"Vgr_Probe_ECM",
				"Vgr_PlanetKillerMissile",
			},
			research =
			{
				"RepairAbility",
				"ScoutEMPAbility",
				"BomberImprovedBombs",
				"cpuplayers_defensive",
				"cpuplayers_aggressive",
				"cpuplayers_dynamic",
				"cpuplayers_norushtime5",
				"cpuplayers_norushtime10",
				"cpuplayers_norushtime15",
				"AllShipBuildSpeed",
				"AllShipBuildSpeedHard",
				"AllShipBuildSpeedExpert",
				"ResourceCollectionRateHard",
				"ResourceCollectionRateExpert",
				"WeaponDamageUpgrade125",
				"WeaponDamageUpgrade150",
				"WeaponDamageUpgrade175",
				"WeaponDamageUpgrade200",
				"SuperCapHealthUpgrade1",
				"SuperCapSpeedUpgrade1",
				"MothershipBUILDSPEEDUpgrade1",
				"CarrierBUILDSPEEDUpgrade1",
				"ShipyardBUILDSPEEDUpgrade1",
				"CorvetteHealthUpgrade1",
				"CorvetteTech",
				"FrigateTech",
				"ProbeSensorDisruption",
				"ProbeProxSensor",
				"LanceBeams",
				"PlasmaBombs",
				"CorvetteGraviticAttraction",
				"CorvetteLaser",
				"CorvetteCommand",
				"PlatformHeavyMissiles",
				"FrigateAssault",
				"FrigateInfiltrationTech",
				"BattlecruiserIonWeapons",
				"DestroyerGuns",
				"HyperspaceGateTech",
				"HyperspaceDamageReductionUpgrade",
				"SGMCapitalHealth",
				"SGMFrigateHealth",
				"SGMCarrierHealth",
				"SGMShipyardHealth",
				"PlatformHealthUpgrade1",
				"WeakVgrHeavyMissiles",
				"HyperspaceRecoveryTimeUpgradeSPGAME",
				"VaygrCarrierHealthRegenDowngrade",
				"HyperspaceTransitionTimeUpgradeSPGAME",
				"SuperCapHealthUpgradeSPGAME",
				"SuperCapDamageAppliedSPGAME",
				"ShipyardSpeedDowngradeSPGAME",
				"VaygrFrigateHealthUpgradeSPGAME",
				"VaygrFrigateHealthRegenDowngradeSPGAME",
				"CorvetteHealthUpgradeSPGAME",
				"ExtraStrongVgrHeavyMissilesSPGAME",
				"VaygrCaptureHack",
				"VaygrReduceCaptureHack",
				"VaygrRadiationImmunityHack",
				"VaygrCarrierHealthUpgrade",
				"MakaanCarrierHealth",
				"MakaanDestroyerHealth",
				"MakaanShipyardHealth",
				"MakaanBattleCruiserHealth",
				"MakaanFrigateHealth",
				"MakaanCorvetteHealth",
				"MakaanFighterHealth",
				"MakaanUtilityHealth",
				"MakaanPlatformHealth",
				"StrongerGunPlats",
				"StrongerMissilePlats",
				"UtilityHealthUpgrade1",
				"CorvetteSpeedUpgrade1",
				"FighterspeedUpgrade1",
				"FrigateHealthUpgrade1",
				"FrigateSpeedUpgrade1",
			}
		},
		kushan_hwce =
		{
			build =
			{
				"hw1_production_fighter",
				"hw1_production_corvette",
				"hw1_production_frigate",
				"hw1_production_capital",
				"Kus_Scout",
				"Kus_Interceptor",
				"Kus_Defender",
				"Kus_AttackBomber",
				"Kus_CloakedFighter",
				"Kus_RepairCorvette",
				"Kus_SalvageCorvette",
				"Kus_LightCorvette",
				"Kus_HeavyCorvette",
				"Kus_MultiGunCorvette",
				"Kus_MinelayerCorvette",
				"Kus_AssaultFrigate",
				"Kus_IonCannonFrigate",
				"Kus_SupportFrigate",
				"Kus_DroneFrigate",
				"Kus_Destroyer",
				"Kus_MissileDestroyer",
				"Kus_Carrier",
				"Kus_HeavyCruiser",
				"Kus_ResourceCollector",
				"Kus_ResourceController",
				"Kus_ResearchShip",
				"Kus_ResearchShip_1",
				"Kus_ResearchShip_2",
				"Kus_ResearchShip_3",
				"Kus_ResearchShip_4",
				"Kus_ResearchShip_5",
				"Kus_Probe",
				"Kus_ProximitySensor",
				"Kus_SensorArray",
				"Kus_GravWellGenerator",
				"Kus_CloakGenerator",
				"Kus_Drone0",
				"Kus_Drone1",
				"Kus_Drone2",
				"Kus_Drone3",
				"Kus_Drone4",
				"Kus_Drone5",
				"Kus_Drone6",
				"Kus_Drone7",
				"Kus_Drone8",
				"Kus_Drone9",
				"Kus_Drone10",
				"Kus_Drone11",
				"Kus_Drone12",
				"Kus_Drone13",
			},
			research =
			{
				"cpuplayers_defensive",
				"cpuplayers_aggressive",
				"cpuplayers_dynamic",
				"cpuplayers_norushtime5",
				"cpuplayers_norushtime10",
				"cpuplayers_norushtime15",
				"AllShipBuildSpeed",
				"AllShipBuildSpeedHard",
				"AllShipBuildSpeedExpert",
				"ResourceCollectionRateHard",
				"ResourceCollectionRateExpert",
				"WeaponDamageUpgrade125",
				"WeaponDamageUpgrade150",
				"WeaponDamageUpgrade175",
				"WeaponDamageUpgrade200",
				"CorvetteDrive",
				"CorvetteChassis",
				"HeavyCorvetteUpgrade",
				"FastTrackingTurrets",
				"MinelayingTech",
				"ProximitySensor",
				"SensorArray",
				"GravityGenerator",
				"CloakGenerator",
				"HyperspaceDamageReductionUpgrade",
				"HyperspaceDamageReductionUpgradeHC",
				"FighterDrive",
				"FighterChassis",
				"DefenderSubSystems",
				"PlasmaBombLauncher",
				"CloakedFighter",
				"CapitalShipDrive",
				"CapitalShipChassis",
				"IonCannons",
				"DroneTechnology",
				"SuperCapitalShipDrive",
				"GuidedMissiles",
				"SuperHeavyChassis",
				"HeavyGuns",
				"SGMCapitalHealth",
				"SGMFrigateHealth",
				"SGMGravWellHealth",
			},
		},
		taiidan_hwce =
		{
			build =
			{
				"hw1_production_fighter",
				"hw1_production_corvette",
				"hw1_production_frigate",
				"hw1_production_capital",
				"Tai_Scout",
				"Tai_Interceptor",
				"Tai_Defender",
				"Tai_AttackBomber",
				"Tai_DefenseFighter",
				"Tai_RepairCorvette",
				"Tai_SalvageCorvette",
				"Tai_LightCorvette",
				"Tai_HeavyCorvette",
				"Tai_MultiGunCorvette",
				"Tai_MinelayerCorvette",
				"Tai_AssaultFrigate",
				"Tai_IonCannonFrigate",
				"Tai_SupportFrigate",
				"Tai_FieldFrigate",
				"Tai_Destroyer",
				"Tai_MissileDestroyer",
				"Tai_Carrier",
				"Tai_HeavyCruiser",
				"Tai_ResourceCollector",
				"Tai_ResourceController",
				"Tai_ResearchShip",
				"Tai_ResearchShip_1",
				"Tai_ResearchShip_2",
				"Tai_ResearchShip_3",
				"Tai_ResearchShip_4",
				"Tai_ResearchShip_5",
				"Tai_Probe",
				"Tai_ProximitySensor",
				"Tai_SensorArray",
				"Tai_GravWellGenerator",
				"Tai_CloakGenerator",
			},
			research =
			{
				"cpuplayers_defensive",
				"cpuplayers_aggressive",
				"cpuplayers_dynamic",
				"cpuplayers_norushtime5",
				"cpuplayers_norushtime10",
				"cpuplayers_norushtime15",
				"AllShipBuildSpeed",
				"AllShipBuildSpeedHard",
				"AllShipBuildSpeedExpert",
				"ResourceCollectionRateHard",
				"ResourceCollectionRateExpert",
				"WeaponDamageUpgrade125",
				"WeaponDamageUpgrade150",
				"WeaponDamageUpgrade175",
				"WeaponDamageUpgrade200",
				"CorvetteDrive",
				"CorvetteChassis",
				"HeavyCorvetteUpgrade",
				"FastTrackingTurrets",
				"MinelayingTech",
				"ProximitySensor",
				"SensorArray",
				"GravityGenerator",
				"CloakGenerator",
				"HyperspaceDamageReductionUpgrade",
				"HyperspaceDamageReductionUpgradeHC",
				"FighterDrive",
				"FighterChassis",
				"DefenderSubSystems",
				"PlasmaBombLauncher",
				"DefenseFighter",
				"CapitalShipDrive",
				"CapitalShipChassis",
				"IonCannons",
				"DefenseField",
				"SuperCapitalShipDrive",
				"GuidedMissiles",
				"SuperHeavyChassis",
				"HeavyGuns",
				"SGMCapitalHealth",
				"SGMFrigateHealth",
				"SGMGravWellHealth",
			},
		},
	},
}
