research =
{
	-- #1.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "AllShipBuildSpeed",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.025,
	},
	-- #2.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "AllShipBuildSpeedExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.075,
	},
	-- #3.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "AllShipBuildSpeedHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
		UpgradeName = "BUILDSPEED",
		UpgradeType = Modifier,
		UpgradeValue = 1.05,
	},
	-- #4.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "cpuplayers_aggressive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #5.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "cpuplayers_defensive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #6.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "cpuplayers_dynamic",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #7.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "cpuplayers_norushtime10",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #8.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "cpuplayers_norushtime15",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #9.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "cpuplayers_norushtime5",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #10.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "ResourceCollectionRateExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.09,
	},
	-- #10.1, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "ResourceCollectionRateExpert_res0_hyp0",
		RequiredResearch = "ResourceCollectionRateExpert",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res0_hyp0",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.09,
	},
	-- #10.2, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "ResourceCollectionRateExpert_res1_hyp0",
		RequiredResearch = "ResourceCollectionRateExpert",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp0",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.09,
	},
	-- #10.3, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "ResourceCollectionRateExpert_res0_hyp1",
		RequiredResearch = "ResourceCollectionRateExpert",
		RequiredSubSystems = "",
		TargetName = "Tai_ResourceCollector_res0_hyp1",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.09,
	},
	-- #10.4, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "ResourceCollectionRateExpert_res1_hyp1",
		RequiredResearch = "ResourceCollectionRateExpert",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp1",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.09,
	},
	-- #11.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "ResourceCollectionRateHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector",
		TargetType = Ship,
		Time = 1,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.04,
	},
	-- #11.1, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "ResourceCollectionRateHard_res0_hyp0",
		RequiredResearch = "ResourceCollectionRateHard",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res0_hyp0",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.04,
	},
	-- #11.2, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "ResourceCollectionRateHard_res1_hyp0",
		RequiredResearch = "ResourceCollectionRateHard",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp0",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.04,
	},
	-- #11.3, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "ResourceCollectionRateHard_res0_hyp1",
		RequiredResearch = "ResourceCollectionRateHard",
		RequiredSubSystems = "",
		TargetName = "Tai_ResourceCollector_res0_hyp1",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.04,
	},
	-- #11.4, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "ResourceCollectionRateHard_res1_hyp1",
		RequiredResearch = "ResourceCollectionRateHard",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp1",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "ResourceCollectionRate",
		UpgradeType = Modifier,
		UpgradeValue = 1.04,
	},
	-- #12.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "WeaponDamageUpgrade125",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.25,
	},
	-- #13.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "WeaponDamageUpgrade150",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.5,
	},
	-- #14.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "WeaponDamageUpgrade175",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 1.75,
	},
	-- #15.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "WeaponDamageUpgrade200",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
		UpgradeName = "WeaponDamage",
		UpgradeType = Modifier,
		UpgradeValue = 2,
	},
	-- #16.0, corvette_tech.lua
	{
		Cost = 700,
		Description = "$11523",
		DisplayPriority = 22,
		DisplayedName = "$11522",
		Icon = Icon_Build,
		Name = "CorvetteChassis",
		RequiredResearch = "CorvetteDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11522",
		TargetName = "Tai_SalvageCorvette",
		TargetType = Ship,
		Time = 60,
	},
	-- #16.1, corvette_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "CorvetteChassis_hyp0",
		RequiredResearch = "CorvetteChassis",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11522",
		TargetName = "Tai_SalvageCorvette_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #16.2, corvette_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "CorvetteChassis_hyp1",
		RequiredResearch = "CorvetteChassis",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11522",
		TargetName = "Tai_SalvageCorvette_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #17.0, corvette_tech.lua
	{
		Cost = 1000,
		Description = "$11517",
		DisplayPriority = 21,
		DisplayedName = "$11516",
		Icon = Icon_Build,
		Name = "CorvetteDrive",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11516",
		TargetName = "Tai_LightCorvette",
		TargetType = Ship,
		Time = 75,
	},
	-- #17.1, corvette_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "CorvetteDrive_hyp0",
		RequiredResearch = "CorvetteDrive",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11516",
		TargetName = "Tai_LightCorvette_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #17.2, corvette_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "CorvetteDrive_hyp1",
		RequiredResearch = "CorvetteDrive",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11516",
		TargetName = "Tai_LightCorvette_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #18.0, corvette_tech.lua
	{
		Cost = 500,
		Description = "$11511",
		DisplayPriority = 24,
		DisplayedName = "$11510",
		Icon = Icon_Build,
		Name = "FastTrackingTurrets",
		RequiredResearch = "CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11510",
		TargetName = "Tai_MultiGunCorvette",
		TargetType = Ship,
		Time = 40,
	},
	-- #18.1, corvette_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "FastTrackingTurrets_hyp0",
		RequiredResearch = "FastTrackingTurrets",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11510",
		TargetName = "Tai_MultiGunCorvette_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #18.2, corvette_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "FastTrackingTurrets_hyp1",
		RequiredResearch = "FastTrackingTurrets",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11510",
		TargetName = "Tai_MultiGunCorvette_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #19.0, corvette_tech.lua
	{
		Cost = 400,
		Description = "$11519",
		DisplayPriority = 23,
		DisplayedName = "$11518",
		Icon = Icon_Build,
		Name = "HeavyCorvetteUpgrade",
		RequiredResearch = "CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11518",
		TargetName = "Tai_HeavyCorvette",
		TargetType = Ship,
		Time = 30,
	},
	-- #19.1, corvette_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "HeavyCorvetteUpgrade_hyp0",
		RequiredResearch = "HeavyCorvetteUpgrade",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11518",
		TargetName = "Tai_HeavyCorvette_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #19.2, corvette_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "HeavyCorvetteUpgrade_hyp1",
		RequiredResearch = "HeavyCorvetteUpgrade",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11518",
		TargetName = "Tai_HeavyCorvette_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #20.0, corvette_tech.lua
	{
		Cost = 1200,
		Description = "$11521",
		DisplayPriority = 25,
		DisplayedName = "$11520",
		Icon = Icon_Build,
		Name = "MinelayingTech",
		RequiredResearch = "CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11520",
		TargetName = "Tai_MinelayerCorvette",
		TargetType = Ship,
		Time = 100,
	},
	-- #20.1, corvette_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "MinelayingTech_hyp0",
		RequiredResearch = "MinelayingTech",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11520",
		TargetName = "Tai_MinelayerCorvette_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #20.2, corvette_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "MinelayingTech_hyp1",
		RequiredResearch = "MinelayingTech",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11520",
		TargetName = "Tai_MinelayerCorvette_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #21.0, default.lua
	{
		Cost = 500,
		Description = "$11559",
		DisplayPriority = 54,
		DisplayedName = "$11558",
		Icon = Icon_Build,
		Name = "CloakGenerator",
		RequiredResearch = "CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11558",
		TargetName = "Tai_CloakGenerator",
		TargetType = Ship,
		Time = 50,
	},
	-- #21.1, default.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "CloakGenerator_hyp0",
		RequiredResearch = "CloakGenerator",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11558",
		TargetName = "Tai_CloakGenerator_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #21.2, default.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "CloakGenerator_hyp1",
		RequiredResearch = "CloakGenerator",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11558",
		TargetName = "Tai_CloakGenerator_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #22.0, default.lua
	{
		Cost = 500,
		Description = "$11557",
		DisplayPriority = 53,
		DisplayedName = "$11556",
		Icon = Icon_Build,
		Name = "GravityGenerator",
		RequiredResearch = "CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11556",
		TargetName = "Tai_GravWellGenerator",
		TargetType = Ship,
		Time = 100,
	},
	-- #22.1, default.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "GravityGenerator_hyp0",
		RequiredResearch = "GravityGenerator",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11556",
		TargetName = "Tai_GravWellGenerator_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #22.2, default.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "GravityGenerator_hyp1",
		RequiredResearch = "GravityGenerator",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11556",
		TargetName = "Tai_GravWellGenerator_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #23.0, default.lua
	{
		Cost = 0,
		Description = "Enhances the fleet's hyperspace drive systems, reducing the hyperspace damage caused by gravity wells. Ships only take 10 11384919amage when forced out of hyperspace.",
		DisplayPriority = 950,
		DisplayedName = "Hyperspace Damage Reduction",
		DoNotGrant = 1,
		Name = "HyperspaceDamageReductionUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "10Hyperspace Exit Damage",
		TargetName = "Tai_fleet",
		TargetType = AllShips,
		Time = 0,
		UpgradeName = "HyperSpaceAbortDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0.4,
	},
	-- #24.0, default.lua
	{
		Cost = 0,
		Description = "Enhances the fleet's hyperspace drive systems, reducing the hyperspace damage caused by gravity wells. Heavy Cruisers only take 0 11384919amage when forced out of hyperspace.",
		DisplayPriority = 951,
		DisplayedName = "Hyperspace Damage Reduction",
		DoNotGrant = 1,
		Name = "HyperspaceDamageReductionUpgradeHC",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "0HC Hyperspace Exit Damage",
		TargetName = "Tai_HeavyCruiser",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "HyperSpaceAbortDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0,
	},
	-- #24.1, default.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "HyperspaceDamageReductionUpgradeHC_hyp0",
		RequiredResearch = "HyperspaceDamageReductionUpgradeHC",
		RequiredSubSystems = "",
		ShortDisplayedName = "0HC Hyperspace Exit Damage",
		TargetName = "Tai_HeavyCruiser_hyp0",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "HyperSpaceAbortDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0,
	},
	-- #24.2, default.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "HyperspaceDamageReductionUpgradeHC_hyp1",
		RequiredResearch = "HyperspaceDamageReductionUpgradeHC",
		RequiredSubSystems = "",
		ShortDisplayedName = "0HC Hyperspace Exit Damage",
		TargetName = "Tai_HeavyCruiser_hyp1",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "HyperSpaceAbortDamage",
		UpgradeType = Modifier,
		UpgradeValue = 0,
	},
	-- #25.0, default.lua
	{
		Cost = 500,
		Description = "$11553",
		DisplayPriority = 51,
		DisplayedName = "$11552",
		Icon = Icon_Build,
		Name = "ProximitySensor",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11552",
		TargetName = "Tai_ProximitySensor",
		TargetType = Ship,
		Time = 40,
	},
	-- #25.1, default.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "ProximitySensor_hyp0",
		RequiredResearch = "ProximitySensor",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11552",
		TargetName = "Tai_ProximitySensor_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #25.2, default.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "ProximitySensor_hyp1",
		RequiredResearch = "ProximitySensor",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11552",
		TargetName = "Tai_ProximitySensor_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #26.0, default.lua
	{
		Cost = 500,
		Description = "$11555",
		DisplayPriority = 52,
		DisplayedName = "$11554",
		Icon = Icon_Build,
		Name = "SensorArray",
		RequiredResearch = "ProximitySensor",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11554",
		TargetName = "Tai_SensorArray",
		TargetType = Ship,
		Time = 50,
	},
	-- #26.1, default.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "SensorArray_hyp0",
		RequiredResearch = "SensorArray",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11554",
		TargetName = "Tai_SensorArray_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #26.2, default.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "SensorArray_hyp1",
		RequiredResearch = "SensorArray",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11554",
		TargetName = "Tai_SensorArray_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #27.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "SGMCapitalHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.5,
	},
	-- #28.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "SGMFrigateHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Frigate",
		TargetType = Family,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.45,
	},
	-- #29.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "SGMGravWellHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Tai_GravWellGenerator",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.2,
	},
	-- #29.1, explicit_grant.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "SGMGravWellHealth_hyp0",
		RequiredResearch = "SGMGravWellHealth",
		RequiredSubSystems = "",
		TargetName = "Tai_GravWellGenerator_hyp0",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.2,
	},
	-- #29.2, explicit_grant.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "SGMGravWellHealth_hyp1",
		RequiredResearch = "SGMGravWellHealth",
		RequiredSubSystems = "",
		TargetName = "Tai_GravWellGenerator_hyp1",
		TargetType = Ship,
		Time = 0,
		UpgradeName = "MAXHEALTH",
		UpgradeType = Modifier,
		UpgradeValue = 0.2,
	},
	-- #30.0, fighter_tech.lua
	{
		Cost = 800,
		Description = "$11529",
		DisplayPriority = 13,
		DisplayedName = "$11528",
		Icon = Icon_Build,
		Name = "DefenderSubSystems",
		RequiredResearch = "FighterDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11528",
		TargetName = "Tai_Defender",
		TargetType = Ship,
		Time = 75,
	},
	-- #30.1, fighter_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "DefenderSubSystems_hyp0",
		RequiredResearch = "DefenderSubSystems",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11528",
		TargetName = "Tai_Defender_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #30.2, fighter_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "DefenderSubSystems_hyp1",
		RequiredResearch = "DefenderSubSystems",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11528",
		TargetName = "Tai_Defender_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #31.0, fighter_tech.lua
	{
		Cost = 1000,
		Description = "$11509",
		DisplayPriority = 15,
		DisplayedName = "$11508",
		Icon = Icon_Build,
		Name = "DefenseFighter",
		RequiredResearch = "FighterChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11508",
		TargetName = "Tai_DefenseFighter",
		TargetType = Ship,
		Time = 100,
	},
	-- #31.1, fighter_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "DefenseFighter_hyp0",
		RequiredResearch = "DefenseFighter",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11508",
		TargetName = "Tai_DefenseFighter_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #31.2, fighter_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "DefenseFighter_hyp1",
		RequiredResearch = "DefenseFighter",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11508",
		TargetName = "Tai_DefenseFighter_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #32.0, fighter_tech.lua
	{
		Cost = 300,
		Description = "$11515",
		DisplayPriority = 12,
		DisplayedName = "$11514",
		Icon = Icon_Build,
		Name = "FighterChassis",
		RequiredResearch = "FighterDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11514",
		TargetName = "Tai_Interceptor",
		TargetType = Ship,
		Time = 30,
	},
	-- #32.1, fighter_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "FighterChassis_hyp0",
		RequiredResearch = "FighterChassis",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11514",
		TargetName = "Tai_Interceptor_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #32.2, fighter_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "FighterChassis_hyp1",
		RequiredResearch = "FighterChassis",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11514",
		TargetName = "Tai_Interceptor_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #33.0, fighter_tech.lua
	{
		Cost = 200,
		Description = "$11503",
		DisplayPriority = 11,
		DisplayedName = "$11502",
		Icon = Icon_Build,
		Name = "FighterDrive",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11502",
		TargetName = "Tai_Scout",
		TargetType = Ship,
		Time = 20,
	},
	-- #33.1, fighter_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "FighterDrive_hyp0",
		RequiredResearch = "FighterDrive",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11502",
		TargetName = "Tai_Scout_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #33.2, fighter_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "FighterDrive_hyp1",
		RequiredResearch = "FighterDrive",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11502",
		TargetName = "Tai_Scout_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #34.0, fighter_tech.lua
	{
		Cost = 400,
		Description = "$11513",
		DisplayPriority = 14,
		DisplayedName = "$11512",
		Icon = Icon_Build,
		Name = "PlasmaBombLauncher",
		RequiredResearch = "FighterChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11512",
		TargetName = "Tai_AttackBomber",
		TargetType = Ship,
		Time = 40,
	},
	-- #34.1, fighter_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "PlasmaBombLauncher_hyp0",
		RequiredResearch = "PlasmaBombLauncher",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11512",
		TargetName = "Tai_AttackBomber_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #34.2, fighter_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "PlasmaBombLauncher_hyp1",
		RequiredResearch = "PlasmaBombLauncher",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11512",
		TargetName = "Tai_AttackBomber_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #35.0, frigate_tech.lua
	{
		Cost = 1200,
		Description = "$11541",
		DisplayPriority = 32,
		DisplayedName = "$11540",
		Icon = Icon_Build,
		Name = "CapitalShipChassis",
		RequiredResearch = "CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11540",
		TargetName = "Tai_AssaultFrigate",
		TargetType = Ship,
		Time = 90,
	},
	-- #35.1, frigate_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "CapitalShipChassis_hyp0",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11540",
		TargetName = "Tai_AssaultFrigate_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #35.2, frigate_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "CapitalShipChassis_hyp1",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11540",
		TargetName = "Tai_AssaultFrigate_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #36.0, frigate_tech.lua
	{
		Cost = 1000,
		Description = "$11527",
		DisplayPriority = 31,
		DisplayedName = "$11526",
		Icon = Icon_Build,
		Name = "CapitalShipDrive",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11526",
		TargetName = "Tai_SupportFrigate",
		TargetType = Ship,
		Time = 75,
	},
	-- #36.1, frigate_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "CapitalShipDrive_hyp0",
		RequiredResearch = "CapitalShipDrive",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11526",
		TargetName = "Tai_SupportFrigate_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #36.2, frigate_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "CapitalShipDrive_hyp1",
		RequiredResearch = "CapitalShipDrive",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11526",
		TargetName = "Tai_SupportFrigate_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #37.0, frigate_tech.lua
	{
		Cost = 1100,
		Description = "$11539",
		DisplayPriority = 34,
		DisplayedName = "$11538",
		Icon = Icon_Build,
		Name = "DefenseField",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11538",
		TargetName = "Tai_FieldFrigate",
		TargetType = Ship,
		Time = 80,
	},
	-- #37.1, frigate_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "DefenseField_hyp0",
		RequiredResearch = "DefenseField",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11538",
		TargetName = "Tai_FieldFrigate_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #37.2, frigate_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "DefenseField_hyp1",
		RequiredResearch = "DefenseField",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11538",
		TargetName = "Tai_FieldFrigate_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #38.0, frigate_tech.lua
	{
		Cost = 1700,
		Description = "$11535",
		DisplayPriority = 33,
		DisplayedName = "$11534",
		Icon = Icon_Build,
		Name = "IonCannons",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11534",
		TargetName = "Tai_IonCannonFrigate",
		TargetType = Ship,
		Time = 120,
	},
	-- #38.1, frigate_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "IonCannons_hyp0",
		RequiredResearch = "IonCannons",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11534",
		TargetName = "Tai_IonCannonFrigate_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #38.2, frigate_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "IonCannons_hyp1",
		RequiredResearch = "IonCannons",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11534",
		TargetName = "Tai_IonCannonFrigate_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #39.0, supercapital_tech.lua
	{
		Cost = 3500,
		Description = "$11547",
		DisplayPriority = 44,
		DisplayedName = "$11546",
		Icon = Icon_Build,
		Name = "GuidedMissiles",
		RequiredResearch = "SuperCapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11546",
		TargetName = "Tai_MissileDestroyer",
		TargetType = Ship,
		Time = 120,
	},
	-- #39.1, supercapital_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "GuidedMissiles_hyp0",
		RequiredResearch = "GuidedMissiles",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11546",
		TargetName = "Tai_MissileDestroyer_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #39.2, supercapital_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "GuidedMissiles_hyp1",
		RequiredResearch = "GuidedMissiles",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11546",
		TargetName = "Tai_MissileDestroyer_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #40.0, supercapital_tech.lua
	{
		Cost = 7000,
		Description = "$11551",
		DisplayPriority = 46,
		DisplayedName = "$11550",
		Icon = Icon_Build,
		Name = "HeavyGuns",
		RequiredResearch = "SuperHeavyChassis & SuperCapitalShipDrive & IonCannons",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11550",
		TargetName = "Tai_HeavyCruiser",
		TargetType = Ship,
		Time = 360,
	},
	-- #40.1, supercapital_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "HeavyGuns_hyp0",
		RequiredResearch = "HeavyGuns",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11550",
		TargetName = "Tai_HeavyCruiser_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #40.2, supercapital_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "HeavyGuns_hyp1",
		RequiredResearch = "HeavyGuns",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11550",
		TargetName = "Tai_HeavyCruiser_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #41.0, supercapital_tech.lua
	{
		Cost = 1500,
		Description = "$11543",
		DisplayPriority = 41,
		DisplayedName = "$11542",
		Icon = Icon_Build,
		Name = "SuperCapitalShipDrive",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier",
		TargetType = Ship,
		Time = 50,
	},
	-- #41.1, supercapital_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "SuperCapitalShipDrive_res0_hyp0",
		RequiredResearch = "SuperCapitalShipDrive",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res0_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #41.2, supercapital_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "SuperCapitalShipDrive_res1_hyp0",
		RequiredResearch = "SuperCapitalShipDrive",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res1_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #41.3, supercapital_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "SuperCapitalShipDrive_res0_hyp1",
		RequiredResearch = "SuperCapitalShipDrive",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res0_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #41.4, supercapital_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "SuperCapitalShipDrive_res1_hyp1",
		RequiredResearch = "SuperCapitalShipDrive",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res1_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #42.0, supercapital_tech.lua
	{
		Cost = 4000,
		Description = "$11561",
		DisplayPriority = 45,
		DisplayedName = "$11560",
		Icon = Icon_Build,
		Name = "SuperHeavyChassis",
		RequiredResearch = "SuperCapitalShipDrive & IonCannons",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11560",
		TargetName = "Tai_Destroyer",
		TargetType = Ship,
		Time = 140,
	},
	-- #42.1, supercapital_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "SuperHeavyChassis_hyp0",
		RequiredResearch = "SuperHeavyChassis",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11560",
		TargetName = "Tai_Destroyer_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #42.2, supercapital_tech.lua
	{
		Cost = 0,
		Description = "Instant Tech",
		DisplayPriority = 0,
		DisplayedName = "",
		Icon = Icon_Build,
		Name = "SuperHeavyChassis_hyp1",
		RequiredResearch = "SuperHeavyChassis",
		RequiredSubSystems = "",
		ShortDisplayedName = "$11560",
		TargetName = "Tai_Destroyer_hyp1",
		TargetType = Ship,
		Time = 0,
	},
}
