research =
{
	-- #1.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_AllShipBuildSpeed",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
	},
	-- #2.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_AllShipBuildSpeedExpert",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
	},
	-- #3.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_AllShipBuildSpeedHard",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 1,
	},
	-- #4.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_aggressive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #5.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_defensive",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #6.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_dynamic",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #7.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_norushtime10",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #8.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_norushtime15",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #9.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_cpuplayers_norushtime5",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "",
		Time = 1,
	},
	-- #10.1, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateExpert_res0_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res0_hyp0",
		TargetType = Ship,
		Time = 1,
	},
	-- #10.2, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateExpert_res1_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp0",
		TargetType = Ship,
		Time = 1,
	},
	-- #10.3, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateExpert_res0_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res0_hyp1",
		TargetType = Ship,
		Time = 1,
	},
	-- #10.4, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateExpert_res1_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp1",
		TargetType = Ship,
		Time = 1,
	},
	-- #11.1, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateHard_res0_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res0_hyp0",
		TargetType = Ship,
		Time = 1,
	},
	-- #11.2, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateHard_res1_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp0",
		TargetType = Ship,
		Time = 1,
	},
	-- #11.3, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateHard_res0_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res0_hyp1",
		TargetType = Ship,
		Time = 1,
	},
	-- #11.4, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_ResourceCollectionRateHard_res1_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetName = "Tai_resourcecollector_res1_hyp1",
		TargetType = Ship,
		Time = 1,
	},
	-- #12.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_WeaponDamageUpgrade125",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
	},
	-- #13.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_WeaponDamageUpgrade150",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
	},
	-- #14.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_WeaponDamageUpgrade175",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
	},
	-- #15.0, ai_properties.lua
	{
		AIOnly = 1,
		Cost = 1,
		Description = "",
		DisplayPriority = 0,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_WeaponDamageUpgrade200",
		RequiredResearch = "",
		RequiredSubSystems = "",
		TargetType = AllShips,
		Time = 1,
	},
	-- #16.1, corvette_tech.lua
	{
		Cost = 700,
		Description = "$11523",
		DisplayPriority = 22,
		DisplayedName = "$11522",
		Icon = Icon_Build,
		Name = "Tai_CorvetteChassis_hyp0",
		RequiredResearch = "CorvetteDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11522",
		TargetName = "Tai_SalvageCorvette_hyp0",
		TargetType = Ship,
		Time = 60,
	},
	-- #16.2, corvette_tech.lua
	{
		Cost = 700,
		Description = "$11523",
		DisplayPriority = 22,
		DisplayedName = "$11522",
		Icon = Icon_Build,
		Name = "Tai_CorvetteChassis_hyp1",
		RequiredResearch = "CorvetteDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11522",
		TargetName = "Tai_SalvageCorvette_hyp1",
		TargetType = Ship,
		Time = 60,
	},
	-- #17.1, corvette_tech.lua
	{
		Cost = 1000,
		Description = "$11517",
		DisplayPriority = 21,
		DisplayedName = "$11516",
		Icon = Icon_Build,
		Name = "Tai_CorvetteDrive_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11516",
		TargetName = "Tai_LightCorvette_hyp0",
		TargetType = Ship,
		Time = 75,
	},
	-- #17.2, corvette_tech.lua
	{
		Cost = 1000,
		Description = "$11517",
		DisplayPriority = 21,
		DisplayedName = "$11516",
		Icon = Icon_Build,
		Name = "Tai_CorvetteDrive_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11516",
		TargetName = "Tai_LightCorvette_hyp1",
		TargetType = Ship,
		Time = 75,
	},
	-- #18.1, corvette_tech.lua
	{
		Cost = 500,
		Description = "$11511",
		DisplayPriority = 24,
		DisplayedName = "$11510",
		Icon = Icon_Build,
		Name = "Tai_FastTrackingTurrets_hyp0",
		RequiredResearch = "CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11510",
		TargetName = "Tai_MultiGunCorvette_hyp0",
		TargetType = Ship,
		Time = 40,
	},
	-- #18.2, corvette_tech.lua
	{
		Cost = 500,
		Description = "$11511",
		DisplayPriority = 24,
		DisplayedName = "$11510",
		Icon = Icon_Build,
		Name = "Tai_FastTrackingTurrets_hyp1",
		RequiredResearch = "CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11510",
		TargetName = "Tai_MultiGunCorvette_hyp1",
		TargetType = Ship,
		Time = 40,
	},
	-- #19.1, corvette_tech.lua
	{
		Cost = 400,
		Description = "$11519",
		DisplayPriority = 23,
		DisplayedName = "$11518",
		Icon = Icon_Build,
		Name = "Tai_HeavyCorvetteUpgrade_hyp0",
		RequiredResearch = "CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11518",
		TargetName = "Tai_HeavyCorvette_hyp0",
		TargetType = Ship,
		Time = 30,
	},
	-- #19.2, corvette_tech.lua
	{
		Cost = 400,
		Description = "$11519",
		DisplayPriority = 23,
		DisplayedName = "$11518",
		Icon = Icon_Build,
		Name = "Tai_HeavyCorvetteUpgrade_hyp1",
		RequiredResearch = "CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11518",
		TargetName = "Tai_HeavyCorvette_hyp1",
		TargetType = Ship,
		Time = 30,
	},
	-- #20.1, corvette_tech.lua
	{
		Cost = 1200,
		Description = "$11521",
		DisplayPriority = 25,
		DisplayedName = "$11520",
		Icon = Icon_Build,
		Name = "Tai_MinelayingTech_hyp0",
		RequiredResearch = "CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11520",
		TargetName = "Tai_MinelayerCorvette_hyp0",
		TargetType = Ship,
		Time = 100,
	},
	-- #20.2, corvette_tech.lua
	{
		Cost = 1200,
		Description = "$11521",
		DisplayPriority = 25,
		DisplayedName = "$11520",
		Icon = Icon_Build,
		Name = "Tai_MinelayingTech_hyp1",
		RequiredResearch = "CorvetteChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11520",
		TargetName = "Tai_MinelayerCorvette_hyp1",
		TargetType = Ship,
		Time = 100,
	},
	-- #21.1, default.lua
	{
		Cost = 500,
		Description = "$11559",
		DisplayPriority = 54,
		DisplayedName = "$11558",
		Icon = Icon_Build,
		Name = "Tai_CloakGenerator_hyp0",
		RequiredResearch = "CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11558",
		TargetName = "Tai_CloakGenerator_hyp0",
		TargetType = Ship,
		Time = 50,
	},
	-- #21.2, default.lua
	{
		Cost = 500,
		Description = "$11559",
		DisplayPriority = 54,
		DisplayedName = "$11558",
		Icon = Icon_Build,
		Name = "Tai_CloakGenerator_hyp1",
		RequiredResearch = "CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11558",
		TargetName = "Tai_CloakGenerator_hyp1",
		TargetType = Ship,
		Time = 50,
	},
	-- #22.1, default.lua
	{
		Cost = 500,
		Description = "$11557",
		DisplayPriority = 53,
		DisplayedName = "$11556",
		Icon = Icon_Build,
		Name = "Tai_GravityGenerator_hyp0",
		RequiredResearch = "CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11556",
		TargetName = "Tai_GravWellGenerator_hyp0",
		TargetType = Ship,
		Time = 100,
	},
	-- #22.2, default.lua
	{
		Cost = 500,
		Description = "$11557",
		DisplayPriority = 53,
		DisplayedName = "$11556",
		Icon = Icon_Build,
		Name = "Tai_GravityGenerator_hyp1",
		RequiredResearch = "CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11556",
		TargetName = "Tai_GravWellGenerator_hyp1",
		TargetType = Ship,
		Time = 100,
	},
	-- #23.0, default.lua
	{
		Cost = 0,
		Description = "Enhances the fleet's hyperspace drive systems, reducing the hyperspace damage caused by gravity wells. Ships only take 10 11384919amage when forced out of hyperspace.",
		DisplayPriority = 950,
		DisplayedName = "Hyperspace Damage Reduction",
		DoNotGrant = 1,
		Name = "Tai_HyperspaceDamageReductionUpgrade",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "10Hyperspace Exit Damage",
		TargetName = "Tai_fleet",
		TargetType = AllShips,
		Time = 0,
	},
	-- #24.1, default.lua
	{
		Cost = 0,
		Description = "Enhances the fleet's hyperspace drive systems, reducing the hyperspace damage caused by gravity wells. Heavy Cruisers only take 0 11384919amage when forced out of hyperspace.",
		DisplayPriority = 951,
		DisplayedName = "Hyperspace Damage Reduction",
		DoNotGrant = 1,
		Name = "Tai_HyperspaceDamageReductionUpgradeHC_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "0HC Hyperspace Exit Damage",
		TargetName = "Tai_HeavyCruiser_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #24.2, default.lua
	{
		Cost = 0,
		Description = "Enhances the fleet's hyperspace drive systems, reducing the hyperspace damage caused by gravity wells. Heavy Cruisers only take 0 11384919amage when forced out of hyperspace.",
		DisplayPriority = 951,
		DisplayedName = "Hyperspace Damage Reduction",
		DoNotGrant = 1,
		Name = "Tai_HyperspaceDamageReductionUpgradeHC_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "",
		ShortDisplayedName = "0HC Hyperspace Exit Damage",
		TargetName = "Tai_HeavyCruiser_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #25.1, default.lua
	{
		Cost = 500,
		Description = "$11553",
		DisplayPriority = 51,
		DisplayedName = "$11552",
		Icon = Icon_Build,
		Name = "Tai_ProximitySensor_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11552",
		TargetName = "Tai_ProximitySensor_hyp0",
		TargetType = Ship,
		Time = 40,
	},
	-- #25.2, default.lua
	{
		Cost = 500,
		Description = "$11553",
		DisplayPriority = 51,
		DisplayedName = "$11552",
		Icon = Icon_Build,
		Name = "Tai_ProximitySensor_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11552",
		TargetName = "Tai_ProximitySensor_hyp1",
		TargetType = Ship,
		Time = 40,
	},
	-- #26.1, default.lua
	{
		Cost = 500,
		Description = "$11555",
		DisplayPriority = 52,
		DisplayedName = "$11554",
		Icon = Icon_Build,
		Name = "Tai_SensorArray_hyp0",
		RequiredResearch = "ProximitySensor",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11554",
		TargetName = "Tai_SensorArray_hyp0",
		TargetType = Ship,
		Time = 50,
	},
	-- #26.2, default.lua
	{
		Cost = 500,
		Description = "$11555",
		DisplayPriority = 52,
		DisplayedName = "$11554",
		Icon = Icon_Build,
		Name = "Tai_SensorArray_hyp1",
		RequiredResearch = "ProximitySensor",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11554",
		TargetName = "Tai_SensorArray_hyp1",
		TargetType = Ship,
		Time = 50,
	},
	-- #27.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_SGMCapitalHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Capital",
		TargetType = Family,
		Time = 0,
	},
	-- #28.0, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_SGMFrigateHealth",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Frigate",
		TargetType = Family,
		Time = 0,
	},
	-- #29.1, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_SGMGravWellHealth_hyp0",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Tai_GravWellGenerator_hyp0",
		TargetType = Ship,
		Time = 0,
	},
	-- #29.2, explicit_grant.lua
	{
		Cost = 0,
		Description = "",
		DisplayPriority = 1208,
		DisplayedName = "",
		DoNotGrant = 1,
		Name = "Tai_SGMGravWellHealth_hyp1",
		RequiredResearch = "RESEARCH HACK",
		RequiredSubSystems = "",
		TargetName = "Tai_GravWellGenerator_hyp1",
		TargetType = Ship,
		Time = 0,
	},
	-- #30.1, fighter_tech.lua
	{
		Cost = 800,
		Description = "$11529",
		DisplayPriority = 13,
		DisplayedName = "$11528",
		Icon = Icon_Build,
		Name = "Tai_DefenderSubSystems_hyp0",
		RequiredResearch = "FighterDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11528",
		TargetName = "Tai_Defender_hyp0",
		TargetType = Ship,
		Time = 75,
	},
	-- #30.2, fighter_tech.lua
	{
		Cost = 800,
		Description = "$11529",
		DisplayPriority = 13,
		DisplayedName = "$11528",
		Icon = Icon_Build,
		Name = "Tai_DefenderSubSystems_hyp1",
		RequiredResearch = "FighterDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11528",
		TargetName = "Tai_Defender_hyp1",
		TargetType = Ship,
		Time = 75,
	},
	-- #31.1, fighter_tech.lua
	{
		Cost = 1000,
		Description = "$11509",
		DisplayPriority = 15,
		DisplayedName = "$11508",
		Icon = Icon_Build,
		Name = "Tai_DefenseFighter_hyp0",
		RequiredResearch = "FighterChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11508",
		TargetName = "Tai_DefenseFighter_hyp0",
		TargetType = Ship,
		Time = 100,
	},
	-- #31.2, fighter_tech.lua
	{
		Cost = 1000,
		Description = "$11509",
		DisplayPriority = 15,
		DisplayedName = "$11508",
		Icon = Icon_Build,
		Name = "Tai_DefenseFighter_hyp1",
		RequiredResearch = "FighterChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11508",
		TargetName = "Tai_DefenseFighter_hyp1",
		TargetType = Ship,
		Time = 100,
	},
	-- #32.1, fighter_tech.lua
	{
		Cost = 300,
		Description = "$11515",
		DisplayPriority = 12,
		DisplayedName = "$11514",
		Icon = Icon_Build,
		Name = "Tai_FighterChassis_hyp0",
		RequiredResearch = "FighterDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11514",
		TargetName = "Tai_Interceptor_hyp0",
		TargetType = Ship,
		Time = 30,
	},
	-- #32.2, fighter_tech.lua
	{
		Cost = 300,
		Description = "$11515",
		DisplayPriority = 12,
		DisplayedName = "$11514",
		Icon = Icon_Build,
		Name = "Tai_FighterChassis_hyp1",
		RequiredResearch = "FighterDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11514",
		TargetName = "Tai_Interceptor_hyp1",
		TargetType = Ship,
		Time = 30,
	},
	-- #33.1, fighter_tech.lua
	{
		Cost = 200,
		Description = "$11503",
		DisplayPriority = 11,
		DisplayedName = "$11502",
		Icon = Icon_Build,
		Name = "Tai_FighterDrive_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11502",
		TargetName = "Tai_Scout_hyp0",
		TargetType = Ship,
		Time = 20,
	},
	-- #33.2, fighter_tech.lua
	{
		Cost = 200,
		Description = "$11503",
		DisplayPriority = 11,
		DisplayedName = "$11502",
		Icon = Icon_Build,
		Name = "Tai_FighterDrive_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11502",
		TargetName = "Tai_Scout_hyp1",
		TargetType = Ship,
		Time = 20,
	},
	-- #34.1, fighter_tech.lua
	{
		Cost = 400,
		Description = "$11513",
		DisplayPriority = 14,
		DisplayedName = "$11512",
		Icon = Icon_Build,
		Name = "Tai_PlasmaBombLauncher_hyp0",
		RequiredResearch = "FighterChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11512",
		TargetName = "Tai_AttackBomber_hyp0",
		TargetType = Ship,
		Time = 40,
	},
	-- #34.2, fighter_tech.lua
	{
		Cost = 400,
		Description = "$11513",
		DisplayPriority = 14,
		DisplayedName = "$11512",
		Icon = Icon_Build,
		Name = "Tai_PlasmaBombLauncher_hyp1",
		RequiredResearch = "FighterChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11512",
		TargetName = "Tai_AttackBomber_hyp1",
		TargetType = Ship,
		Time = 40,
	},
	-- #35.1, frigate_tech.lua
	{
		Cost = 1200,
		Description = "$11541",
		DisplayPriority = 32,
		DisplayedName = "$11540",
		Icon = Icon_Build,
		Name = "Tai_CapitalShipChassis_hyp0",
		RequiredResearch = "CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11540",
		TargetName = "Tai_AssaultFrigate_hyp0",
		TargetType = Ship,
		Time = 90,
	},
	-- #35.2, frigate_tech.lua
	{
		Cost = 1200,
		Description = "$11541",
		DisplayPriority = 32,
		DisplayedName = "$11540",
		Icon = Icon_Build,
		Name = "Tai_CapitalShipChassis_hyp1",
		RequiredResearch = "CapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11540",
		TargetName = "Tai_AssaultFrigate_hyp1",
		TargetType = Ship,
		Time = 90,
	},
	-- #36.1, frigate_tech.lua
	{
		Cost = 1000,
		Description = "$11527",
		DisplayPriority = 31,
		DisplayedName = "$11526",
		Icon = Icon_Build,
		Name = "Tai_CapitalShipDrive_hyp0",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11526",
		TargetName = "Tai_SupportFrigate_hyp0",
		TargetType = Ship,
		Time = 75,
	},
	-- #36.2, frigate_tech.lua
	{
		Cost = 1000,
		Description = "$11527",
		DisplayPriority = 31,
		DisplayedName = "$11526",
		Icon = Icon_Build,
		Name = "Tai_CapitalShipDrive_hyp1",
		RequiredResearch = "",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11526",
		TargetName = "Tai_SupportFrigate_hyp1",
		TargetType = Ship,
		Time = 75,
	},
	-- #37.1, frigate_tech.lua
	{
		Cost = 1100,
		Description = "$11539",
		DisplayPriority = 34,
		DisplayedName = "$11538",
		Icon = Icon_Build,
		Name = "Tai_DefenseField_hyp0",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11538",
		TargetName = "Tai_FieldFrigate_hyp0",
		TargetType = Ship,
		Time = 80,
	},
	-- #37.2, frigate_tech.lua
	{
		Cost = 1100,
		Description = "$11539",
		DisplayPriority = 34,
		DisplayedName = "$11538",
		Icon = Icon_Build,
		Name = "Tai_DefenseField_hyp1",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11538",
		TargetName = "Tai_FieldFrigate_hyp1",
		TargetType = Ship,
		Time = 80,
	},
	-- #38.1, frigate_tech.lua
	{
		Cost = 1700,
		Description = "$11535",
		DisplayPriority = 33,
		DisplayedName = "$11534",
		Icon = Icon_Build,
		Name = "Tai_IonCannons_hyp0",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11534",
		TargetName = "Tai_IonCannonFrigate_hyp0",
		TargetType = Ship,
		Time = 120,
	},
	-- #38.2, frigate_tech.lua
	{
		Cost = 1700,
		Description = "$11535",
		DisplayPriority = 33,
		DisplayedName = "$11534",
		Icon = Icon_Build,
		Name = "Tai_IonCannons_hyp1",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11534",
		TargetName = "Tai_IonCannonFrigate_hyp1",
		TargetType = Ship,
		Time = 120,
	},
	-- #39.1, supercapital_tech.lua
	{
		Cost = 3500,
		Description = "$11547",
		DisplayPriority = 44,
		DisplayedName = "$11546",
		Icon = Icon_Build,
		Name = "Tai_GuidedMissiles_hyp0",
		RequiredResearch = "SuperCapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11546",
		TargetName = "Tai_MissileDestroyer_hyp0",
		TargetType = Ship,
		Time = 120,
	},
	-- #39.2, supercapital_tech.lua
	{
		Cost = 3500,
		Description = "$11547",
		DisplayPriority = 44,
		DisplayedName = "$11546",
		Icon = Icon_Build,
		Name = "Tai_GuidedMissiles_hyp1",
		RequiredResearch = "SuperCapitalShipDrive",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11546",
		TargetName = "Tai_MissileDestroyer_hyp1",
		TargetType = Ship,
		Time = 120,
	},
	-- #40.1, supercapital_tech.lua
	{
		Cost = 7000,
		Description = "$11551",
		DisplayPriority = 46,
		DisplayedName = "$11550",
		Icon = Icon_Build,
		Name = "Tai_HeavyGuns_hyp0",
		RequiredResearch = "SuperHeavyChassis & SuperCapitalShipDrive & IonCannons",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11550",
		TargetName = "Tai_HeavyCruiser_hyp0",
		TargetType = Ship,
		Time = 360,
	},
	-- #40.2, supercapital_tech.lua
	{
		Cost = 7000,
		Description = "$11551",
		DisplayPriority = 46,
		DisplayedName = "$11550",
		Icon = Icon_Build,
		Name = "Tai_HeavyGuns_hyp1",
		RequiredResearch = "SuperHeavyChassis & SuperCapitalShipDrive & IonCannons",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11550",
		TargetName = "Tai_HeavyCruiser_hyp1",
		TargetType = Ship,
		Time = 360,
	},
	-- #41.1, supercapital_tech.lua
	{
		Cost = 1500,
		Description = "$11543",
		DisplayPriority = 41,
		DisplayedName = "$11542",
		Icon = Icon_Build,
		Name = "Tai_SuperCapitalShipDrive_res0_hyp0",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res0_hyp0",
		TargetType = Ship,
		Time = 50,
	},
	-- #41.2, supercapital_tech.lua
	{
		Cost = 1500,
		Description = "$11543",
		DisplayPriority = 41,
		DisplayedName = "$11542",
		Icon = Icon_Build,
		Name = "Tai_SuperCapitalShipDrive_res1_hyp0",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res1_hyp0",
		TargetType = Ship,
		Time = 50,
	},
	-- #41.3, supercapital_tech.lua
	{
		Cost = 1500,
		Description = "$11543",
		DisplayPriority = 41,
		DisplayedName = "$11542",
		Icon = Icon_Build,
		Name = "Tai_SuperCapitalShipDrive_res0_hyp1",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res0_hyp1",
		TargetType = Ship,
		Time = 50,
	},
	-- #41.4, supercapital_tech.lua
	{
		Cost = 1500,
		Description = "$11543",
		DisplayPriority = 41,
		DisplayedName = "$11542",
		Icon = Icon_Build,
		Name = "Tai_SuperCapitalShipDrive_res1_hyp1",
		RequiredResearch = "CapitalShipChassis",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11542",
		TargetName = "Tai_Carrier_res1_hyp1",
		TargetType = Ship,
		Time = 50,
	},
	-- #42.1, supercapital_tech.lua
	{
		Cost = 4000,
		Description = "$11561",
		DisplayPriority = 45,
		DisplayedName = "$11560",
		Icon = Icon_Build,
		Name = "Tai_SuperHeavyChassis_hyp0",
		RequiredResearch = "SuperCapitalShipDrive & IonCannons",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11560",
		TargetName = "Tai_Destroyer_hyp0",
		TargetType = Ship,
		Time = 140,
	},
	-- #42.2, supercapital_tech.lua
	{
		Cost = 4000,
		Description = "$11561",
		DisplayPriority = 45,
		DisplayedName = "$11560",
		Icon = Icon_Build,
		Name = "Tai_SuperHeavyChassis_hyp1",
		RequiredResearch = "SuperCapitalShipDrive & IonCannons",
		RequiredSubSystems = "Research",
		ShortDisplayedName = "$11560",
		TargetName = "Tai_Destroyer_hyp1",
		TargetType = Ship,
		Time = 140,
	},
}
