build =
{
	-- #1.1, capital_builds.lua
	{
		Description = "$7061",
		DisplayPriority = 118,
		DisplayedName = "$7060",
		RequiredFleetSubSystems = "",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Battlecruiser_hyp0",
		Type = Ship,
	},
	-- #1.2, capital_builds.lua
	{
		Description = "$7061",
		DisplayPriority = 118,
		DisplayedName = "$7060",
		RequiredFleetSubSystems = "",
		RequiredResearch = "BattlecruiserIonWeapons",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Battlecruiser_hyp1",
		Type = Ship,
	},
	-- #2.1, capital_builds.lua
	{
		Description = "$7057",
		DisplayPriority = 116,
		DisplayedName = "$7056",
		RequiredFleetSubSystems = "",
		RequiredResearch = "DestroyerTech",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Destroyer_hyp0",
		Type = Ship,
	},
	-- #2.2, capital_builds.lua
	{
		Description = "$7057",
		DisplayPriority = 116,
		DisplayedName = "$7056",
		RequiredFleetSubSystems = "",
		RequiredResearch = "DestroyerTech",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Destroyer_hyp1",
		Type = Ship,
	},
	-- #3.1, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #3.2, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #3.3, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #3.4, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #3.5, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #3.6, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #3.7, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #3.8, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #3.9, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #3.10, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #3.11, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #3.12, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #3.13, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #3.14, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #3.15, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car0_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #3.16, carrier_builds.lua
	{
		Description = "$7055",
		DisplayPriority = 110,
		DisplayedName = "$7054",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CapShipProduction",
		ThingToBuild = "Hgn_Carrier_car1_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #4.1, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car0_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #4.2, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car1_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #4.3, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car0_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #4.4, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car1_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #4.5, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car0_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #4.6, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car1_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #4.7, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car0_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #4.8, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car1_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #4.9, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car0_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #4.10, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car1_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #4.11, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car0_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #4.12, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_car1_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #4.13, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car0_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #4.14, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car1_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #4.15, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car0_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #4.16, carrier_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_car1_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #5.1, carrier_builds.lua
	{
		Description = "$7019",
		DisplayPriority = 50,
		DisplayedName = "$7018",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_CloakGenerator_rch0",
		Type = SubSystem,
	},
	-- #5.2, carrier_builds.lua
	{
		Description = "$7019",
		DisplayPriority = 50,
		DisplayedName = "$7018",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_CloakGenerator_rch1",
		Type = SubSystem,
	},
	-- #6.1, carrier_builds.lua
	{
		Description = "$7021",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_FireControl_rch0",
		Type = SubSystem,
	},
	-- #6.2, carrier_builds.lua
	{
		Description = "$7021",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		RequiredFleetSubSystems = "AdvancedResearch",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_FireControl_rch1",
		Type = SubSystem,
	},
	-- #7.1, carrier_builds.lua
	{
		Description = "$7015",
		DisplayPriority = 30,
		DisplayedName = "$7014",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_Hyperspace_rch0",
		Type = SubSystem,
	},
	-- #7.2, carrier_builds.lua
	{
		Description = "$7015",
		DisplayPriority = 30,
		DisplayedName = "$7014",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_Hyperspace_rch1",
		Type = SubSystem,
	},
	-- #8.1, carrier_builds.lua
	{
		Description = "$7017",
		DisplayPriority = 40,
		DisplayedName = "$1826",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_HyperspaceInhibitor_rch0",
		Type = SubSystem,
	},
	-- #8.2, carrier_builds.lua
	{
		Description = "$7017",
		DisplayPriority = 40,
		DisplayedName = "$1826",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_HyperspaceInhibitor_rch1",
		Type = SubSystem,
	},
	-- #9.0, carrier_builds.lua
	{
		Description = "$7011",
		DisplayPriority = 0,
		DisplayedName = "$7010",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_Research",
		Type = SubSystem,
	},
	-- #10.0, carrier_builds.lua
	{
		Description = "$7013",
		DisplayPriority = 10,
		DisplayedName = "$7012",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_ResearchAdvanced",
		Type = SubSystem,
	},
	-- #11.0, carrier_builds.lua
	{
		Description = "$7023",
		DisplayPriority = 151,
		DisplayedName = "$7022",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Sensors_AdvancedArray",
		Type = SubSystem,
	},
	-- #12.0, carrier_builds.lua
	{
		Description = "$7025",
		DisplayPriority = 152,
		DisplayedName = "$7024",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Sensors_DetectCloaked",
		Type = SubSystem,
	},
	-- #13.0, carrier_builds.lua
	{
		Description = "$7037",
		DisplayPriority = 150,
		DisplayedName = "$7036",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Sensors_DetectHyperspace",
		Type = SubSystem,
	},
	-- #14.1, corvette_builds.lua
	{
		Description = "$7039",
		DisplayPriority = 50,
		DisplayedName = "$7038",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_AssaultCorvette_hyp0",
		Type = Ship,
	},
	-- #14.2, corvette_builds.lua
	{
		Description = "$7039",
		DisplayPriority = 50,
		DisplayedName = "$7038",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_AssaultCorvette_hyp1",
		Type = Ship,
	},
	-- #15.1, corvette_builds.lua
	{
		Description = "$7043",
		DisplayPriority = 52,
		DisplayedName = "$7042",
		RequiredFleetSubSystems = "",
		RequiredResearch = "GraviticAttractionMines",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_MinelayerCorvette_hyp0",
		Type = Ship,
	},
	-- #15.2, corvette_builds.lua
	{
		Description = "$7043",
		DisplayPriority = 52,
		DisplayedName = "$7042",
		RequiredFleetSubSystems = "",
		RequiredResearch = "GraviticAttractionMines",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_MinelayerCorvette_hyp1",
		Type = Ship,
	},
	-- #16.1, corvette_builds.lua
	{
		Description = "$7041",
		DisplayPriority = 51,
		DisplayedName = "$7040",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_PulsarCorvette_hyp0",
		Type = Ship,
	},
	-- #16.2, corvette_builds.lua
	{
		Description = "$7041",
		DisplayPriority = 51,
		DisplayedName = "$7040",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_PulsarCorvette_hyp1",
		Type = Ship,
	},
	-- #17.1, fighter_builds.lua
	{
		Description = "$7035",
		DisplayPriority = 30,
		DisplayedName = "$7034",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		ThingToBuild = "Hgn_AttackBomber_hyp0",
		Type = Ship,
	},
	-- #17.2, fighter_builds.lua
	{
		Description = "$7035",
		DisplayPriority = 30,
		DisplayedName = "$7034",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		ThingToBuild = "Hgn_AttackBomber_hyp1",
		Type = Ship,
	},
	-- #18.1, fighter_builds.lua
	{
		Description = "$7033",
		DisplayPriority = 20,
		DisplayedName = "$7032",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		ThingToBuild = "Hgn_Interceptor_hyp0",
		Type = Ship,
	},
	-- #18.2, fighter_builds.lua
	{
		Description = "$7033",
		DisplayPriority = 20,
		DisplayedName = "$7032",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FighterProduction",
		ThingToBuild = "Hgn_Interceptor_hyp1",
		Type = Ship,
	},
	-- #19.1, fighter_builds.lua
	{
		Description = "$7031",
		DisplayPriority = 10,
		DisplayedName = "$7030",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Scout_hyp0",
		Type = Ship,
	},
	-- #19.2, fighter_builds.lua
	{
		Description = "$7031",
		DisplayPriority = 10,
		DisplayedName = "$7030",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Scout_hyp1",
		Type = Ship,
	},
	-- #20.1, frigate_builds.lua
	{
		Description = "$7049",
		DisplayPriority = 60,
		DisplayedName = "$7048",
		RequiredFleetSubSystems = "",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_AssaultFrigate_hyp0",
		Type = Ship,
	},
	-- #20.2, frigate_builds.lua
	{
		Description = "$7049",
		DisplayPriority = 60,
		DisplayedName = "$7048",
		RequiredFleetSubSystems = "",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_AssaultFrigate_hyp1",
		Type = Ship,
	},
	-- #21.1, frigate_builds.lua
	{
		Description = "$7045",
		DisplayPriority = 80,
		DisplayedName = "$7044",
		RequiredFleetSubSystems = "",
		RequiredResearch = "DefenseFieldFrigateShield",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_DefenseFieldFrigate_hyp0",
		Type = Ship,
	},
	-- #21.2, frigate_builds.lua
	{
		Description = "$7045",
		DisplayPriority = 80,
		DisplayedName = "$7044",
		RequiredFleetSubSystems = "",
		RequiredResearch = "DefenseFieldFrigateShield",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_DefenseFieldFrigate_hyp1",
		Type = Ship,
	},
	-- #22.1, frigate_builds.lua
	{
		Description = "$7051",
		DisplayPriority = 70,
		DisplayedName = "$1520",
		RequiredFleetSubSystems = "",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_IonCannonFrigate_hyp0",
		Type = Ship,
	},
	-- #22.2, frigate_builds.lua
	{
		Description = "$7051",
		DisplayPriority = 70,
		DisplayedName = "$1520",
		RequiredFleetSubSystems = "",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_IonCannonFrigate_hyp1",
		Type = Ship,
	},
	-- #23.1, frigate_builds.lua
	{
		Description = "$7053",
		DisplayPriority = 75,
		DisplayedName = "$7052",
		RequiredFleetSubSystems = "",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_MarineFrigate_hyp0",
		Type = Ship,
	},
	-- #23.2, frigate_builds.lua
	{
		Description = "$7053",
		DisplayPriority = 75,
		DisplayedName = "$7052",
		RequiredFleetSubSystems = "",
		RequiredResearch = "InstaAdvancedFrigateTech",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_MarineFrigate_hyp1",
		Type = Ship,
	},
	-- #24.1, frigate_builds.lua
	{
		Description = "$7047",
		DisplayPriority = 65,
		DisplayedName = "$7046",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_TorpedoFrigate_hyp0",
		Type = Ship,
	},
	-- #24.2, frigate_builds.lua
	{
		Description = "$7047",
		DisplayPriority = 65,
		DisplayedName = "$7046",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "FrigateProduction",
		ThingToBuild = "Hgn_TorpedoFrigate_hyp1",
		Type = Ship,
	},
	-- #25.1, mothership_builds.lua
	{
		Description = "$7019",
		DisplayPriority = 50,
		DisplayedName = "$7018",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_CloakGenerator_rch0",
		Type = SubSystem,
	},
	-- #25.2, mothership_builds.lua
	{
		Description = "$7019",
		DisplayPriority = 50,
		DisplayedName = "$7018",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_CloakGenerator_rch1",
		Type = SubSystem,
	},
	-- #26.1, mothership_builds.lua
	{
		Description = "$7021",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_FireControl_rch0",
		Type = SubSystem,
	},
	-- #26.2, mothership_builds.lua
	{
		Description = "$7021",
		DisplayPriority = 60,
		DisplayedName = "$7020",
		RequiredFleetSubSystems = "AdvancedResearch",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_FireControl_rch1",
		Type = SubSystem,
	},
	-- #27.1, mothership_builds.lua
	{
		Description = "$7015",
		DisplayPriority = 30,
		DisplayedName = "$7014",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_Hyperspace_rch0",
		Type = SubSystem,
	},
	-- #27.2, mothership_builds.lua
	{
		Description = "$7015",
		DisplayPriority = 30,
		DisplayedName = "$7014",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_Hyperspace_rch1",
		Type = SubSystem,
	},
	-- #28.1, mothership_builds.lua
	{
		Description = "$7017",
		DisplayPriority = 40,
		DisplayedName = "$1826",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_HyperspaceInhibitor_rch0",
		Type = SubSystem,
	},
	-- #28.2, mothership_builds.lua
	{
		Description = "$7017",
		DisplayPriority = 40,
		DisplayedName = "$1826",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_HyperspaceInhibitor_rch1",
		Type = SubSystem,
	},
	-- #29.0, mothership_builds.lua
	{
		Description = "$7011",
		DisplayPriority = 0,
		DisplayedName = "$7010",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_Research",
		Type = SubSystem,
	},
	-- #30.0, mothership_builds.lua
	{
		Description = "$7013",
		DisplayPriority = 10,
		DisplayedName = "$7012",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_ResearchAdvanced",
		Type = SubSystem,
	},
	-- #31.0, mothership_builds.lua
	{
		Description = "$7023",
		DisplayPriority = 151,
		DisplayedName = "$7022",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Sensors_AdvancedArray",
		Type = SubSystem,
	},
	-- #32.0, mothership_builds.lua
	{
		Description = "$7025",
		DisplayPriority = 152,
		DisplayedName = "$7024",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Sensors_DetectCloaked",
		Type = SubSystem,
	},
	-- #33.0, mothership_builds.lua
	{
		Description = "$7037",
		DisplayPriority = 150,
		DisplayedName = "$7036",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Sensors_DetectHyperspace",
		Type = SubSystem,
	},
	-- #34.1, platform_builds.lua
	{
		Description = "$7063",
		DisplayPriority = 141,
		DisplayedName = "$7062",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "PlatformProduction",
		ThingToBuild = "Hgn_GunTurret_hyp0",
		Type = Ship,
	},
	-- #34.2, platform_builds.lua
	{
		Description = "$7063",
		DisplayPriority = 141,
		DisplayedName = "$7062",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "PlatformProduction",
		ThingToBuild = "Hgn_GunTurret_hyp1",
		Type = Ship,
	},
	-- #35.1, platform_builds.lua
	{
		Description = "$7065",
		DisplayPriority = 142,
		DisplayedName = "$1514",
		RequiredFleetSubSystems = "",
		RequiredResearch = "PlatformIonWeapons",
		RequiredShipSubSystems = "PlatformProduction",
		ThingToBuild = "Hgn_IonTurret_hyp0",
		Type = Ship,
	},
	-- #35.2, platform_builds.lua
	{
		Description = "$7065",
		DisplayPriority = 142,
		DisplayedName = "$1514",
		RequiredFleetSubSystems = "",
		RequiredResearch = "PlatformIonWeapons",
		RequiredShipSubSystems = "PlatformProduction",
		ThingToBuild = "Hgn_IonTurret_hyp1",
		Type = Ship,
	},
	-- #36.0, production_builds.lua
	{
		Description = "$7009",
		DisplayPriority = 10,
		DisplayedName = "$7008",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Module_PlatformControl",
		Type = SubSystem,
	},
	-- #37.1, production_builds.lua
	{
		Description = "$7003",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Production_Corvette_rch0",
		Type = SubSystem,
	},
	-- #37.2, production_builds.lua
	{
		Description = "$7003",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Production_Corvette_rch1",
		Type = SubSystem,
	},
	-- #38.0, production_builds.lua
	{
		Description = "$7001",
		DisplayPriority = 0,
		DisplayedName = "$7000",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Production_Fighter",
		Type = SubSystem,
	},
	-- #39.1, production_builds.lua
	{
		Description = "$7005",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Production_Frigate_rch0",
		Type = SubSystem,
	},
	-- #39.2, production_builds.lua
	{
		Description = "$7005",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_C_Production_Frigate_rch1",
		Type = SubSystem,
	},
	-- #40.0, production_builds.lua
	{
		Description = "$7009",
		DisplayPriority = 20,
		DisplayedName = "$7008",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Module_PlatformControl",
		Type = SubSystem,
	},
	-- #41.0, production_builds.lua
	{
		Description = "$7007",
		DisplayPriority = 0,
		DisplayedName = "$7006",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_CapShip",
		Type = SubSystem,
	},
	-- #42.1, production_builds.lua
	{
		Description = "$7003",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_Corvette_rch0",
		Type = SubSystem,
	},
	-- #42.2, production_builds.lua
	{
		Description = "$7003",
		DisplayPriority = 0,
		DisplayedName = "$7002",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_Corvette_rch1",
		Type = SubSystem,
	},
	-- #43.0, production_builds.lua
	{
		Description = "$7001",
		DisplayPriority = 0,
		DisplayedName = "$7000",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_Fighter",
		Type = SubSystem,
	},
	-- #44.1, production_builds.lua
	{
		Description = "$7005",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_Frigate_rch0",
		Type = SubSystem,
	},
	-- #44.2, production_builds.lua
	{
		Description = "$7005",
		DisplayPriority = 0,
		DisplayedName = "$7004",
		RequiredFleetSubSystems = "Research",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_MS_Production_Frigate_rch1",
		Type = SubSystem,
	},
	-- #45.0, production_builds.lua
	{
		Description = "$7007",
		DisplayPriority = 0,
		DisplayedName = "$7006",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_SY_Production_CapShip",
		Type = SubSystem,
	},
	-- #46.1, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #46.2, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #46.3, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #46.4, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #46.5, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #46.6, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #46.7, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #46.8, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #46.9, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #46.10, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #46.11, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #46.12, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #46.13, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #46.14, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #46.15, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car0_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #46.16, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_Elohim_car1_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #47.1, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #47.2, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch0_res0_hyp0",
		Type = Ship,
	},
	-- #47.3, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #47.4, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch0_res1_hyp0",
		Type = Ship,
	},
	-- #47.5, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #47.6, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch0_res0_hyp1",
		Type = Ship,
	},
	-- #47.7, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #47.8, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch0_res1_hyp1",
		Type = Ship,
	},
	-- #47.9, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #47.10, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch1_res0_hyp0",
		Type = Ship,
	},
	-- #47.11, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #47.12, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch1_res1_hyp0",
		Type = Ship,
	},
	-- #47.13, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #47.14, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch1_res0_hyp1",
		Type = Ship,
	},
	-- #47.15, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car0_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #47.16, singleplayer_builds.lua
	{
		Description = "$7059",
		DisplayPriority = 117,
		DisplayedName = "$7058",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "Hyperspace",
		ThingToBuild = "Hgn_Shipyard_SPG_car1_rch1_res1_hyp1",
		Type = Ship,
	},
	-- #48.1, singleplayer_builds.lua
	{
		Description = "$7914",
		DisplayPriority = 53,
		DisplayedName = "$7913",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Kpr_Mover_hyp0",
		Type = Ship,
	},
	-- #48.2, singleplayer_builds.lua
	{
		Description = "$7914",
		DisplayPriority = 53,
		DisplayedName = "$7913",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Kpr_Mover_hyp1",
		Type = Ship,
	},
	-- #49.0, singleplayer_builds.lua
	{
		Description = "$7911",
		DisplayPriority = 10,
		DisplayedName = "$7910",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "CorvetteProduction",
		ThingToBuild = "Hgn_MS_Production_CorvetteMover",
		Type = SubSystem,
	},
	-- #50.1, utility_builds.lua
	{
		Description = "$7075",
		DisplayPriority = 160,
		DisplayedName = "$7074",
		RequiredFleetSubSystems = "",
		RequiredResearch = "ECMProbe",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ECMProbe_hyp0",
		Type = Ship,
	},
	-- #50.2, utility_builds.lua
	{
		Description = "$7075",
		DisplayPriority = 160,
		DisplayedName = "$7074",
		RequiredFleetSubSystems = "",
		RequiredResearch = "ECMProbe",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ECMProbe_hyp1",
		Type = Ship,
	},
	-- #51.1, utility_builds.lua
	{
		Description = "$7071",
		DisplayPriority = 140,
		DisplayedName = "$7070",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Probe_hyp0",
		Type = Ship,
	},
	-- #51.2, utility_builds.lua
	{
		Description = "$7071",
		DisplayPriority = 140,
		DisplayedName = "$7070",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_Probe_hyp1",
		Type = Ship,
	},
	-- #52.1, utility_builds.lua
	{
		Description = "$7073",
		DisplayPriority = 150,
		DisplayedName = "$7072",
		RequiredFleetSubSystems = "",
		RequiredResearch = "SensDisProbe",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ProximitySensor_hyp0",
		Type = Ship,
	},
	-- #52.2, utility_builds.lua
	{
		Description = "$7073",
		DisplayPriority = 150,
		DisplayedName = "$7072",
		RequiredFleetSubSystems = "",
		RequiredResearch = "SensDisProbe",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ProximitySensor_hyp1",
		Type = Ship,
	},
	-- #53.1, utility_builds.lua
	{
		Description = "$7067",
		DisplayPriority = 120,
		DisplayedName = "$7066",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceCollector_hyp0",
		Type = Ship,
	},
	-- #53.2, utility_builds.lua
	{
		Description = "$7067",
		DisplayPriority = 120,
		DisplayedName = "$7066",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceCollector_hyp1",
		Type = Ship,
	},
	-- #54.1, utility_builds.lua
	{
		Description = "$7069",
		DisplayPriority = 130,
		DisplayedName = "$7068",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceController_res0_hyp0",
		Type = Ship,
	},
	-- #54.2, utility_builds.lua
	{
		Description = "$7069",
		DisplayPriority = 130,
		DisplayedName = "$7068",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceController_res1_hyp0",
		Type = Ship,
	},
	-- #54.3, utility_builds.lua
	{
		Description = "$7069",
		DisplayPriority = 130,
		DisplayedName = "$7068",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceController_res0_hyp1",
		Type = Ship,
	},
	-- #54.4, utility_builds.lua
	{
		Description = "$7069",
		DisplayPriority = 130,
		DisplayedName = "$7068",
		RequiredFleetSubSystems = "",
		RequiredResearch = "",
		RequiredShipSubSystems = "",
		ThingToBuild = "Hgn_ResourceController_res1_hyp1",
		Type = Ship,
	},
}
