::Place the Python script into the SHIP or SUBSYSTEM directory.
copy NUL buildtimes.csv
python.exe "GetBuildTimes.py" subs "hgn_c_module_cloakgenerator_rch0"
python.exe "GetBuildTimes.py" subs "hgn_c_module_cloakgenerator_rch1"
python.exe "GetBuildTimes.py" subs "hgn_c_module_firecontrol_rch0"
python.exe "GetBuildTimes.py" subs "hgn_c_module_firecontrol_rch1"
python.exe "GetBuildTimes.py" subs "hgn_c_module_hyperspaceinhibitor_rch0"
python.exe "GetBuildTimes.py" subs "hgn_c_module_hyperspaceinhibitor_rch1"
python.exe "GetBuildTimes.py" subs "hgn_c_module_hyperspace_rch0"
python.exe "GetBuildTimes.py" subs "hgn_c_module_hyperspace_rch1"
python.exe "GetBuildTimes.py" subs "hgn_ms_module_cloakgenerator_rch0"
python.exe "GetBuildTimes.py" subs "hgn_ms_module_cloakgenerator_rch1"
python.exe "GetBuildTimes.py" subs "hgn_ms_module_firecontrol_rch0"
python.exe "GetBuildTimes.py" subs "hgn_ms_module_firecontrol_rch1"
python.exe "GetBuildTimes.py" subs "hgn_ms_module_hyperspaceinhibitor_rch0"
python.exe "GetBuildTimes.py" subs "hgn_ms_module_hyperspaceinhibitor_rch1"
python.exe "GetBuildTimes.py" subs "hgn_ms_module_hyperspace_rch0"
python.exe "GetBuildTimes.py" subs "hgn_ms_module_hyperspace_rch1"
python.exe "GetBuildTimes.py" subs "vgr_c_module_cloakgenerator_rch0"
python.exe "GetBuildTimes.py" subs "vgr_c_module_cloakgenerator_rch1"
python.exe "GetBuildTimes.py" subs "vgr_c_module_firecontrol_rch0"
python.exe "GetBuildTimes.py" subs "vgr_c_module_firecontrol_rch1"
python.exe "GetBuildTimes.py" subs "vgr_c_module_hyperspaceinhibitor_rch0"
python.exe "GetBuildTimes.py" subs "vgr_c_module_hyperspaceinhibitor_rch1"
python.exe "GetBuildTimes.py" subs "vgr_c_production_corvette_car0"
python.exe "GetBuildTimes.py" subs "vgr_c_production_corvette_car1"
python.exe "GetBuildTimes.py" subs "vgr_c_production_fighter_car0"
python.exe "GetBuildTimes.py" subs "vgr_c_production_fighter_car1"
python.exe "GetBuildTimes.py" subs "vgr_ms_module_cloakgenerator_rch0"
python.exe "GetBuildTimes.py" subs "vgr_ms_module_cloakgenerator_rch1"
python.exe "GetBuildTimes.py" subs "vgr_ms_module_firecontrol_rch0"
python.exe "GetBuildTimes.py" subs "vgr_ms_module_firecontrol_rch1"
python.exe "GetBuildTimes.py" subs "vgr_ms_module_hyperspaceinhibitor_rch0"
python.exe "GetBuildTimes.py" subs "vgr_ms_module_hyperspaceinhibitor_rch1"
pause
