Path_Name		= "hiigaran_hwce"
Symbolic_Name	= "hiigaran_hwce"
Display_Name	= "Hiigaran (HWCE)"
Prefix			= "HGN_"
ExtFilter		= "races_dm_hwce,races_hw2,races_hgn,races_hwrm,races_dm_hw2"
Tags			= "race_dm_hwce"
SG_Pass_Tags	= "sgf_common,sgf_hgn"
