Path_Name		= "kushan_hwce"
Symbolic_Name	= "kushan_hwce"
Display_Name	= "Kushan (HWCE)"
Prefix			= "KUS_"
ExtFilter		= "races_dm_hwce,races_hw2,races_kus,races_hwrm,races_dm_hw2"
Tags			= "race_dm_hwce"
SG_Pass_Tags	= "sgf_common,sgf_kus"
