Path_Name		= "taiidan_hwce"
Symbolic_Name	= "taiidan_hwce"
Display_Name	= "Taiidan (HWCE)"
Prefix			= "TAI_"
ExtFilter		= "races_dm_hwce,races_hw2,races_tai,races_hwrm,races_dm_hw2"
Tags			= "race_dm_hwce"
SG_Pass_Tags	= "sgf_common,sgf_tai"
