Path_Name		= "vaygr_hwce"
Symbolic_Name	= "vaygr_hwce"
Display_Name	= "Vaygr (HWCE)"
Prefix			= "VGR_"
ExtFilter		= "races_dm_hwce,races_hw2,races_vgr,races_hwrm,races_dm_hw2"
Tags			= "race_dm_hwce"
SG_Pass_Tags	= "sgf_common,sgf_vgr"
